use crate::rbac::Role;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Confirmation {
    None,
    Required,
    Approval,
    Consent,
}

#[derive(Debug, Clone, Copy)]
pub struct CommandSpec {
    pub name: &'static str,
    pub role: Role,
    pub confirmation: Confirmation,
    pub description: &'static str,
    pub implemented: bool,
}

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "help",
        Role::Service,
        Confirmation::None,
        "Show help.",
        true,
    ),
    spec(
        "exit",
        Role::Service,
        Confirmation::None,
        "Exit Core Access.",
        true,
    ),
    spec(
        "quit",
        Role::Service,
        Confirmation::None,
        "Exit Core Access.",
        true,
    ),
    spec(
        "dashboard",
        Role::Service,
        Confirmation::None,
        "Show local dashboard.",
        true,
    ),
    spec(
        "auth whoami",
        Role::Service,
        Confirmation::None,
        "Show current identity.",
        true,
    ),
    spec(
        "commands list",
        Role::Service,
        Confirmation::None,
        "List command registry.",
        true,
    ),
    spec(
        "commands search",
        Role::Service,
        Confirmation::None,
        "Search command registry.",
        true,
    ),
    spec(
        "server status",
        Role::Service,
        Confirmation::None,
        "Show server status matrix.",
        true,
    ),
    spec(
        "logs list",
        Role::Service,
        Confirmation::None,
        "List log sources.",
        true,
    ),
    spec(
        "audit search",
        Role::Service,
        Confirmation::None,
        "Search local audit log.",
        true,
    ),
    spec(
        "audit export",
        Role::Service,
        Confirmation::None,
        "Export local audit lines.",
        true,
    ),
    spec(
        "note add",
        Role::Service,
        Confirmation::None,
        "Add linked note.",
        true,
    ),
    spec(
        "note list",
        Role::Service,
        Confirmation::None,
        "List linked notes.",
        true,
    ),
    spec(
        "note export",
        Role::Service,
        Confirmation::None,
        "Export linked notes.",
        true,
    ),
    spec(
        "approval request",
        Role::Service,
        Confirmation::None,
        "Create approval request.",
        true,
    ),
    spec(
        "approval list",
        Role::Service,
        Confirmation::None,
        "List approval queue.",
        true,
    ),
    spec(
        "approval approve",
        Role::Admin,
        Confirmation::Required,
        "Approve an approval request.",
        true,
    ),
    spec(
        "incident open",
        Role::Service,
        Confirmation::None,
        "Open local incident workspace.",
        true,
    ),
    spec(
        "incident list",
        Role::Service,
        Confirmation::None,
        "List local incident events.",
        true,
    ),
    spec(
        "incident status",
        Role::Service,
        Confirmation::None,
        "Show local incident status.",
        true,
    ),
    spec(
        "incident note",
        Role::Service,
        Confirmation::None,
        "Add incident note.",
        true,
    ),
    spec(
        "incident pin",
        Role::Service,
        Confirmation::None,
        "Attach log evidence to incident.",
        true,
    ),
    spec(
        "incident export",
        Role::Service,
        Confirmation::None,
        "Export incident workspace.",
        true,
    ),
    spec(
        "incident close",
        Role::Service,
        Confirmation::None,
        "Close local incident workspace.",
        true,
    ),
    spec(
        "ops snapshot",
        Role::Service,
        Confirmation::None,
        "Write local incident snapshot.",
        true,
    ),
    spec(
        "ops timeline",
        Role::Service,
        Confirmation::None,
        "Show local ops timeline.",
        true,
    ),
    spec(
        "ops handoff",
        Role::Service,
        Confirmation::None,
        "Export local shift handoff.",
        true,
    ),
    spec(
        "ops doctor",
        Role::Service,
        Confirmation::None,
        "Run local Core Access readiness checks.",
        true,
    ),
    spec(
        "ops paths",
        Role::Service,
        Confirmation::None,
        "Show Core Access local paths.",
        true,
    ),
    spec(
        "ops exports",
        Role::Service,
        Confirmation::None,
        "List local Core Access exports.",
        true,
    ),
    spec(
        "maintenance status",
        Role::Service,
        Confirmation::None,
        "Show maintenance status.",
        true,
    ),
    spec(
        "server services",
        Role::Service,
        Confirmation::None,
        "List known service targets.",
        true,
    ),
    spec(
        "server agent-health",
        Role::Service,
        Confirmation::None,
        "Read admin-agent health.",
        true,
    ),
    spec(
        "server agent-system",
        Role::Service,
        Confirmation::None,
        "Read admin-agent system matrix.",
        true,
    ),
    spec(
        "server agent-services",
        Role::Service,
        Confirmation::None,
        "Read admin-agent service inventory.",
        true,
    ),
    spec(
        "server agent-service",
        Role::Service,
        Confirmation::None,
        "Read admin-agent service state.",
        true,
    ),
    spec(
        "server agent-logs",
        Role::Service,
        Confirmation::None,
        "Read admin-agent service logs.",
        true,
    ),
    spec(
        "nexus services",
        Role::Service,
        Confirmation::None,
        "List private Nexus admin-agent services.",
        true,
    ),
    spec(
        "server logs",
        Role::Service,
        Confirmation::None,
        "Tail service logs.",
        true,
    ),
    spec(
        "server restart",
        Role::Admin,
        Confirmation::Required,
        "Restart allowlisted service.",
        true,
    ),
    spec(
        "server start",
        Role::Admin,
        Confirmation::Required,
        "Start allowlisted service.",
        true,
    ),
    spec(
        "server stop",
        Role::Admin,
        Confirmation::Required,
        "Stop allowlisted service.",
        true,
    ),
    spec(
        "server update plan",
        Role::Admin,
        Confirmation::None,
        "Plan server update.",
        false,
    ),
    spec(
        "server update apply",
        Role::Admin,
        Confirmation::Required,
        "Apply server update.",
        false,
    ),
    spec(
        "ssh open",
        Role::Admin,
        Confirmation::Required,
        "Open SSH session.",
        false,
    ),
    spec(
        "health probe",
        Role::Service,
        Confirmation::None,
        "Run health probe.",
        true,
    ),
    spec(
        "logs tail",
        Role::Service,
        Confirmation::None,
        "Tail log source.",
        true,
    ),
    spec(
        "logs search",
        Role::Service,
        Confirmation::None,
        "Search logs.",
        true,
    ),
    spec(
        "logs filter",
        Role::Service,
        Confirmation::None,
        "Filter logs.",
        true,
    ),
    spec(
        "logs pin",
        Role::Service,
        Confirmation::None,
        "Pin selected log.",
        true,
    ),
    spec(
        "logs note",
        Role::Service,
        Confirmation::None,
        "Create log note.",
        true,
    ),
    spec(
        "logs export",
        Role::Service,
        Confirmation::None,
        "Export logs.",
        true,
    ),
    spec(
        "user search",
        Role::Service,
        Confirmation::None,
        "Search users.",
        true,
    ),
    spec(
        "user open",
        Role::Service,
        Confirmation::None,
        "Open user.",
        true,
    ),
    spec(
        "user create",
        Role::Admin,
        Confirmation::Required,
        "Create user.",
        false,
    ),
    spec(
        "user edit",
        Role::Admin,
        Confirmation::Required,
        "Edit user.",
        false,
    ),
    spec(
        "user disable",
        Role::Admin,
        Confirmation::Required,
        "Disable user.",
        false,
    ),
    spec(
        "user sessions",
        Role::Service,
        Confirmation::None,
        "List user sessions.",
        true,
    ),
    spec(
        "user devices",
        Role::Service,
        Confirmation::None,
        "List user devices.",
        true,
    ),
    spec(
        "user audit",
        Role::Service,
        Confirmation::None,
        "List user audit.",
        true,
    ),
    spec(
        "user revoke-sessions",
        Role::Admin,
        Confirmation::Required,
        "Revoke sessions.",
        false,
    ),
    spec(
        "user force-password-reset",
        Role::Admin,
        Confirmation::Required,
        "Force password reset.",
        false,
    ),
    spec(
        "user configs",
        Role::Service,
        Confirmation::None,
        "List user configs.",
        false,
    ),
    spec(
        "user config open",
        Role::Service,
        Confirmation::None,
        "Open user config.",
        false,
    ),
    spec(
        "user config diff",
        Role::Service,
        Confirmation::None,
        "Diff user config.",
        false,
    ),
    spec(
        "user config export",
        Role::Service,
        Confirmation::None,
        "Export user config.",
        false,
    ),
    spec(
        "user config edit",
        Role::Admin,
        Confirmation::Required,
        "Edit user config.",
        false,
    ),
    spec(
        "lobby list",
        Role::Service,
        Confirmation::None,
        "List lobbies.",
        true,
    ),
    spec(
        "lobby open",
        Role::Service,
        Confirmation::None,
        "Open lobby.",
        true,
    ),
    spec(
        "lobby create",
        Role::Admin,
        Confirmation::Required,
        "Create lobby.",
        false,
    ),
    spec(
        "lobby edit",
        Role::Admin,
        Confirmation::Required,
        "Edit lobby.",
        false,
    ),
    spec(
        "lobby close",
        Role::Service,
        Confirmation::Approval,
        "Close lobby.",
        false,
    ),
    spec(
        "lobby lock",
        Role::Service,
        Confirmation::Required,
        "Lock lobby.",
        false,
    ),
    spec(
        "lobby unlock",
        Role::Service,
        Confirmation::Required,
        "Unlock lobby.",
        false,
    ),
    spec(
        "lobby chat",
        Role::Service,
        Confirmation::None,
        "Open lobby chat.",
        false,
    ),
    spec(
        "lobby join-secret",
        Role::Admin,
        Confirmation::Required,
        "Secret admin observer.",
        false,
    ),
    spec(
        "lobby broadcast",
        Role::Service,
        Confirmation::Required,
        "Broadcast to lobby.",
        false,
    ),
    spec(
        "room list",
        Role::Service,
        Confirmation::None,
        "List rooms.",
        false,
    ),
    spec(
        "room open",
        Role::Service,
        Confirmation::None,
        "Open room.",
        false,
    ),
    spec(
        "room summary",
        Role::Service,
        Confirmation::None,
        "Room summary.",
        false,
    ),
    spec(
        "room events",
        Role::Service,
        Confirmation::None,
        "Room events.",
        false,
    ),
    spec(
        "room logs",
        Role::Service,
        Confirmation::None,
        "Room logs.",
        false,
    ),
    spec(
        "room snapshot",
        Role::Service,
        Confirmation::None,
        "Snapshot room.",
        false,
    ),
    spec(
        "room sync",
        Role::Admin,
        Confirmation::Required,
        "Force room sync.",
        false,
    ),
    spec(
        "room pending-items",
        Role::Service,
        Confirmation::None,
        "Pending items.",
        false,
    ),
    spec(
        "room client-reports",
        Role::Service,
        Confirmation::None,
        "Client reports.",
        false,
    ),
    spec(
        "room request-sklmi-reconnect",
        Role::Service,
        Confirmation::Required,
        "Request SKLMI reconnect.",
        false,
    ),
    spec(
        "room disconnect-runtime",
        Role::Admin,
        Confirmation::Required,
        "Disconnect runtime.",
        false,
    ),
    spec(
        "room give-item",
        Role::Admin,
        Confirmation::Required,
        "Give item.",
        false,
    ),
    spec(
        "client broadcast",
        Role::Service,
        Confirmation::Required,
        "Broadcast to clients.",
        false,
    ),
    spec(
        "client maintenance-banner",
        Role::Admin,
        Confirmation::Required,
        "Client maintenance banner.",
        false,
    ),
    spec(
        "client force-update-prompt",
        Role::Admin,
        Confirmation::Required,
        "Force update prompt.",
        false,
    ),
    spec(
        "client request-relogin",
        Role::Service,
        Confirmation::Required,
        "Request relogin.",
        false,
    ),
    spec(
        "client refresh-lobby",
        Role::Service,
        Confirmation::None,
        "Refresh lobby.",
        false,
    ),
    spec(
        "client refresh-room",
        Role::Service,
        Confirmation::None,
        "Refresh room.",
        false,
    ),
    spec(
        "client request-sklmi-reconnect",
        Role::Service,
        Confirmation::Required,
        "Client SKLMI reconnect.",
        false,
    ),
    spec(
        "client restart-runtime",
        Role::Admin,
        Confirmation::Required,
        "Restart client runtime.",
        false,
    ),
    spec(
        "client clear-cache-request",
        Role::Service,
        Confirmation::Approval,
        "Request clear cache.",
        false,
    ),
    spec(
        "client diagnostics-request",
        Role::Service,
        Confirmation::Consent,
        "Request diagnostics.",
        true,
    ),
    spec(
        "client diagnostics-list",
        Role::Service,
        Confirmation::None,
        "List diagnostics requests.",
        true,
    ),
    spec(
        "client diagnostics-export",
        Role::Service,
        Confirmation::None,
        "Export diagnostics requests.",
        true,
    ),
    spec(
        "broadcast global",
        Role::Admin,
        Confirmation::Required,
        "Global broadcast.",
        false,
    ),
    spec(
        "broadcast server",
        Role::Admin,
        Confirmation::Required,
        "Server broadcast.",
        false,
    ),
    spec(
        "broadcast lobby",
        Role::Service,
        Confirmation::Required,
        "Lobby broadcast.",
        false,
    ),
    spec(
        "broadcast room",
        Role::Service,
        Confirmation::Required,
        "Room broadcast.",
        false,
    ),
    spec(
        "broadcast role",
        Role::Admin,
        Confirmation::Required,
        "Role broadcast.",
        false,
    ),
    spec(
        "broadcast version",
        Role::Admin,
        Confirmation::Required,
        "Version broadcast.",
        false,
    ),
    spec(
        "broadcast game",
        Role::Service,
        Confirmation::Required,
        "Game broadcast.",
        false,
    ),
    spec(
        "maintenance enable",
        Role::Admin,
        Confirmation::Required,
        "Enable maintenance.",
        false,
    ),
    spec(
        "maintenance disable",
        Role::Admin,
        Confirmation::Required,
        "Disable maintenance.",
        false,
    ),
    spec(
        "maintenance schedule",
        Role::Admin,
        Confirmation::Required,
        "Schedule maintenance.",
        true,
    ),
    spec(
        "maintenance broadcast",
        Role::Admin,
        Confirmation::Required,
        "Maintenance broadcast.",
        false,
    ),
    spec(
        "maintenance history",
        Role::Service,
        Confirmation::None,
        "Maintenance history.",
        true,
    ),
    spec(
        "release current",
        Role::Service,
        Confirmation::None,
        "Current release.",
        false,
    ),
    spec(
        "release list",
        Role::Service,
        Confirmation::None,
        "List releases.",
        false,
    ),
    spec(
        "release verify",
        Role::Service,
        Confirmation::None,
        "Verify release.",
        false,
    ),
    spec(
        "release verify-cdn",
        Role::Service,
        Confirmation::None,
        "Verify CDN.",
        false,
    ),
    spec(
        "release compare",
        Role::Service,
        Confirmation::None,
        "Compare releases.",
        false,
    ),
    spec(
        "release publish",
        Role::Admin,
        Confirmation::Required,
        "Publish release.",
        false,
    ),
    spec(
        "release rollback",
        Role::Admin,
        Confirmation::Required,
        "Rollback release.",
        false,
    ),
    spec(
        "release schedule",
        Role::Admin,
        Confirmation::Required,
        "Schedule release.",
        false,
    ),
    spec(
        "release notes",
        Role::Service,
        Confirmation::None,
        "Release notes.",
        false,
    ),
    spec(
        "release audit",
        Role::Service,
        Confirmation::None,
        "Release audit.",
        false,
    ),
    spec(
        "client-banner list",
        Role::Service,
        Confirmation::None,
        "List client banners.",
        true,
    ),
    spec(
        "client-banner edit",
        Role::Admin,
        Confirmation::Required,
        "Edit client banner.",
        true,
    ),
    spec(
        "client-banner preview",
        Role::Service,
        Confirmation::None,
        "Preview banner.",
        true,
    ),
    spec(
        "client-banner publish",
        Role::Admin,
        Confirmation::Required,
        "Publish banner.",
        false,
    ),
    spec(
        "client-banner rollback",
        Role::Admin,
        Confirmation::Required,
        "Rollback banner.",
        false,
    ),
    spec(
        "client-banner disable",
        Role::Admin,
        Confirmation::Required,
        "Disable banner.",
        false,
    ),
    spec(
        "pack repo list",
        Role::Service,
        Confirmation::None,
        "List pack repos.",
        true,
    ),
    spec(
        "pack repo add",
        Role::Admin,
        Confirmation::Required,
        "Add pack repo.",
        true,
    ),
    spec(
        "pack repo edit",
        Role::Admin,
        Confirmation::Required,
        "Edit pack repo.",
        false,
    ),
    spec(
        "pack repo disable",
        Role::Admin,
        Confirmation::Required,
        "Disable pack repo.",
        false,
    ),
    spec(
        "pack repo delete",
        Role::Admin,
        Confirmation::Required,
        "Delete pack repo.",
        false,
    ),
    spec(
        "pack check",
        Role::Service,
        Confirmation::None,
        "Check pack.",
        false,
    ),
    spec(
        "pack validate",
        Role::Service,
        Confirmation::None,
        "Validate pack.",
        false,
    ),
    spec(
        "pack stage",
        Role::Admin,
        Confirmation::Required,
        "Stage pack.",
        false,
    ),
    spec(
        "pack publish",
        Role::Admin,
        Confirmation::Required,
        "Publish pack.",
        false,
    ),
    spec(
        "pack rollback",
        Role::Admin,
        Confirmation::Required,
        "Rollback pack.",
        false,
    ),
    spec(
        "pack schedule-check",
        Role::Admin,
        Confirmation::Required,
        "Schedule pack check.",
        true,
    ),
    spec(
        "schedule list",
        Role::Service,
        Confirmation::None,
        "List scheduled jobs.",
        true,
    ),
    spec(
        "schedule calendar",
        Role::Service,
        Confirmation::None,
        "Calendar view.",
        true,
    ),
    spec(
        "schedule add",
        Role::Admin,
        Confirmation::Required,
        "Add schedule.",
        true,
    ),
    spec(
        "schedule edit",
        Role::Admin,
        Confirmation::Required,
        "Edit schedule.",
        false,
    ),
    spec(
        "schedule pause",
        Role::Admin,
        Confirmation::Required,
        "Pause schedule.",
        false,
    ),
    spec(
        "schedule resume",
        Role::Admin,
        Confirmation::Required,
        "Resume schedule.",
        false,
    ),
    spec(
        "schedule run-now",
        Role::Admin,
        Confirmation::Required,
        "Run schedule now.",
        false,
    ),
    spec(
        "schedule history",
        Role::Service,
        Confirmation::None,
        "Schedule history.",
        true,
    ),
    spec(
        "discord status",
        Role::Service,
        Confirmation::None,
        "Discord bot status.",
        false,
    ),
    spec(
        "discord reload",
        Role::Admin,
        Confirmation::Required,
        "Reload Discord bot.",
        false,
    ),
    spec(
        "discord announce",
        Role::Service,
        Confirmation::Required,
        "Discord announce.",
        false,
    ),
    spec(
        "discord sync-roles",
        Role::Admin,
        Confirmation::Required,
        "Sync Discord roles.",
        false,
    ),
    spec(
        "discord command list",
        Role::Service,
        Confirmation::None,
        "List Discord commands.",
        false,
    ),
    spec(
        "discord command enable",
        Role::Admin,
        Confirmation::Required,
        "Enable Discord command.",
        false,
    ),
    spec(
        "discord command disable",
        Role::Admin,
        Confirmation::Required,
        "Disable Discord command.",
        false,
    ),
    spec(
        "discord command edit",
        Role::Admin,
        Confirmation::Required,
        "Edit Discord command.",
        false,
    ),
    spec(
        "discord timer list",
        Role::Service,
        Confirmation::None,
        "List Discord timers.",
        false,
    ),
    spec(
        "discord timer edit",
        Role::Admin,
        Confirmation::Required,
        "Edit Discord timer.",
        false,
    ),
    spec(
        "discord incident-post",
        Role::Service,
        Confirmation::Required,
        "Post Discord incident.",
        false,
    ),
    spec(
        "discord logs",
        Role::Service,
        Confirmation::None,
        "Discord logs.",
        false,
    ),
    spec(
        "twitch status",
        Role::Service,
        Confirmation::None,
        "Twitch bot status.",
        false,
    ),
    spec(
        "twitch connect",
        Role::Admin,
        Confirmation::Required,
        "Connect Twitch channel.",
        false,
    ),
    spec(
        "twitch disconnect",
        Role::Admin,
        Confirmation::Required,
        "Disconnect Twitch channel.",
        false,
    ),
    spec(
        "twitch announce",
        Role::Service,
        Confirmation::Required,
        "Twitch announce.",
        false,
    ),
    spec(
        "twitch command list",
        Role::Service,
        Confirmation::None,
        "List Twitch commands.",
        false,
    ),
    spec(
        "twitch command enable",
        Role::Admin,
        Confirmation::Required,
        "Enable Twitch command.",
        false,
    ),
    spec(
        "twitch command disable",
        Role::Admin,
        Confirmation::Required,
        "Disable Twitch command.",
        false,
    ),
    spec(
        "twitch command edit",
        Role::Admin,
        Confirmation::Required,
        "Edit Twitch command.",
        false,
    ),
    spec(
        "twitch timer list",
        Role::Service,
        Confirmation::None,
        "List Twitch timers.",
        false,
    ),
    spec(
        "twitch timer edit",
        Role::Admin,
        Confirmation::Required,
        "Edit Twitch timer.",
        false,
    ),
    spec(
        "twitch lobby announce",
        Role::Service,
        Confirmation::Required,
        "Announce lobby.",
        false,
    ),
    spec(
        "twitch stream set-title-hint",
        Role::Service,
        Confirmation::None,
        "Stream title hint.",
        false,
    ),
    spec(
        "twitch logs",
        Role::Service,
        Confirmation::None,
        "Twitch logs.",
        false,
    ),
    spec(
        "cleanup plan logs",
        Role::Admin,
        Confirmation::None,
        "Plan log cleanup.",
        false,
    ),
    spec(
        "cleanup plan db",
        Role::Admin,
        Confirmation::None,
        "Plan DB cleanup.",
        false,
    ),
    spec(
        "cleanup plan spool",
        Role::Admin,
        Confirmation::None,
        "Plan spool cleanup.",
        false,
    ),
    spec(
        "cleanup plan all",
        Role::Admin,
        Confirmation::None,
        "Plan all cleanup.",
        false,
    ),
    spec(
        "cleanup apply",
        Role::Admin,
        Confirmation::Required,
        "Apply cleanup.",
        false,
    ),
    spec(
        "cleanup history",
        Role::Service,
        Confirmation::None,
        "Cleanup history.",
        false,
    ),
    spec(
        "cleanup rollback",
        Role::Admin,
        Confirmation::Required,
        "Rollback cleanup.",
        false,
    ),
];

const fn spec(
    name: &'static str,
    role: Role,
    confirmation: Confirmation,
    description: &'static str,
    implemented: bool,
) -> CommandSpec {
    CommandSpec {
        name,
        role,
        confirmation,
        description,
        implemented,
    }
}

pub fn command_names() -> Vec<&'static str> {
    COMMANDS.iter().map(|cmd| cmd.name).collect()
}

pub fn find_command(input: &str) -> Option<&'static CommandSpec> {
    let clean = input.trim();
    COMMANDS
        .iter()
        .filter(|cmd| clean == cmd.name || clean.starts_with(&format!("{} ", cmd.name)))
        .max_by_key(|cmd| cmd.name.len())
}

pub fn search_commands(query: &str) -> Vec<&'static CommandSpec> {
    let q = query.trim().to_ascii_lowercase();
    COMMANDS
        .iter()
        .filter(|cmd| cmd.name.contains(&q) || cmd.description.to_ascii_lowercase().contains(&q))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::find_command;

    #[test]
    fn longest_command_wins() {
        assert_eq!(
            find_command("user config edit jade cfg").unwrap().name,
            "user config edit"
        );
    }
}
