-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE = 27022002000

LOCATION_LISTING = {
    { "@Overworld/Forest of Time/Impa Gift/" },
    { "@Overworld/Forest of Time/Nayru's House/" },
    { "@Overworld/Lynna|South Shore|Palace/Tingle Present/" },
    { "@Overworld/Lynna|South Shore|Palace/Tingle Upgrade/" },

    { "@Overworld/Lynna|South Shore|Palace/Lynna City Chest/" },
    { "@Overworld/Lynna|South Shore|Palace/Shop/First Item" },
    { "@Overworld/Lynna|South Shore|Palace/Shop/Second Item" },
    { "@Overworld/Lynna|South Shore|Palace/Shop/Third Item" },
    { "@Overworld/Lynna|South Shore|Palace/Hidden Shop/First Item" },
    { "@Overworld/Lynna|South Shore|Palace/Hidden Shop/Second Item" },
    { "@Overworld/Lynna|South Shore|Palace/Hidden Shop/Third Item" },

    { "@Overworld/Lynna|South Shore|Palace/Mayor Plen's House/" },
    { "@Overworld/Lynna|South Shore|Palace/Vasu's Gift/" },
    { "@Overworld/Lynna|South Shore|Palace/Maku Tree Gift/" },
    { "@Overworld/Lynna|South Shore|Palace/Mamamu Yan Trade/" },
    { "@Overworld/Lynna|South Shore|Palace/Comedian Trade/" },
    { "@Overworld/Lynna|South Shore|Palace/Gasha Farmer/" },
    { "@Overworld/Lynna|South Shore|Palace/Advance Shop/First Item" },
    { "@Overworld/Lynna|South Shore|Palace/Advance Shop/Second Item" },
    { "@Overworld/Lynna|South Shore|Palace/Advance Shop/Third Item" },
    { "@Overworld/Lynna|South Shore|Palace/Lynna Village Shooting Gallery/" },
    { "@Overworld/Lynna|South Shore|Palace/Postman Trade/" },
    { "@Overworld/Lynna|South Shore|Palace/The Toilet Hand Trade/" },
    { "@Overworld/Lynna|South Shore|Palace/Sad Boi Trade/" },
    { "@Overworld/Lynna|South Shore|Palace/Black Tower Worker/" },
    { "@Overworld/Lynna|South Shore|Palace/Black Tower Heart Piece/" },
    { "@Overworld/Lynna|South Shore|Palace/Ambi's Palace/Ambi's Palace Chest" },
    { "@Overworld/Lynna|South Shore|Palace/Ambi's Palace/Rescue Nayru" },

    { "@Overworld/Fairies' Woods/Restoration Wall Heart Piece/" },

    { "@Overworld/Lynna|South Shore|Palace/Shore Dirt Spot/" },
    { "@Overworld/Lynna|South Shore|Palace/Rafton Trade/" },

    { "@Overworld/Yoll Graveyard/Cheval's Test/" },
    { "@Overworld/Yoll Graveyard/Cheval's Invention/" },
    { "@Overworld/Yoll Graveyard/Grave Under The Tree/" },
    { "@Overworld/Yoll Graveyard/Syrup's Shop/Syrup Shop #1" },
    { "@Overworld/Yoll Graveyard/Syrup's Shop/Syrup Shop #2" },
    { "@Overworld/Yoll Graveyard/Syrup's Shop/Syrup Shop #3" },
    { "@Overworld/Yoll Graveyard/Graveyard Poe Trade/" },
    { "@Overworld/Yoll Graveyard/Yoll Graveyard Heart Piece/" },

    { "@Overworld/Fairies' Woods/Fairies' Woods Chest/" },
    { "@Overworld/Fairies' Woods/Deku Forest Cave East/" },
    { "@Overworld/Fairies' Woods/Deku Forest Cave West/" },
    { "@Overworld/Fairies' Woods/Deku Forest Soldier/" },
    { "@Overworld/Fairies' Woods/Deku Forest Heart Piece/" },

    { "@Overworld/Crescent Island/Under Crescent Island/" },
    { "@Overworld/Crescent Island/Tokay Chef Trade/" },

    { "@Overworld/Crescent Island/Hidden Tokay Cave/" },
    { "@Overworld/Crescent Island/Tokay Crystal Cave/" },
    { "@Overworld/Crescent Island/Tokay Bomb Cave/" },
    { "@Overworld/Crescent Island/Tokay Chicken Hut/"},
    { "@Overworld/Crescent Island/Wild Tokay Game/" },
    { "@Overworld/Crescent Island/Tokay Market/Tokay Market #1" },
    { "@Overworld/Crescent Island/Tokay Market/Tokay Market #2" },
    { "@Overworld/Crescent Island/Tokay Pot Cave/" },

    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Nuun Highlands Cave/" },
    { "@Overworld/Fairies' Woods/Happy Mask Salesman Trade/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Symmetry City Main House/Symmetry City Brothers" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Symmetry City Main House/Middle Man Trade" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Bomb Fairy/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Talus Peaks Chest/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Symmetry City Heart Piece/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Tokkey's Composition/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Patch Tuni Nut Ceremony/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Patch Broken Sword Ceremony/" },

    { "@Overworld/Rolling Ridge West/Rolling Ridge Entrance/Ridge Chest West Base On Terrace" },
    { "@Overworld/Rolling Ridge East (Present)/Goron caves (Present)/First Goron Dance" },
    { "@Overworld/Rolling Ridge East (Present)/Pool in D6 Entrance/" },
    { "@Overworld/Rolling Ridge East (Present)/Goron caves (Present)/Trade Rock Brisket" },
    { "@Overworld/Rolling Ridge West/Goron Elder/" },
    { "@Overworld/Rolling Ridge East (Past)/Goron caves (Past)/Goron Dance, With Letter" },
    { "@Overworld/Rolling Ridge East (Past)/Goron caves (Past)/Trade Goron Vase" },
    { "@Overworld/Rolling Ridge East (Past)/East Ridge Base/Ridge Base Past Bomb" },
    { "@Overworld/Rolling Ridge East (Past)/East Ridge Base/Ridge Diamonds Past" },
    { "@Overworld/Rolling Ridge West/Rolling Ridge Entrance/Ridge West Surface Stair" },
    { "@Overworld/Rolling Ridge West/Moblin Keep/Under Moblin Keep" },
    { "@Overworld/Rolling Ridge West/Moblin Keep/Defeat Great Moblin" },
    { "@Overworld/Rolling Ridge West/Rolling Ridge Entrance/Goron's Hiding Place" },
    { "@Overworld/Rolling Ridge East (Past)/Goron caves (Past)/Ridge Bush Cave" },
    { "@Overworld/Rolling Ridge East (Present)/Target Carts Minigame/First reward" },
    { "@Overworld/Rolling Ridge East (Present)/Target Carts Minigame/Second reward" },
    { "@Overworld/Rolling Ridge East (Present)/Goron caves (Present)/Big Bang Game" },
    { "@Overworld/Rolling Ridge East (Present)/Goron caves (Present)/Ridge NE Cave Present" },
    { "@Overworld/Rolling Ridge East (Present)/Goron caves (Present)/Goron Diamond Cave" },
    { "@Overworld/Rolling Ridge West/Rolling Ridge Entrance/Ridge West Heart Piece" },
    { "@Overworld/Rolling Ridge East (Present)/Ridge Upper Heart Piece/" },
    { "@Overworld/Rolling Ridge East (Past)/Bomb Goron Head/" },
    { "@Overworld/Rolling Ridge East (Past)/Treasure Hunting Goron/" },
    { "@Overworld/Rolling Ridge East (Past)/Goron Shooting Gallery Price/100 points" },
    { "@Overworld/Rolling Ridge East (Past)/Goron caves (Past)/Trade Lava Juice" },
    { "@Overworld/Zora Village|Zora Seas/Zora Village Present Chest/" },
    { "@Overworld/Zora Village|Zora Seas/Zora Palace (Present)/Zora Palace Chest" },
    { "@Overworld/Zora Village|Zora Seas/Zora NW Cave/" },
    { "@Overworld/Zora Village|Zora Seas/Fairies' Coast Chest/" },
    { "@Overworld/Zora Village|Zora Seas/Zora Palace (Present)/Zora King Gift" },
    { "@Overworld/Zora Village|Zora Seas/Zora's Reward/" },
    { "@Overworld/Zora Village|Zora Seas/Library Present/" },
    { "@Overworld/Zora Village|Zora Seas/Library Past/" },
    { "@Overworld/Zora Village|Zora Seas/Zora Seas Chest/" },
    { "@Overworld/Zora Village|Zora Seas/Fisher's Island Cave/" },
    { "@Overworld/Sea of Storms|No Return/Piratian Captain/" },
    { "@Overworld/Sea of Storms|No Return/Sea of Storms Past/" },
    { "@Overworld/Sea of Storms|No Return/Sea of No Return/" },
    -- TRADE
    { "@Overworld/Rolling Ridge West/Old Zora Trade/" },
    { "@Overworld/Yoll Graveyard/Maple Trade/" },
    -- MAKU PATH
    { "@Dungeons/Maku Path (D0)/Heart Piece/" },
    { "@Dungeons/Maku Path (D0)/Key Chest/" },
    { "@Dungeons/Maku Path (D0)/Basement/" },
    -- SPIRITS GRAVE
    { "@Dungeons/Spirit's Grave (D1)/One-Button Chest/" },
    { "@Dungeons/Spirit's Grave (D1)/Two-Buttons Chest/" },
    { "@Dungeons/Spirit's Grave (D1)/Wide Room/" },
    { "@Dungeons/Spirit's Grave (D1)/Crystal Room/" },
    { "@Dungeons/Spirit's Grave (D1)/Crossroad/" },
    { "@Dungeons/Spirit's Grave (D1)/West Terrace/" },
    { "@Dungeons/Spirit's Grave (D1)/Pot Chest/" },
    { "@Dungeons/Spirit's Grave (D1)/East Terrace/" },
    { "@Dungeons/Spirit's Grave (D1)/Ghini Drop/" },
    { "@Dungeons/Spirit's Grave (D1)/Basement/" },
    { "@Dungeons/Spirit's Grave (D1)/Pumpkin Head/Boss" },
    -- WING DUNGEON
    { "@Dungeons/Wing Dungeon (D2)/(1F): Color Room/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Bombed Terrace/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Moblin Platform/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Rope Room/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Ladder Chest/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Moblin Drop/" },
    { "@Dungeons/Wing Dungeon (D2)/(1F): Statue Puzzle/" },
    { "@Dungeons/Wing Dungeon (D2)/(B1F): Thwomp Shelf/" },
    { "@Dungeons/Wing Dungeon (D2)/(B1F): Thwomp Tunnel/" },
    { "@Dungeons/Wing Dungeon (D2)/(B1F): Basement Chest/" },
    { "@Dungeons/Wing Dungeon (D2)/(B1F): Basement Drop/" },
    { "@Dungeons/Wing Dungeon (D2)/Head Thwomp/(1F): Boss" },
    --    MOONLIT GROTTO
    { "@Dungeons/Moonlit Grotto (D3)/(B1F): Bridge Chest/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Mimic Room/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Bush Beetle Room/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Crossroad/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Pols Voice Chest/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Armos Drop/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Statue Drop/" },
    { "@Dungeons/Moonlit Grotto (D3)/(1F): Six Blocs Drop/" },
    { "@Dungeons/Moonlit Grotto (D3)/(B1F): Moldorm Drop/" },
    { "@Dungeons/Moonlit Grotto (D3)/(B1F): East/" },
    { "@Dungeons/Moonlit Grotto (D3)/(B1F): Torch Chest/" },
    { "@Dungeons/Moonlit Grotto (D3)/(B1F): Conveyor Belt Room/" },
    { "@Dungeons/Moonlit Grotto (D3)/Shadow Hag/(B1F): Boss" },
    --     SKULL DUNGEON
    { "@Dungeons/Skull Dungeon (D4)/(1F): Second Crystal Switch/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): Lava Pot Chest/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): Small Floor Puzzle/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): First Chest/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): Minecart Chest/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): Cube Chest/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): First Crystal Switch/" },
    { "@Dungeons/Skull Dungeon (D4)/(1F): Color Tile Drop/" },
    { "@Dungeons/Skull Dungeon (D4)/(B1F): Large Floor Puzzle/" },
    { "@Dungeons/Skull Dungeon (D4)/Eyesoar/(B1F): Boss" },
    -- CROWN DNGEON
    { "@Dungeons/Crown Dungeon (D5)/(1F): Diamond Chest/" },
    { "@Dungeons/Crown Dungeon (D5)/(1F): Eyes Chest/" },
    { "@Dungeons/Crown Dungeon (D5)/(1F): Three-Statue Puzzle/" },
    { "@Dungeons/Crown Dungeon (D5)/(1F): Blue Peg Chest/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Like-Like Chest/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Red Peg Chest/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Owl Puzzle/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Two-Statue Puzzle/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Dark Room/" },
    { "@Dungeons/Crown Dungeon (D5)/(B1F): Six-Statue Puzzle/" },
    { "@Dungeons/Crown Dungeon (D5)/Smog/(1F): Boss" },
    -- MERMAIDS CAVE PRESENT
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Vire Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Spinner Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Rope Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/RNG Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Diamond Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Beamos Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Cube Chest/" },
    { "@Dungeons/Mermaid's Cave [Present] (D6)/Channel Chest/" },
    -- MERMAIDS CAVE PAST
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Stalfos Chest/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Color Room/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Pool Chest/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(1F): Wizzrobe/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Diamond Chest/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Spear Chest/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/(B1F): Rope Chest/" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/Octogon/(1F): Boss" },
    -- JABU-JABUS BELLY
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Island Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Stairway Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Miniboss Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Cane|Diamond Puzzle/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Boxed Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Flower Room/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Diamond Puzzle/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(1F): Crab Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Left Wing/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Right Wing/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(2F): Spike Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Hallway Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Post-Hallway Chest/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/(3F): Terrace/" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/Plasmarine/(2F): Boss" },
    -- ANCIENT TOMB
    { "@Dungeons/Ancient Tomb (D8)/(1F): Single Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): Maze Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): NW Slate Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): NE Slate Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): Ghini Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): SE Slate Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): SW Slate Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): NW Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): Sarcophagus Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): Blade Trap/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): Blue Peg Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): Floor Puzzle/" },
    { "@Dungeons/Ancient Tomb (D8)/(B2F): Tile Room/" },
    { "@Dungeons/Ancient Tomb (D8)/(B1F): Stalfos/" },
    { "@Dungeons/Ancient Tomb (D8)/(B3F): Single Chest/" },
    { "@Dungeons/Ancient Tomb (D8)/Ramrock/(B3F): Boss" },
    -- LINKED HERO'S CAVE
    { "@Dungeons/Hero's Cave/(1F): Pots Puzzle/" },
    { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #1/" },
    { "@Dungeons/Hero's Cave/(1F): Bridge Puzzle #1/" },
    { "@Dungeons/Hero's Cave/(1F): Shoot Eyes/" },
    { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #2/" },
    { "@Dungeons/Hero's Cave/(1F): Pots Puzzle #2/" },
    { "@Dungeons/Hero's Cave/(1F): Statue Puzzle #3/" },
    { "@Dungeons/Hero's Cave/(1F): Bridge Puzzle #2/" },
    { "@Dungeons/Hero's Cave/(1F): Color Room/" },
    { "@Dungeons/Hero's Cave/(1F): Water Puzzle/" },
    { "@Dungeons/Hero's Cave/(B1F): Water Puzzle/" },
    { "@Dungeons/Hero's Cave/(B1F): Basement/" },
    { "@Dungeons/Hero's Cave/(1F): Final Puzzle/" },
    { "@Dungeons/Hero's Cave/(1F): Completion Reward/"},
    -- ESSENCES
    { "@Dungeons/Spirit's Grave (D1)/Eternal Spirit/Essence" },
    { "@Dungeons/Wing Dungeon (D2)/Ancient Wood/Essence" },
    { "@Dungeons/Moonlit Grotto (D3)/Echoing Howl/Essence" },
    { "@Dungeons/Skull Dungeon (D4)/Burning Flame/Essence" },
    { "@Dungeons/Crown Dungeon (D5)/Sacred Soil/Essence" },
    { "@Dungeons/Mermaid's Cave [Past] (D6)/Lonely Peak/Essence" },
    { "@Dungeons/Jabu-Jabu's Belly (D7)/Rolling Sea/Essence" },
    { "@Dungeons/Ancient Tomb (D8)/Falling Star/Essence" },
    -- SEED TREES
    { "@Overworld/Lynna|South Shore|Palace/Lynna City Seed Tree/" },
    { "@Overworld/Lynna|South Shore|Palace/Ambi's Palace: Seed Tree/" },
    { "@Overworld/Fairies' Woods/Deku Forest Seed Tree/" },
    { "@Overworld/Crescent Island/Crescent Island Seed Tree/" },
    { "@Overworld/Nuun Highlands|Symmetry City|Talus Peaks/Symmetry City: Seed Tree/" },
    { "@Overworld/Rolling Ridge West/Rolling Ridge West: Seed Tree/" },
    { "@Overworld/Rolling Ridge East (Past)/Rolling Ridge East: Seed Tree/" },
    { "@Overworld/Zora Village|Zora Seas/Zora Village: Seed Tree/" }
}

function BuildLocationMapping()
    local location_mapping = {}
    local currentIndex = BASE
    for _, location in ipairs(LOCATION_LISTING) do
        if type(location) == "number" then
            currentIndex = currentIndex + location
        else
            location_mapping[currentIndex] = location
            currentIndex = currentIndex + 1
        end
    end

    return location_mapping
end

LOCATION_MAPPING = BuildLocationMapping()
