from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/BTL_ArtsList.html
# flake8: noqa
arts_data: list[Data] = [
Data("ARTS_ASSAULT_AUTO_Na_1", valid=False),
Data("Decoy Round"),
Data("Furious Blast"),
Data("Burst Grenade"),
Data("Flash Grenade"),
Data("Assault Breaker"),
Data("Medic Free"),
Data("Takedown Shot"),
Data("Power Dive"),
Data("Last Stand"),
Data("Gunforce"),
Data("Flame Grenade"),
Data("Assault Hammer"),
Data("Infuriate"),
Data("ARTS_ASSAULT_ARTS_14", valid=False),
Data("ARTS_SNIPER_AUTO_Nam", valid=False),
Data("First Down"),
Data("Shrapnel"),
Data("Eagle Eye"),
Data("Sidewinder"),
Data("Intercept"),
Data("Hawkeye"),
Data("Ghost Sniper"),
Data("ARTS_DOUBLEHAND_AUTO", valid=False),
Data("Sliding Slinger"),
Data("Early Bird"),
Data("Violent Streak"),
Data("Primer"),
Data("Executioner"),
Data("Combat Limbo"),
Data("Ghostwalker"),
Data("ARTS_GATLING_AUTO_Na", valid=False),
Data("Bullet Storm"),
Data("Hellfire"),
Data("Thermal Payload"),
Data("Missile Volley"),
Data("Enhanced Stand"),
Data("Cool Off"),
Data("ARTS_BEAMCANNON_AUTO", valid=False),
Data("Beam Barrage"),
Data("Subterfuge"),
Data("Myopic Screen"),
Data("Ether Blast"),
Data("Gravity Blast"),
Data("Gravity Cloak"),
Data("Pathogen Blast"),
Data("ARTS_PSYCHO_AUTO_Nam", valid=False),
Data("Jetstream"),
Data("Stellar Ray"),
Data("Lightning Cloak"),
Data("Starlight Kick"),
Data("Astral Protection"),
Data("Shooting Star"),
Data("ARTS_SWORD_AUTO_Name", valid=False),
Data("Rising Blade"),
Data("Defensive Stance"),
Data("Offensive Stance"),
Data("Magnum Edge"),
Data("Tornado Blade"),
Data("Burning Slash"),
Data("Incendiary Edge"),
Data("Samurai Soul"),
Data("ARTS_JAVELIN_AUTO_Na", valid=False),
Data("Arcing Horn"),
Data("Hair Trigger"),
Data("Spiral Horn"),
Data("Overwhelm"),
Data("Speed Demon"),
Data("Raijin"),
Data("Trident Buster"),
Data("ARTS_DOUBLEBLADE_AUT", valid=False),
Data("Back Slash"),
Data("Killing Machine"),
Data("Side Slash"),
Data("Stream Edge"),
Data("Shadowrunner"),
Data("Thirsty Edge"),
Data("Blood Sacrifice"),
Data("Upper Hand"),
Data("Hundred Shells"),
Data("Electric Surge"),
Data("ARTS_HUGESHIELD_AUTO", valid=False),
Data("Wild Down"),
Data("Flame Cloak"),
Data("Trash Talk"),
Data("Iron Prison"),
Data("Supershield"),
Data("Wild Smash"),
Data("Reality Rift"),
Data("Bombardier"),
Data("Shield Wall"),
Data("ARTS_KNIFE_AUTO_Name", valid=False),
Data("Screamer"),
Data("Absorber Skin"),
Data("Servant Sacrifice"),
Data("Full Specs"),
Data("Repair"),
Data("Energy Source"),
Data("Brainjack"),
Data("Dispel"),
Data("Black Butterfly"),
Data("Recuperate"),
Data("Chrome Armor"),
Data("Slit Edge"),
Data("ARTS_KNIFE_ARTS_13_N", valid=False),
Data("ARTS_BEAMSABER_AUTO_", valid=False),
Data("Geolibrium"),
Data("Astrolibrium"),
Data("Starfall Blade"),
Data("Starfall Rondo"),
Data("Astral Purge"),
Data("Astral Horizon"),
Data("Galactic Cataclysm"),
Data("Astral Heal"),
Data("Novalibrium"),
Data("Starfall Blossom"),
Data("ARTS_ASSAULT_AUTO_Na_2", valid=False),
Data("Boost Barrel"),
Data("Sniper Barrel"),
Data("Missile Barrel"),
Data("Cannon Barrel"),
Data("Quick Cannon"),
Data("Grenade Blitz"),
Data("Overclock"),
Data("Afterburner"),
Data("Slayonet"),
Data("Ghost Factory"),
Data("Zero Zero"),
Data("Sky High"),
Data("Fire Carnival"),
Data("Bullet Twister"),
Data("Titan Recharge"),
Data("Master Gunner"),
Data("Clarity Ray"),
Data("Beam Bomber"),
Data("Dual Dynamo"),
Data("Gravity Lunge"),
Data("Tacit Censure"),
Data("Ultraslash"),
Data("Blossom Dance"),
Data("True Stream Edge"),
Data("Balance Breaker"),
Data("Vortex"),
Data("Maximum Voltage"),
Data("Shadowstrike"),
Data("Crisis Zone"),
Data("Seventh Edge"),
Data("Drum Roll"),
Data("Mindstorm"),
Data("Atomic Hit"),
Data("Flamehand"),
Data("Smooth Recovery"),
Data("Black Bane"),
Data("Secondary Speed"),
Data("Starlight Duster"),
Data("Essence Exchange"),
Data("Phenomenon"),
]
