from typing import List
from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_BeaconList.html
# flake8: noqa
dataprobes_data: List[Data] = [
Data("Basic Probe", valid=False),
Data("Mining Probe G1", count=20),
Data("Mining Probe G2", count=24),
Data("Mining Probe G3", count=7),
Data("Mining Probe G4", count=15),
Data("Mining Probe G5", count=9),
Data("Mining Probe G6", count=9),
Data("Mining Probe G7", count=4),
Data("Mining Probe G8", count=23),
Data("Mining Probe G9", count=10),
Data("Mining Probe G10", count=4),
Data("ITM_BCN_MINE_011_name", valid=False),
Data("ITM_BCN_MINE_012_name", valid=False),
Data("Research Probe G1", count=3),
Data("Research Probe G2", count=4),
Data("Research Probe G3", count=2),
Data("Research Probe G4", count=6),
Data("Research Probe G5", count=7),
Data("Research Probe G6", count=3),
Data("ITM_BCN_TOUR_007_name", valid=False),
Data("ITM_BCN_TOUR_008_name", valid=False),
Data("Booster Probe G1", count=3),
Data("Booster Probe G2", count=3),
Data("ITM_BCN_RAISE_003_name", valid=False),
Data("ITM_BCN_RAISE_004_name", valid=False),
Data("Storage Probe", count=11),
Data("ITM_BCN_STORAGE_002_name", valid=False),
Data("ITM_BCN_STORAGE_003_name", valid=False),
Data("Duplicator Probe", count=4),
Data("Fuel Recovery Probe", count=3),
Data("Melee Attack Probe", count=3),
Data("Ranged Attack Probe", count=3),
Data("EZ Debuff Probe", count=3),
Data("Attribute Resistance Probe", count=3),
Data("ITM_BCN_BTL_006_name", valid=False),
Data("ITM_BCN_BTL_007_name", valid=False),
Data("ITM_BCN_BTL_008_name", valid=False),
Data("ITM_BCN_BTL_009_name", valid=False),
Data("ITM_BCN_BTL_010_name", valid=False),
]