from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/WPN_PcList.html
# flake8: noqa
ground_weapons_data: list[Data] = [
Data("Combat Assault Rifle"), 
Data("Combat Sniper Rifle"),
Data("Combat Dual Guns"),
Data("Combat Gatling Gun"),
Data("Combat Raygun"),
Data("Combat Psycho Launchers"),
Data("Combat Longsword"),
Data("Combat Javelin"),
Data("Combat Dual Swords"),
Data("Combat Shield"),
Data("Combat Knife"),
Data("Combat Photon Saber"),
Data("Busted Rifle"),
Data("Busted Knife"),
Data("Ramjet Rifle_1"),
Data("Ramjet Rifle_2"),
Data("Sparkjet Rifle"),
Data("Adelbert"),
Data("Grette"),
Data("Unbreakable Sword"),
Data("Hundred Devil Sword"),
Data("Scrap Duo"),
Data("Diagonal Twins"),
Data("Hyde Dyads"),
Data("Savage Ziyse"),
Data("Iron Sword_1"),
Data("Iron Sword_2"),
Data("Iron Sword_3"),
Data("Titanium Sword_1"),
Data("Titanium Sword_2"),
Data("Titanium Sword_3"),
Data("Chrome Sword_1"),
Data("Chrome Sword_2"),
Data("Chrome Sword_3"),
Data("Cobalt Sword_1"),
Data("Cobalt Sword_2"),
Data("Cobalt Sword_3"),
Data("Chromoly Sword_1"),
Data("Chromoly Sword_2"),
Data("Chromoly Sword_3"),
Data("Cermet Sword_1"),
Data("Cermet Sword_2"),
Data("Cermet Sword_3"),
Data("Carbide Sword_1"),
Data("Carbide Sword_2"),
Data("Carbide Sword_3"),
Data("Iron Sword II_1"),
Data("Iron Sword II_2"),
Data("Iron Sword II_3"),
Data("Titanium Sword II_1"),
Data("Titanium Sword II_2"),
Data("Titanium Sword II_3"),
Data("Chrome Sword II_1"),
Data("Chrome Sword II_2"),
Data("Chrome Sword II_3"),
Data("Cobalt Sword II_1"),
Data("Cobalt Sword II_2"),
Data("Cobalt Sword II_3"),
Data("Chromoly Sword II_1"),
Data("Chromoly Sword II_2"),
Data("Chromoly Sword II_3"),
Data("Cermet Sword II_1"),
Data("Cermet Sword II_2"),
Data("Cermet Sword II_3"),
Data("Carbide Sword II_1"),
Data("Carbide Sword II_2"),
Data("Carbide Sword II_3"),
Data("Iron Slair_1"),
Data("Iron Slair_2"),
Data("Iron Slair_3"),
Data("Titanium Slair_1"),
Data("Titanium Slair_2"),
Data("Titanium Slair_3"),
Data("Chrome Slair_1"),
Data("Chrome Slair_2"),
Data("Chrome Slair_3"),
Data("Cobalt Slair_1"),
Data("Cobalt Slair_2"),
Data("Cobalt Slair_3"),
Data("Chromoly Slair_1"),
Data("Chromoly Slair_2"),
Data("Chromoly Slair_3"),
Data("Cermet Slair_1"),
Data("Cermet Slair_2"),
Data("Cermet Slair_3"),
Data("Carbide Slair_1"),
Data("Carbide Slair_2"),
Data("Carbide Slair_3"),
Data("Iron Slair II_1"),
Data("Iron Slair II_2"),
Data("Iron Slair II_3"),
Data("Titanium Slair II_1"),
Data("Titanium Slair II_2"),
Data("Titanium Slair II_3"),
Data("Chrome Slair II_1"),
Data("Chrome Slair II_2"),
Data("Chrome Slair II_3"),
Data("Cobalt Slair II_1"),
Data("Cobalt Slair II_2"),
Data("Cobalt Slair II_3"),
Data("Chromoly Slair II_1"),
Data("Chromoly Slair II_2"),
Data("Chromoly Slair II_3"),
Data("Cermet Slair II_1"),
Data("Cermet Slair II_2"),
Data("Cermet Slair II_3"),
Data("Carbide Slair II_1"),
Data("Carbide Slair II_2"),
Data("Carbide Slair II_3"),
Data("Iron Spatha_1"),
Data("Iron Spatha_2"),
Data("Iron Spatha_3"),
Data("Titanium Spatha_1"),
Data("Titanium Spatha_2"),
Data("Titanium Spatha_3"),
Data("Chrome Spatha_1"),
Data("Chrome Spatha_2"),
Data("Chrome Spatha_3"),
Data("Cobalt Spatha_1"),
Data("Cobalt Spatha_2"),
Data("Cobalt Spatha_3"),
Data("Chromoly Spatha_1"),
Data("Chromoly Spatha_2"),
Data("Chromoly Spatha_3"),
Data("Cermet Spatha_1"),
Data("Cermet Spatha_2"),
Data("Cermet Spatha_3"),
Data("Carbide Spatha_1"),
Data("Carbide Spatha_2"),
Data("Carbide Spatha_3"),
Data("Iron Pride_1"),
Data("Iron Pride_2"),
Data("Iron Pride_3"),
Data("Titanium Pride_1"),
Data("Titanium Pride_2"),
Data("Titanium Pride_3"),
Data("Chrome Pride_1"),
Data("Chrome Pride_2"),
Data("Chrome Pride_3"),
Data("Cobalt Pride_1"),
Data("Cobalt Pride_2"),
Data("Cobalt Pride_3"),
Data("Chromoly Pride_1"),
Data("Chromoly Pride_2"),
Data("Chromoly Pride_3"),
Data("Cermet Pride_1"),
Data("Cermet Pride_2"),
Data("Cermet Pride_3"),
Data("Carbide Pride_1"),
Data("Carbide Pride_2"),
Data("Carbide Pride_3"),
Data("IW_MU_F_SWORD_A06_0101_name_1", valid=False),
Data("IW_MU_F_SWORD_A06_0101_name_2", valid=False),
Data("IW_MU_F_SWORD_A06_0101_name_3", valid=False),
Data("IW_MU_F_SWORD_A05_1001_name_1", valid=False),
Data("IW_MU_F_SWORD_A05_1001_name_2", valid=False),
Data("IW_MU_F_SWORD_A05_1001_name_3", valid=False),
Data("Faithful Glaive_1"),
Data("Faithful Glaive_2"),
Data("Faithful Glaive_3"),
Data("Steelbreaker Glaive_1"),
Data("Steelbreaker Glaive_2"),
Data("Steelbreaker Glaive_3"),
Data("Pulverizing Glaive_1"),
Data("Pulverizing Glaive_2"),
Data("Pulverizing Glaive_3"),
Data("Intrepid Glaive_1"),
Data("Intrepid Glaive_2"),
Data("Intrepid Glaive_3"),
Data("Audacious Glaive_1"),
Data("Audacious Glaive_2"),
Data("Audacious Glaive_3"),
Data("IW_MU_F_SWORD_B04_0101_name_1", valid=False),
Data("IW_MU_F_SWORD_B04_0101_name_2", valid=False),
Data("IW_MU_F_SWORD_B04_0101_name_3", valid=False),
Data("IW_MU_F_SWORD_B05_1001_name_1", valid=False),
Data("IW_MU_F_SWORD_B05_1001_name_2", valid=False),
Data("IW_MU_F_SWORD_B05_1001_name_3", valid=False),
Data("Faithful Glaive II_1"),
Data("Faithful Glaive II_2"),
Data("Faithful Glaive II_3"),
Data("Steelbreaker Glaive II_1"),
Data("Steelbreaker Glaive II_2"),
Data("Steelbreaker Glaive II_3"),
Data("Pulverizing Glaive II_1"),
Data("Pulverizing Glaive II_2"),
Data("Pulverizing Glaive II_3"),
Data("Intrepid Glaive II_1"),
Data("Intrepid Glaive II_2"),
Data("Intrepid Glaive II_3"),
Data("Audacious Glaive II_1"),
Data("Audacious Glaive II_2"),
Data("Audacious Glaive II_3"),
Data("Advanced Iron Sword"),
Data("Worn Titanium Sword"),
Data("Advanced Titanium Sword"),
Data("Worn Chrome Sword"),
Data("Advanced Chrome Sword"),
Data("Worn Cobalt Sword"),
Data("Advanced Cobalt Sword"),
Data("Worn Chromoly Sword"),
Data("Advanced Chromoly Sword"),
Data("Worn Cermet Sword"),
Data("Advanced Cermet Sword"),
Data("Worn Carbide Sword"),
Data("Advanced Iron Sword II"),
Data("Worn Titanium Sword II"),
Data("Advanced Titanium Sword II"),
Data("Worn Chrome Sword II"),
Data("Advanced Chrome Sword II"),
Data("Worn Cobalt Sword II"),
Data("Advanced Cobalt Sword II"),
Data("Worn Chromoly Sword II"),
Data("Advanced Chromoly Sword II"),
Data("Worn Cermet Sword II"),
Data("Advanced Cermet Sword II"),
Data("Worn Carbide Sword II"),
Data("Advanced Iron Slair"),
Data("Worn Titanium Slair"),
Data("Advanced Titanium Slair"),
Data("Worn Chrome Slair"),
Data("Advanced Chrome Slair"),
Data("Worn Cobalt Slair"),
Data("Advanced Cobalt Slair"),
Data("Worn Chromoly Slair"),
Data("Advanced Chromoly Slair"),
Data("Worn Cermet Slair"),
Data("Advanced Cermet Slair"),
Data("Worn Carbide Slair"),
Data("Advanced Iron Slair II"),
Data("Worn Titanium Slair II"),
Data("Advanced Titanium Slair II"),
Data("Worn Chrome Slair II"),
Data("Advanced Chrome Slair II"),
Data("Worn Cobalt Slair II"),
Data("Advanced Cobalt Slair II"),
Data("Worn Chromoly Slair II"),
Data("Advanced Chromoly Slair II"),
Data("Worn Cermet Slair II"),
Data("Advanced Cermet Slair II"),
Data("Worn Carbide Slair II"),
Data("Worn Chrome Spatha"),
Data("Advanced Chrome Spatha"),
Data("Worn Cobalt Spatha"),
Data("Advanced Cobalt Spatha"),
Data("Worn Chromoly Spatha"),
Data("Advanced Chromoly Spatha"),
Data("Worn Cermet Spatha"),
Data("Advanced Cermet Spatha"),
Data("Worn Carbide Spatha"),
Data("Advanced Chrome Pride"),
Data("Worn Cobalt Pride"),
Data("Advanced Cobalt Pride"),
Data("Worn Chromoly Pride"),
Data("Advanced Chromoly Pride"),
Data("Worn Cermet Pride"),
Data("Advanced Cermet Pride"),
Data("Worn Carbide Pride"),
Data("Advanced Steelbreaker Glaive"),
Data("Worn Pulverizing Glaive"),
Data("Advanced Pulverizing Glaive"),
Data("Worn Intrepid Glaive"),
Data("Advanced Intrepid Glaive"),
Data("Worn Audacious Glaive"),
Data("Advanced Steelbreaker Glaive II"),
Data("Worn Pulverizing Glaive II"),
Data("Advanced Pulverizing Glaive II"),
Data("Worn Intrepid Glaive II"),
Data("Advanced Intrepid Glaive II"),
Data("Worn Audacious Glaive II"),
Data("Ultra Ceramic Sword"),
Data("Ultra Diamond Sword"),
Data("Ultra Ceramic Sword II"),
Data("Ultra Diamond Sword II"),
Data("Ultra Ceramic Slair"),
Data("Ultra Diamond Slair"),
Data("Ultra Ceramic Slair II"),
Data("Ultra Diamond Slair II"),
Data("Ultra Ceramic Spatha"),
Data("Ultra Diamond Spatha"),
Data("Ultra Ceramic Pride"),
Data("Ultra Diamond Pride"),
Data("Ultra Godbreaker Glaive"),
Data("Ultra Phenomenon Glaive"),
Data("Ultra Godbreaker Glaive II"),
Data("Ultra Phenomenon Glaive II"),
Data("Iron Blades_1"),
Data("Iron Blades_2"),
Data("Iron Blades_3"),
Data("Titanium Blades_1"),
Data("Titanium Blades_2"),
Data("Titanium Blades_3"),
Data("Chrome Blades_1"),
Data("Chrome Blades_2"),
Data("Chrome Blades_3"),
Data("Cobalt Blades_1"),
Data("Cobalt Blades_2"),
Data("Cobalt Blades_3"),
Data("Chromoly Blades_1"),
Data("Chromoly Blades_2"),
Data("Chromoly Blades_3"),
Data("Cermet Blades_1"),
Data("Cermet Blades_2"),
Data("Cermet Blades_3"),
Data("Carbide Blades_1"),
Data("Carbide Blades_2"),
Data("Carbide Blades_3"),
Data("Iron Blades II_1"),
Data("Iron Blades II_2"),
Data("Iron Blades II_3"),
Data("Titanium Blades II_1"),
Data("Titanium Blades II_2"),
Data("Titanium Blades II_3"),
Data("Chrome Blades II_1"),
Data("Chrome Blades II_2"),
Data("Chrome Blades II_3"),
Data("Cobalt Blades II_1"),
Data("Cobalt Blades II_2"),
Data("Cobalt Blades II_3"),
Data("Chromoly Blades II_1"),
Data("Chromoly Blades II_2"),
Data("Chromoly Blades II_3"),
Data("Cermet Blades II_1"),
Data("Cermet Blades II_2"),
Data("Cermet Blades II_3"),
Data("Carbide Blades II_1"),
Data("Carbide Blades II_2"),
Data("Carbide Blades II_3"),
Data("Iron Ralzes_1"),
Data("Iron Ralzes_2"),
Data("Iron Ralzes_3"),
Data("Titanium Ralzes_1"),
Data("Titanium Ralzes_2"),
Data("Titanium Ralzes_3"),
Data("Chrome Ralzes_1"),
Data("Chrome Ralzes_2"),
Data("Chrome Ralzes_3"),
Data("Cobalt Ralzes_1"),
Data("Cobalt Ralzes_2"),
Data("Cobalt Ralzes_3"),
Data("Chromoly Ralzes_1"),
Data("Chromoly Ralzes_2"),
Data("Chromoly Ralzes_3"),
Data("Cermet Ralzes_1"),
Data("Cermet Ralzes_2"),
Data("Cermet Ralzes_3"),
Data("Carbide Ralzes_1"),
Data("Carbide Ralzes_2"),
Data("Carbide Ralzes_3"),
Data("Iron Gladiis_1"),
Data("Iron Gladiis_2"),
Data("Iron Gladiis_3"),
Data("Titanium Gladiis_1"),
Data("Titanium Gladiis_2"),
Data("Titanium Gladiis_3"),
Data("Chrome Gladiis_1"),
Data("Chrome Gladiis_2"),
Data("Chrome Gladiis_3"),
Data("Cobalt Gladiis_1"),
Data("Cobalt Gladiis_2"),
Data("Cobalt Gladiis_3"),
Data("Chromoly Gladiis_1"),
Data("Chromoly Gladiis_2"),
Data("Chromoly Gladiis_3"),
Data("Cermet Gladiis_1"),
Data("Cermet Gladiis_2"),
Data("Cermet Gladiis_3"),
Data("Carbide Gladiis_1"),
Data("Carbide Gladiis_2"),
Data("Carbide Gladiis_3"),
Data("Iron Twins_1"),
Data("Iron Twins_2"),
Data("Iron Twins_3"),
Data("Titanium Twins_1"),
Data("Titanium Twins_2"),
Data("Titanium Twins_3"),
Data("Chrome Twins_1"),
Data("Chrome Twins_2"),
Data("Chrome Twins_3"),
Data("Cobalt Twins_1"),
Data("Cobalt Twins_2"),
Data("Cobalt Twins_3"),
Data("Chromoly Twins_1"),
Data("Chromoly Twins_2"),
Data("Chromoly Twins_3"),
Data("Cermet Twins_1"),
Data("Cermet Twins_2"),
Data("Cermet Twins_3"),
Data("Carbide Twins_1"),
Data("Carbide Twins_2"),
Data("Carbide Twins_3"),
Data("Iron Watxes_1"),
Data("Iron Watxes_2"),
Data("Iron Watxes_3"),
Data("Titanium Watxes_1"),
Data("Titanium Watxes_2"),
Data("Titanium Watxes_3"),
Data("Chrome Watxes_1"),
Data("Chrome Watxes_2"),
Data("Chrome Watxes_3"),
Data("Cobalt Watxes_1"),
Data("Cobalt Watxes_2"),
Data("Cobalt Watxes_3"),
Data("Chromoly Watxes_1"),
Data("Chromoly Watxes_2"),
Data("Chromoly Watxes_3"),
Data("Cermet Watxes_1"),
Data("Cermet Watxes_2"),
Data("Cermet Watxes_3"),
Data("Carbide Watxes_1"),
Data("Carbide Watxes_2"),
Data("Carbide Watxes_3"),
Data("IW_MU_F_DUALBLADE_A04_0101_name_1", valid=False),
Data("IW_MU_F_DUALBLADE_A04_0101_name_2", valid=False),
Data("IW_MU_F_DUALBLADE_A04_0101_name_3", valid=False),
Data("IW_MU_F_DUALBLADE_A05_1001_name_1", valid=False),
Data("IW_MU_F_DUALBLADE_A05_1001_name_2", valid=False),
Data("IW_MU_F_DUALBLADE_A05_1001_name_3", valid=False),
Data("Faithful Edges II_1"),
Data("Faithful Edges II_2"),
Data("Faithful Edges II_3"),
Data("Steelbreaker Edges II_1"),
Data("Steelbreaker Edges II_2"),
Data("Steelbreaker Edges II_3"),
Data("Pulverizing Edges II_1"),
Data("Pulverizing Edges II_2"),
Data("Pulverizing Edges II_3"),
Data("Intrepid Edges II_1"),
Data("Intrepid Edges II_2"),
Data("Intrepid Edges II_3"),
Data("Audacious Edges II_1"),
Data("Audacious Edges II_2"),
Data("Audacious Edges II_3"),
Data("IW_MU_F_DUALBLADE_B04_0101_name_1", valid=False),
Data("IW_MU_F_DUALBLADE_B04_0101_name_2", valid=False),
Data("IW_MU_F_DUALBLADE_B04_0101_name_3", valid=False),
Data("IW_MU_F_DUALBLADE_B05_1001_name_1", valid=False),
Data("IW_MU_F_DUALBLADE_B05_1001_name_2", valid=False),
Data("IW_MU_F_DUALBLADE_B05_1001_name_3", valid=False),
Data("Faithful Edges_1"),
Data("Faithful Edges_2"),
Data("Faithful Edges_3"),
Data("Steelbreaker Edges_1"),
Data("Steelbreaker Edges_2"),
Data("Steelbreaker Edges_3"),
Data("Pulverizing Edges_1"),
Data("Pulverizing Edges_2"),
Data("Pulverizing Edges_3"),
Data("Intrepid Edges_1"),
Data("Intrepid Edges_2"),
Data("Intrepid Edges_3"),
Data("Audacious Edges_1"),
Data("Audacious Edges_2"),
Data("Audacious Edges_3"),
Data("Advanced Iron Blades"),
Data("Worn Titanium Blades"),
Data("Advanced Titanium Blades"),
Data("Worn Chrome Blades"),
Data("Advanced Chrome Blades"),
Data("Worn Cobalt Blades"),
Data("Advanced Cobalt Blades"),
Data("Worn Chromoly Blades"),
Data("Advanced Chromoly Blades"),
Data("Worn Cermet Blades"),
Data("Advanced Cermet Blades"),
Data("Worn Carbide Blades"),
Data("Advanced Iron Blades II"),
Data("Worn Titanium Blades II"),
Data("Advanced Titanium Blades II"),
Data("Worn Chrome Blades II"),
Data("Advanced Chrome Blades II"),
Data("Worn Cobalt Blades II"),
Data("Advanced Cobalt Blades II"),
Data("Worn Chromoly Blades II"),
Data("Advanced Chromoly Blades II"),
Data("Worn Cermet Blades II"),
Data("Advanced Cermet Blades II"),
Data("Worn Carbide Blades II"),
Data("Advanced Iron Ralzes"),
Data("Worn Titanium Ralzes"),
Data("Advanced Titanium Ralzes"),
Data("Worn Chrome Ralzes"),
Data("Advanced Chrome Ralzes"),
Data("Worn Cobalt Ralzes"),
Data("Advanced Cobalt Ralzes"),
Data("Worn Chromoly Ralzes"),
Data("Advanced Chromoly Ralzes"),
Data("Worn Cermet Ralzes"),
Data("Advanced Cermet Ralzes"),
Data("Worn Carbide Ralzes"),
Data("Worn Chrome Gladiis"),
Data("Advanced Chrome Gladiis"),
Data("Worn Cobalt Gladiis"),
Data("Advanced Cobalt Gladiis"),
Data("Worn Chromoly Gladiis"),
Data("Advanced Chromoly Gladiis"),
Data("Worn Cermet Gladiis"),
Data("Advanced Cermet Gladiis"),
Data("Worn Carbide Gladiis"),
Data("Advanced Chrome Twins"),
Data("Worn Cobalt Twins"),
Data("Advanced Cobalt Twins"),
Data("Worn Chromoly Twins"),
Data("Advanced Chromoly Twins"),
Data("Worn Cermet Twins"),
Data("Advanced Cermet Twins"),
Data("Worn Carbide Twins"),
Data("Worn Cobalt Watxes"),
Data("Advanced Cobalt Watxes"),
Data("Worn Chromoly Watxes"),
Data("Advanced Chromoly Watxes"),
Data("Worn Cermet Watxes"),
Data("Advanced Cermet Watxes"),
Data("Worn Carbide Watxes"),
Data("Advanced Steelbreaker Edges II"),
Data("Worn Pulverizing Edges II"),
Data("Advanced Pulverizing Edges II"),
Data("Worn Intrepid Edges II"),
Data("Advanced Intrepid Edges II"),
Data("Worn Audacious Edges II"),
Data("Advanced Steelbreaker Edges"),
Data("Worn Pulverizing Edges"),
Data("Advanced Pulverizing Edges"),
Data("Worn Intrepid Edges"),
Data("Advanced Intrepid Edges"),
Data("Worn Audacious Edges"),
Data("Ultra Ceramic Blades"),
Data("Ultra Diamond Blades"),
Data("Ultra Ceramic Blades II"),
Data("Ultra Diamond Blades II"),
Data("Ultra Ceramic Ralzes"),
Data("Ultra Diamond Ralzes"),
Data("Ultra Ceramic Gladiis"),
Data("Ultra Diamond Gladiis"),
Data("Ultra Ceramic Twins"),
Data("Ultra Diamond Twins"),
Data("Ultra Ceramic Watxes"),
Data("Ultra Diamond Watxes"),
Data("Ultra Godbreaker Edges II"),
Data("Ultra Phenomenon Edges II"),
Data("Ultra Godbreaker Edges"),
Data("Ultra Phenomenon Edges"),
Data("Proto Knife"),
Data("Iron Knife_1"),
Data("Iron Knife_2"),
Data("Iron Knife_3"),
Data("Titanium Knife_1"),
Data("Titanium Knife_2"),
Data("Titanium Knife_3"),
Data("Chrome Knife_1"),
Data("Chrome Knife_2"),
Data("Chrome Knife_3"),
Data("Cobalt Knife_1"),
Data("Cobalt Knife_2"),
Data("Cobalt Knife_3"),
Data("Chromoly Knife_1"),
Data("Chromoly Knife_2"),
Data("Chromoly Knife_3"),
Data("Cermet Knife_1"),
Data("Cermet Knife_2"),
Data("Cermet Knife_3"),
Data("Carbide Knife_1"),
Data("Carbide Knife_2"),
Data("Carbide Knife_3"),
Data("Iron Knife III_1"),
Data("Iron Knife III_2"),
Data("Iron Knife III_3"),
Data("Titanium Knife III_1"),
Data("Titanium Knife III_2"),
Data("Titanium Knife III_3"),
Data("Chrome Knife III_1"),
Data("Chrome Knife III_2"),
Data("Chrome Knife III_3"),
Data("Cobalt Knife III_1"),
Data("Cobalt Knife III_2"),
Data("Cobalt Knife III_3"),
Data("Chromoly Knife III_1"),
Data("Chromoly Knife III_2"),
Data("Chromoly Knife III_3"),
Data("Cermet Knife III_1"),
Data("Cermet Knife III_2"),
Data("Cermet Knife III_3"),
Data("Carbide Knife III_1"),
Data("Carbide Knife III_2"),
Data("Carbide Knife III_3"),
Data("Iron Knife II_1"),
Data("Iron Knife II_2"),
Data("Iron Knife II_3"),
Data("Titanium Knife II_1"),
Data("Titanium Knife II_2"),
Data("Titanium Knife II_3"),
Data("Chrome Knife II_1"),
Data("Chrome Knife II_2"),
Data("Chrome Knife II_3"),
Data("Cobalt Knife II_1"),
Data("Cobalt Knife II_2"),
Data("Cobalt Knife II_3"),
Data("Chromoly Knife II_1"),
Data("Chromoly Knife II_2"),
Data("Chromoly Knife II_3"),
Data("Cermet Knife II_1"),
Data("Cermet Knife II_2"),
Data("Cermet Knife II_3"),
Data("Carbide Knife II_1"),
Data("Carbide Knife II_2"),
Data("Carbide Knife II_3"),
Data("Iron Riv_1"),
Data("Iron Riv_2"),
Data("Iron Riv_3"),
Data("Titanium Riv_1"),
Data("Titanium Riv_2"),
Data("Titanium Riv_3"),
Data("Chrome Riv_1"),
Data("Chrome Riv_2"),
Data("Chrome Riv_3"),
Data("Cobalt Riv_1"),
Data("Cobalt Riv_2"),
Data("Cobalt Riv_3"),
Data("Chromoly Riv_1"),
Data("Chromoly Riv_2"),
Data("Chromoly Riv_3"),
Data("Cermet Riv_1"),
Data("Cermet Riv_2"),
Data("Cermet Riv_3"),
Data("Carbide Riv_1"),
Data("Carbide Riv_2"),
Data("Carbide Riv_3"),
Data("Iron Pugio_1"),
Data("Iron Pugio_2"),
Data("Iron Pugio_3"),
Data("Titanium Pugio_1"),
Data("Titanium Pugio_2"),
Data("Titanium Pugio_3"),
Data("Chrome Pugio_1"),
Data("Chrome Pugio_2"),
Data("Chrome Pugio_3"),
Data("Cobalt Pugio_1"),
Data("Cobalt Pugio_2"),
Data("Cobalt Pugio_3"),
Data("Chromoly Pugio_1"),
Data("Chromoly Pugio_2"),
Data("Chromoly Pugio_3"),
Data("Cermet Pugio_1"),
Data("Cermet Pugio_2"),
Data("Cermet Pugio_3"),
Data("Carbide Pugio_1"),
Data("Carbide Pugio_2"),
Data("Carbide Pugio_3"),
Data("Iron Pokepoke_1"),
Data("Iron Pokepoke_2"),
Data("Iron Pokepoke_3"),
Data("Titanium Pokepoke_1"),
Data("Titanium Pokepoke_2"),
Data("Titanium Pokepoke_3"),
Data("Chrome Pokepoke_1"),
Data("Chrome Pokepoke_2"),
Data("Chrome Pokepoke_3"),
Data("Cobalt Pokepoke_1"),
Data("Cobalt Pokepoke_2"),
Data("Cobalt Pokepoke_3"),
Data("Chromoly Pokepoke_1"),
Data("Chromoly Pokepoke_2"),
Data("Chromoly Pokepoke_3"),
Data("Cermet Pokepoke_1"),
Data("Cermet Pokepoke_2"),
Data("Cermet Pokepoke_3"),
Data("Carbide Pokepoke_1"),
Data("Carbide Pokepoke_2"),
Data("Carbide Pokepoke_3"),
Data("Iron Iyst_1"),
Data("Iron Iyst_2"),
Data("Iron Iyst_3"),
Data("Titanium Iyst_1"),
Data("Titanium Iyst_2"),
Data("Titanium Iyst_3"),
Data("Chrome Iyst_1"),
Data("Chrome Iyst_2"),
Data("Chrome Iyst_3"),
Data("Cobalt Iyst_1"),
Data("Cobalt Iyst_2"),
Data("Cobalt Iyst_3"),
Data("Chromoly Iyst_1"),
Data("Chromoly Iyst_2"),
Data("Chromoly Iyst_3"),
Data("Cermet Iyst_1"),
Data("Cermet Iyst_2"),
Data("Cermet Iyst_3"),
Data("Carbide Iyst_1"),
Data("Carbide Iyst_2"),
Data("Carbide Iyst_3"),
Data("Iron Iyst II_1"),
Data("Iron Iyst II_2"),
Data("Iron Iyst II_3"),
Data("Titanium Iyst II_1"),
Data("Titanium Iyst II_2"),
Data("Titanium Iyst II_3"),
Data("Chrome Iyst II_1"),
Data("Chrome Iyst II_2"),
Data("Chrome Iyst II_3"),
Data("Cobalt Iyst II_1"),
Data("Cobalt Iyst II_2"),
Data("Cobalt Iyst II_3"),
Data("Chromoly Iyst II_1"),
Data("Chromoly Iyst II_2"),
Data("Chromoly Iyst II_3"),
Data("Cermet Iyst II_1"),
Data("Cermet Iyst II_2"),
Data("Cermet Iyst II_3"),
Data("Carbide Iyst II_1"),
Data("Carbide Iyst II_2"),
Data("Carbide Iyst II_3"),
Data("Advanced Iron Knife"),
Data("Worn Titanium Knife"),
Data("Advanced Titanium Knife"),
Data("Worn Chrome Knife"),
Data("Advanced Chrome Knife"),
Data("Worn Cobalt Knife"),
Data("Advanced Cobalt Knife"),
Data("Worn Chromoly Knife"),
Data("Advanced Chromoly Knife"),
Data("Worn Cermet Knife"),
Data("Advanced Cermet Knife"),
Data("Worn Carbide Knife"),
Data("Advanced Iron Knife III"),
Data("Worn Titanium Knife III"),
Data("Advanced Titanium Knife III"),
Data("Worn Chrome Knife III"),
Data("Advanced Chrome Knife III"),
Data("Worn Cobalt Knife III"),
Data("Advanced Cobalt Knife III"),
Data("Worn Chromoly Knife III"),
Data("Advanced Chromoly Knife III"),
Data("Worn Cermet Knife III"),
Data("Advanced Cermet Knife III"),
Data("Worn Carbide Knife III"),
Data("Advanced Iron Knife II"),
Data("Worn Titanium Knife II"),
Data("Advanced Titanium Knife II"),
Data("Worn Chrome Knife II"),
Data("Advanced Chrome Knife II"),
Data("Worn Cobalt Knife II"),
Data("Advanced Cobalt Knife II"),
Data("Worn Chromoly Knife II"),
Data("Advanced Chromoly Knife II"),
Data("Worn Cermet Knife II"),
Data("Advanced Cermet Knife II"),
Data("Worn Carbide Knife II"),
Data("Advanced Iron Riv"),
Data("Worn Titanium Riv"),
Data("Advanced Titanium Riv"),
Data("Worn Chrome Riv"),
Data("Advanced Chrome Riv"),
Data("Worn Cobalt Riv"),
Data("Advanced Cobalt Riv"),
Data("Worn Chromoly Riv"),
Data("Advanced Chromoly Riv"),
Data("Worn Cermet Riv"),
Data("Advanced Cermet Riv"),
Data("Worn Carbide Riv"),
Data("Worn Chrome Pugio"),
Data("Advanced Chrome Pugio"),
Data("Worn Cobalt Pugio"),
Data("Advanced Cobalt Pugio"),
Data("Worn Chromoly Pugio"),
Data("Advanced Chromoly Pugio"),
Data("Worn Cermet Pugio"),
Data("Advanced Cermet Pugio"),
Data("Worn Carbide Pugio"),
Data("Advanced Chrome Pokepoke"),
Data("Worn Cobalt Pokepoke"),
Data("Advanced Cobalt Pokepoke"),
Data("Worn Chromoly Pokepoke"),
Data("Advanced Chromoly Pokepoke"),
Data("Worn Cermet Pokepoke"),
Data("Advanced Cermet Pokepoke"),
Data("Worn Carbide Pokepoke"),
Data("Worn Cobalt Iyst"),
Data("Advanced Cobalt Iyst"),
Data("Worn Chromoly Iyst"),
Data("Advanced Chromoly Iyst"),
Data("Worn Cermet Iyst"),
Data("Advanced Cermet Iyst"),
Data("Worn Carbide Iyst"),
Data("Worn Cobalt Iyst II"),
Data("Advanced Cobalt Iyst II"),
Data("Worn Chromoly Iyst II"),
Data("Advanced Chromoly Iyst II"),
Data("Worn Cermet Iyst II"),
Data("Advanced Cermet Iyst II"),
Data("Worn Carbide Iyst II"),
Data("Ultra Ceramic Knife"),
Data("Ultra Diamond Knife"),
Data("Ultra Ceramic Knife III"),
Data("Ultra Diamond Knife III"),
Data("Ultra Ceramic Knife II"),
Data("Ultra Diamond Knife II"),
Data("Ultra Ceramic Riv"),
Data("Ultra Diamond Riv"),
Data("Ultra Ceramic Pugio"),
Data("Ultra Diamond Pugio"),
Data("Ultra Ceramic Pokepoke"),
Data("Ultra Diamond Pokepoke"),
Data("Ultra Ceramic Iyst"),
Data("Ultra Diamond Iyst"),
Data("Ultra Ceramic Iyst II"),
Data("Ultra Diamond Iyst II"),
Data("Iron Shield_1"),
Data("Iron Shield_2"),
Data("Iron Shield_3"),
Data("Titanium Shield_1"),
Data("Titanium Shield_2"),
Data("Titanium Shield_3"),
Data("Chrome Shield_1"),
Data("Chrome Shield_2"),
Data("Chrome Shield_3"),
Data("Cobalt Shield_1"),
Data("Cobalt Shield_2"),
Data("Cobalt Shield_3"),
Data("Chromoly Shield_1"),
Data("Chromoly Shield_2"),
Data("Chromoly Shield_3"),
Data("Cermet Shield_1"),
Data("Cermet Shield_2"),
Data("Cermet Shield_3"),
Data("Carbide Shield_1"),
Data("Carbide Shield_2"),
Data("Carbide Shield_3"),
Data("Iron Paive_1"),
Data("Iron Paive_2"),
Data("Iron Paive_3"),
Data("Titanium Paive_1"),
Data("Titanium Paive_2"),
Data("Titanium Paive_3"),
Data("Chrome Paive_1"),
Data("Chrome Paive_2"),
Data("Chrome Paive_3"),
Data("Cobalt Paive_1"),
Data("Cobalt Paive_2"),
Data("Cobalt Paive_3"),
Data("Chromoly Paive_1"),
Data("Chromoly Paive_2"),
Data("Chromoly Paive_3"),
Data("Cermet Paive_1"),
Data("Cermet Paive_2"),
Data("Cermet Paive_3"),
Data("Carbide Paive_1"),
Data("Carbide Paive_2"),
Data("Carbide Paive_3"),
Data("Iron Parma_1"),
Data("Iron Parma_2"),
Data("Iron Parma_3"),
Data("Titanium Parma_1"),
Data("Titanium Parma_2"),
Data("Titanium Parma_3"),
Data("Chrome Parma_1"),
Data("Chrome Parma_2"),
Data("Chrome Parma_3"),
Data("Cobalt Parma_1"),
Data("Cobalt Parma_2"),
Data("Cobalt Parma_3"),
Data("Chromoly Parma_1"),
Data("Chromoly Parma_2"),
Data("Chromoly Parma_3"),
Data("Cermet Parma_1"),
Data("Cermet Parma_2"),
Data("Cermet Parma_3"),
Data("Carbide Parma_1"),
Data("Carbide Parma_2"),
Data("Carbide Parma_3"),
Data("Iron Parma II_1"),
Data("Iron Parma II_2"),
Data("Iron Parma II_3"),
Data("Titanium Parma II_1"),
Data("Titanium Parma II_2"),
Data("Titanium Parma II_3"),
Data("Chrome Parma II_1"),
Data("Chrome Parma II_2"),
Data("Chrome Parma II_3"),
Data("Cobalt Parma II_1"),
Data("Cobalt Parma II_2"),
Data("Cobalt Parma II_3"),
Data("Chromoly Parma II_1"),
Data("Chromoly Parma II_2"),
Data("Chromoly Parma II_3"),
Data("Cermet Parma II_1"),
Data("Cermet Parma II_2"),
Data("Cermet Parma II_3"),
Data("Carbide Parma II_1"),
Data("Carbide Parma II_2"),
Data("Carbide Parma II_3"),
Data("Iron Haven_1"),
Data("Iron Haven_2"),
Data("Iron Haven_3"),
Data("Titanium Haven_1"),
Data("Titanium Haven_2"),
Data("Titanium Haven_3"),
Data("Chrome Haven_1"),
Data("Chrome Haven_2"),
Data("Chrome Haven_3"),
Data("Cobalt Haven_1"),
Data("Cobalt Haven_2"),
Data("Cobalt Haven_3"),
Data("Chromoly Haven_1"),
Data("Chromoly Haven_2"),
Data("Chromoly Haven_3"),
Data("Cermet Haven_1"),
Data("Cermet Haven_2"),
Data("Cermet Haven_3"),
Data("Carbide Haven_1"),
Data("Carbide Haven_2"),
Data("Carbide Haven_3"),
Data("Iron Haven II_1"),
Data("Iron Haven II_2"),
Data("Iron Haven II_3"),
Data("Titanium Haven II_1"),
Data("Titanium Haven II_2"),
Data("Titanium Haven II_3"),
Data("Chrome Haven II_1"),
Data("Chrome Haven II_2"),
Data("Chrome Haven II_3"),
Data("Cobalt Haven II_1"),
Data("Cobalt Haven II_2"),
Data("Cobalt Haven II_3"),
Data("Chromoly Haven II_1"),
Data("Chromoly Haven II_2"),
Data("Chromoly Haven II_3"),
Data("Cermet Haven II_1"),
Data("Cermet Haven II_2"),
Data("Cermet Haven II_3"),
Data("Carbide Haven II_1"),
Data("Carbide Haven II_2"),
Data("Carbide Haven II_3"),
Data("Iron Thudclang_1"),
Data("Iron Thudclang_2"),
Data("Iron Thudclang_3"),
Data("Titanium Thudclang_1"),
Data("Titanium Thudclang_2"),
Data("Titanium Thudclang_3"),
Data("Chrome Thudclang_1"),
Data("Chrome Thudclang_2"),
Data("Chrome Thudclang_3"),
Data("Cobalt Thudclang_1"),
Data("Cobalt Thudclang_2"),
Data("Cobalt Thudclang_3"),
Data("Chromoly Thudclang_1"),
Data("Chromoly Thudclang_2"),
Data("Chromoly Thudclang_3"),
Data("Cermet Thudclang_1"),
Data("Cermet Thudclang_2"),
Data("Cermet Thudclang_3"),
Data("Carbide Thudclang_1"),
Data("Carbide Thudclang_2"),
Data("Carbide Thudclang_3"),
Data("Iron Honor_1"),
Data("Iron Honor_2"),
Data("Iron Honor_3"),
Data("Titanium Honor_1"),
Data("Titanium Honor_2"),
Data("Titanium Honor_3"),
Data("Chrome Honor_1"),
Data("Chrome Honor_2"),
Data("Chrome Honor_3"),
Data("Cobalt Honor_1"),
Data("Cobalt Honor_2"),
Data("Cobalt Honor_3"),
Data("Chromoly Honor_1"),
Data("Chromoly Honor_2"),
Data("Chromoly Honor_3"),
Data("Cermet Honor_1"),
Data("Cermet Honor_2"),
Data("Cermet Honor_3"),
Data("Carbide Honor_1"),
Data("Carbide Honor_2"),
Data("Carbide Honor_3"),
Data("Advanced Iron Shield"),
Data("Worn Titanium Shield"),
Data("Advanced Titanium Shield"),
Data("Worn Chrome Shield"),
Data("Advanced Chrome Shield"),
Data("Worn Cobalt Shield"),
Data("Advanced Cobalt Shield"),
Data("Worn Chromoly Shield"),
Data("Advanced Chromoly Shield"),
Data("Worn Cermet Shield"),
Data("Advanced Cermet Shield"),
Data("Worn Carbide Shield"),
Data("Advanced Iron Paive"),
Data("Worn Titanium Paive"),
Data("Advanced Titanium Paive"),
Data("Worn Chrome Paive"),
Data("Advanced Chrome Paive"),
Data("Worn Cobalt Paive"),
Data("Advanced Cobalt Paive"),
Data("Worn Chromoly Paive"),
Data("Advanced Chromoly Paive"),
Data("Worn Cermet Paive"),
Data("Advanced Cermet Paive"),
Data("Worn Carbide Paive"),
Data("Worn Chrome Parma"),
Data("Advanced Chrome Parma"),
Data("Worn Cobalt Parma"),
Data("Advanced Cobalt Parma"),
Data("Worn Chromoly Parma"),
Data("Advanced Chromoly Parma"),
Data("Worn Cermet Parma"),
Data("Advanced Cermet Parma"),
Data("Worn Carbide Parma"),
Data("Worn Chrome Parma II"),
Data("Advanced Chrome Parma II"),
Data("Worn Cobalt Parma II"),
Data("Advanced Cobalt Parma II"),
Data("Worn Chromoly Parma II"),
Data("Advanced Chromoly Parma II"),
Data("Worn Cermet Parma II"),
Data("Advanced Cermet Parma II"),
Data("Worn Carbide Parma II"),
Data("Advanced Chrome Haven"),
Data("Worn Cobalt Haven"),
Data("Advanced Cobalt Haven"),
Data("Worn Chromoly Haven"),
Data("Advanced Chromoly Haven"),
Data("Worn Cermet Haven"),
Data("Advanced Cermet Haven"),
Data("Worn Carbide Haven"),
Data("Advanced Chrome Haven II"),
Data("Worn Cobalt Haven II"),
Data("Advanced Cobalt Haven II"),
Data("Worn Chromoly Haven II"),
Data("Advanced Chromoly Haven II"),
Data("Worn Cermet Haven II"),
Data("Advanced Cermet Haven II"),
Data("Worn Carbide Haven II"),
Data("Advanced Chrome Thudclang"),
Data("Worn Cobalt Thudclang"),
Data("Advanced Cobalt Thudclang"),
Data("Worn Chromoly Thudclang"),
Data("Advanced Chromoly Thudclang"),
Data("Worn Cermet Thudclang"),
Data("Advanced Cermet Thudclang"),
Data("Worn Carbide Thudclang"),
Data("Advanced Chrome Honor"),
Data("Worn Cobalt Honor"),
Data("Advanced Cobalt Honor"),
Data("Worn Chromoly Honor"),
Data("Advanced Chromoly Honor"),
Data("Worn Cermet Honor"),
Data("Advanced Cermet Honor"),
Data("Worn Carbide Honor"),
Data("Ultra Ceramic Shield"),
Data("Ultra Diamond Shield"),
Data("Ultra Ceramic Paive"),
Data("Ultra Diamond Paive"),
Data("Ultra Ceramic Parma"),
Data("Ultra Diamond Parma"),
Data("Ultra Ceramic Parma II"),
Data("Ultra Diamond Parma II"),
Data("Ultra Ceramic Haven"),
Data("Ultra Diamond Haven"),
Data("Ultra Ceramic Haven II"),
Data("Ultra Diamond Haven II"),
Data("Ultra Ceramic Thudclang"),
Data("Ultra Diamond Thudclang"),
Data("Ultra Ceramic Honor"),
Data("Ultra Diamond Honor"),
Data("Iron Spear_1"),
Data("Iron Spear_2"),
Data("Iron Spear_3"),
Data("Titanium Spear_1"),
Data("Titanium Spear_2"),
Data("Titanium Spear_3"),
Data("Chrome Spear_1"),
Data("Chrome Spear_2"),
Data("Chrome Spear_3"),
Data("Cobalt Spear_1"),
Data("Cobalt Spear_2"),
Data("Cobalt Spear_3"),
Data("Chromoly Spear_1"),
Data("Chromoly Spear_2"),
Data("Chromoly Spear_3"),
Data("Cermet Spear_1"),
Data("Cermet Spear_2"),
Data("Cermet Spear_3"),
Data("Carbide Spear_1"),
Data("Carbide Spear_2"),
Data("Carbide Spear_3"),
Data("Iron Spear II_1"),
Data("Iron Spear II_2"),
Data("Iron Spear II_3"),
Data("Titanium Spear II_1"),
Data("Titanium Spear II_2"),
Data("Titanium Spear II_3"),
Data("Chrome Spear II_1"),
Data("Chrome Spear II_2"),
Data("Chrome Spear II_3"),
Data("Cobalt Spear II_1"),
Data("Cobalt Spear II_2"),
Data("Cobalt Spear II_3"),
Data("Chromoly Spear II_1"),
Data("Chromoly Spear II_2"),
Data("Chromoly Spear II_3"),
Data("Cermet Spear II_1"),
Data("Cermet Spear II_2"),
Data("Cermet Spear II_3"),
Data("Carbide Spear II_1"),
Data("Carbide Spear II_2"),
Data("Carbide Spear II_3"),
Data("Iron Parce_1"),
Data("Iron Parce_2"),
Data("Iron Parce_3"),
Data("Titanium Parce_1"),
Data("Titanium Parce_2"),
Data("Titanium Parce_3"),
Data("Chrome Parce_1"),
Data("Chrome Parce_2"),
Data("Chrome Parce_3"),
Data("Cobalt Parce_1"),
Data("Cobalt Parce_2"),
Data("Cobalt Parce_3"),
Data("Chromoly Parce_1"),
Data("Chromoly Parce_2"),
Data("Chromoly Parce_3"),
Data("Cermet Parce_1"),
Data("Cermet Parce_2"),
Data("Cermet Parce_3"),
Data("Carbide Parce_1"),
Data("Carbide Parce_2"),
Data("Carbide Parce_3"),
Data("Iron Pilum_1"),
Data("Iron Pilum_2"),
Data("Iron Pilum_3"),
Data("Titanium Pilum_1"),
Data("Titanium Pilum_2"),
Data("Titanium Pilum_3"),
Data("Chrome Pilum_1"),
Data("Chrome Pilum_2"),
Data("Chrome Pilum_3"),
Data("Cobalt Pilum_1"),
Data("Cobalt Pilum_2"),
Data("Cobalt Pilum_3"),
Data("Chromoly Pilum_1"),
Data("Chromoly Pilum_2"),
Data("Chromoly Pilum_3"),
Data("Cermet Pilum_1"),
Data("Cermet Pilum_2"),
Data("Cermet Pilum_3"),
Data("Carbide Pilum_1"),
Data("Carbide Pilum_2"),
Data("Carbide Pilum_3"),
Data("Iron Pilum II_1"),
Data("Iron Pilum II_2"),
Data("Iron Pilum II_3"),
Data("Titanium Pilum II_1"),
Data("Titanium Pilum II_2"),
Data("Titanium Pilum II_3"),
Data("Chrome Pilum II_1"),
Data("Chrome Pilum II_2"),
Data("Chrome Pilum II_3"),
Data("Cobalt Pilum II_1"),
Data("Cobalt Pilum II_2"),
Data("Cobalt Pilum II_3"),
Data("Chromoly Pilum II_1"),
Data("Chromoly Pilum II_2"),
Data("Chromoly Pilum II_3"),
Data("Cermet Pilum II_1"),
Data("Cermet Pilum II_2"),
Data("Cermet Pilum II_3"),
Data("Carbide Pilum II_1"),
Data("Carbide Pilum II_2"),
Data("Carbide Pilum II_3"),
Data("Iron Bolide_1"),
Data("Iron Bolide_2"),
Data("Iron Bolide_3"),
Data("Titanium Bolide_1"),
Data("Titanium Bolide_2"),
Data("Titanium Bolide_3"),
Data("Chrome Bolide_1"),
Data("Chrome Bolide_2"),
Data("Chrome Bolide_3"),
Data("Cobalt Bolide_1"),
Data("Cobalt Bolide_2"),
Data("Cobalt Bolide_3"),
Data("Chromoly Bolide_1"),
Data("Chromoly Bolide_2"),
Data("Chromoly Bolide_3"),
Data("Cermet Bolide_1"),
Data("Cermet Bolide_2"),
Data("Cermet Bolide_3"),
Data("Carbide Bolide_1"),
Data("Carbide Bolide_2"),
Data("Carbide Bolide_3"),
Data("Iron Jyth_1"),
Data("Iron Jyth_2"),
Data("Iron Jyth_3"),
Data("Titanium Jyth_1"),
Data("Titanium Jyth_2"),
Data("Titanium Jyth_3"),
Data("Chrome Jyth_1"),
Data("Chrome Jyth_2"),
Data("Chrome Jyth_3"),
Data("Cobalt Jyth_1"),
Data("Cobalt Jyth_2"),
Data("Cobalt Jyth_3"),
Data("Chromoly Jyth_1"),
Data("Chromoly Jyth_2"),
Data("Chromoly Jyth_3"),
Data("Cermet Jyth_1"),
Data("Cermet Jyth_2"),
Data("Cermet Jyth_3"),
Data("Carbide Jyth_1"),
Data("Carbide Jyth_2"),
Data("Carbide Jyth_3"),
Data("IW_MU_F_JAVELIN_A02_0101_name_1", valid=False),
Data("IW_MU_F_JAVELIN_A02_0101_name_2", valid=False),
Data("IW_MU_F_JAVELIN_A02_0101_name_3", valid=False),
Data("IW_MU_F_JAVELIN_A03_1001_name_1", valid=False),
Data("IW_MU_F_JAVELIN_A03_1001_name_2", valid=False),
Data("IW_MU_F_JAVELIN_A03_1001_name_3", valid=False),
Data("Faithful Lance_1"),
Data("Faithful Lance_2"),
Data("Faithful Lance_3"),
Data("Steelbreaker Lance_1"),
Data("Steelbreaker Lance_2"),
Data("Steelbreaker Lance_3"),
Data("Pulverizing Lance_1"),
Data("Pulverizing Lance_2"),
Data("Pulverizing Lance_3"),
Data("Intrepid Lance_1"),
Data("Intrepid Lance_2"),
Data("Intrepid Lance_3"),
Data("Audacious Lance_1"),
Data("Audacious Lance_2"),
Data("Audacious Lance_3"),
Data("Advanced Iron Spear"),
Data("Worn Titanium Spear"),
Data("Advanced Titanium Spear"),
Data("Worn Chrome Spear"),
Data("Advanced Chrome Spear"),
Data("Worn Cobalt Spear"),
Data("Advanced Cobalt Spear"),
Data("Worn Chromoly Spear"),
Data("Advanced Chromoly Spear"),
Data("Worn Cermet Spear"),
Data("Advanced Cermet Spear"),
Data("Worn Carbide Spear"),
Data("Advanced Iron Spear II"),
Data("Worn Titanium Spear II"),
Data("Advanced Titanium Spear II"),
Data("Worn Chrome Spear II"),
Data("Advanced Chrome Spear II"),
Data("Worn Cobalt Spear II"),
Data("Advanced Cobalt Spear II"),
Data("Worn Chromoly Spear II"),
Data("Advanced Chromoly Spear II"),
Data("Worn Cermet Spear II"),
Data("Advanced Cermet Spear II"),
Data("Worn Carbide Spear II"),
Data("Advanced Iron Parce"),
Data("Worn Titanium Parce"),
Data("Advanced Titanium Parce"),
Data("Worn Chrome Parce"),
Data("Advanced Chrome Parce"),
Data("Worn Cobalt Parce"),
Data("Advanced Cobalt Parce"),
Data("Worn Chromoly Parce"),
Data("Advanced Chromoly Parce"),
Data("Worn Cermet Parce"),
Data("Advanced Cermet Parce"),
Data("Worn Carbide Parce"),
Data("Worn Chrome Pilum"),
Data("Advanced Chrome Pilum"),
Data("Worn Cobalt Pilum"),
Data("Advanced Cobalt Pilum"),
Data("Worn Chromoly Pilum"),
Data("Advanced Chromoly Pilum"),
Data("Worn Cermet Pilum"),
Data("Advanced Cermet Pilum"),
Data("Worn Carbide Pilum"),
Data("Worn Chrome Pilum II"),
Data("Advanced Chrome Pilum II"),
Data("Worn Cobalt Pilum II"),
Data("Advanced Cobalt Pilum II"),
Data("Worn Chromoly Pilum II"),
Data("Advanced Chromoly Pilum II"),
Data("Worn Cermet Pilum II"),
Data("Advanced Cermet Pilum II"),
Data("Worn Carbide Pilum II"),
Data("Advanced Chrome Bolide"),
Data("Worn Cobalt Bolide"),
Data("Advanced Cobalt Bolide"),
Data("Worn Chromoly Bolide"),
Data("Advanced Chromoly Bolide"),
Data("Worn Cermet Bolide"),
Data("Advanced Cermet Bolide"),
Data("Worn Carbide Bolide"),
Data("Worn Cobalt Jyth"),
Data("Advanced Cobalt Jyth"),
Data("Worn Chromoly Jyth"),
Data("Advanced Chromoly Jyth"),
Data("Worn Cermet Jyth"),
Data("Advanced Cermet Jyth"),
Data("Worn Carbide Jyth"),
Data("Advanced Steelbreaker Lance"),
Data("Worn Pulverizing Lance"),
Data("Advanced Pulverizing Lance"),
Data("Worn Intrepid Lance"),
Data("Advanced Intrepid Lance"),
Data("Worn Audacious Lance"),
Data("Ultra Ceramic Spear"),
Data("Ultra Diamond Spear"),
Data("Ultra Ceramic Spear II"),
Data("Ultra Diamond Spear II"),
Data("Ultra Ceramic Parce"),
Data("Ultra Diamond Parce"),
Data("Ultra Ceramic Pilum"),
Data("Ultra Diamond Pilum"),
Data("Ultra Ceramic Pilum II"),
Data("Ultra Diamond Pilum II"),
Data("Ultra Ceramic Bolide"),
Data("Ultra Diamond Bolide"),
Data("Ultra Ceramic Jyth"),
Data("Ultra Diamond Jyth"),
Data("Ultra Godbreaker Lance"),
Data("Ultra Phenomenon Lance"),
Data("Iron Saber_1"),
Data("Iron Saber_2"),
Data("Iron Saber_3"),
Data("Titanium Saber_1"),
Data("Titanium Saber_2"),
Data("Titanium Saber_3"),
Data("Chrome Saber_1"),
Data("Chrome Saber_2"),
Data("Chrome Saber_3"),
Data("Cobalt Saber_1"),
Data("Cobalt Saber_2"),
Data("Cobalt Saber_3"),
Data("Chromoly Saber_1"),
Data("Chromoly Saber_2"),
Data("Chromoly Saber_3"),
Data("Cermet Saber_1"),
Data("Cermet Saber_2"),
Data("Cermet Saber_3"),
Data("Carbide Saber_1"),
Data("Carbide Saber_2"),
Data("Carbide Saber_3"),
Data("Iron Fulge_1"),
Data("Iron Fulge_2"),
Data("Iron Fulge_3"),
Data("Titanium Fulge_1"),
Data("Titanium Fulge_2"),
Data("Titanium Fulge_3"),
Data("Chrome Fulge_1"),
Data("Chrome Fulge_2"),
Data("Chrome Fulge_3"),
Data("Cobalt Fulge_1"),
Data("Cobalt Fulge_2"),
Data("Cobalt Fulge_3"),
Data("Chromoly Fulge_1"),
Data("Chromoly Fulge_2"),
Data("Chromoly Fulge_3"),
Data("Cermet Fulge_1"),
Data("Cermet Fulge_2"),
Data("Cermet Fulge_3"),
Data("Carbide Fulge_1"),
Data("Carbide Fulge_2"),
Data("Carbide Fulge_3"),
Data("Iron Fulge II_1"),
Data("Iron Fulge II_2"),
Data("Iron Fulge II_3"),
Data("Titanium Fulge II_1"),
Data("Titanium Fulge II_2"),
Data("Titanium Fulge II_3"),
Data("Chrome Fulge II_1"),
Data("Chrome Fulge II_2"),
Data("Chrome Fulge II_3"),
Data("Cobalt Fulge II_1"),
Data("Cobalt Fulge II_2"),
Data("Cobalt Fulge II_3"),
Data("Chromoly Fulge II_1"),
Data("Chromoly Fulge II_2"),
Data("Chromoly Fulge II_3"),
Data("Cermet Fulge II_1"),
Data("Cermet Fulge II_2"),
Data("Cermet Fulge II_3"),
Data("Carbide Fulge II_1"),
Data("Carbide Fulge II_2"),
Data("Carbide Fulge II_3"),
Data("Iron Candela_1"),
Data("Iron Candela_2"),
Data("Iron Candela_3"),
Data("Titanium Candela_1"),
Data("Titanium Candela_2"),
Data("Titanium Candela_3"),
Data("Chrome Candela_1"),
Data("Chrome Candela_2"),
Data("Chrome Candela_3"),
Data("Cobalt Candela_1"),
Data("Cobalt Candela_2"),
Data("Cobalt Candela_3"),
Data("Chromoly Candela_1"),
Data("Chromoly Candela_2"),
Data("Chromoly Candela_3"),
Data("Cermet Candela_1"),
Data("Cermet Candela_2"),
Data("Cermet Candela_3"),
Data("Carbide Candela_1"),
Data("Carbide Candela_2"),
Data("Carbide Candela_3"),
Data("Iron Candela II_1"),
Data("Iron Candela II_2"),
Data("Iron Candela II_3"),
Data("Titanium Candela II_1"),
Data("Titanium Candela II_2"),
Data("Titanium Candela II_3"),
Data("Chrome Candela II_1"),
Data("Chrome Candela II_2"),
Data("Chrome Candela II_3"),
Data("Cobalt Candela II_1"),
Data("Cobalt Candela II_2"),
Data("Cobalt Candela II_3"),
Data("Chromoly Candela II_1"),
Data("Chromoly Candela II_2"),
Data("Chromoly Candela II_3"),
Data("Cermet Candela II_1"),
Data("Cermet Candela II_2"),
Data("Cermet Candela II_3"),
Data("Carbide Candela II_1"),
Data("Carbide Candela II_2"),
Data("Carbide Candela II_3"),
Data("Iron Candela III_1"),
Data("Iron Candela III_2"),
Data("Iron Candela III_3"),
Data("Titanium Candela III_1"),
Data("Titanium Candela III_2"),
Data("Titanium Candela III_3"),
Data("Chrome Candela III_1"),
Data("Chrome Candela III_2"),
Data("Chrome Candela III_3"),
Data("Cobalt Candela III_1"),
Data("Cobalt Candela III_2"),
Data("Cobalt Candela III_3"),
Data("Chromoly Candela III_1"),
Data("Chromoly Candela III_2"),
Data("Chromoly Candela III_3"),
Data("Cermet Candela III_1"),
Data("Cermet Candela III_2"),
Data("Cermet Candela III_3"),
Data("Carbide Candela III_1"),
Data("Carbide Candela III_2"),
Data("Carbide Candela III_3"),
Data("IW_MU_F_PHOTON_A04_0101_name_1", valid=False),
Data("IW_MU_F_PHOTON_A04_0101_name_2", valid=False),
Data("IW_MU_F_PHOTON_A04_0101_name_3", valid=False),
Data("IW_MU_F_PHOTON_A05_1001_name_1", valid=False),
Data("IW_MU_F_PHOTON_A05_1001_name_2", valid=False),
Data("IW_MU_F_PHOTON_A05_1001_name_3", valid=False),
Data("Faithful Lightblade_1"),
Data("Faithful Lightblade_2"),
Data("Faithful Lightblade_3"),
Data("Steelbreaker Lightblade_1"),
Data("Steelbreaker Lightblade_2"),
Data("Steelbreaker Lightblade_3"),
Data("Pulverizing Lightblade_1"),
Data("Pulverizing Lightblade_2"),
Data("Pulverizing Lightblade_3"),
Data("Intrepid Lightblade_1"),
Data("Intrepid Lightblade_2"),
Data("Intrepid Lightblade_3"),
Data("Audacious Lightblade_1"),
Data("Audacious Lightblade_2"),
Data("Audacious Lightblade_3"),
Data("IW_MU_F_PHOTON_B04_0101_name_1", valid=False),
Data("IW_MU_F_PHOTON_B04_0101_name_2", valid=False),
Data("IW_MU_F_PHOTON_B04_0101_name_3", valid=False),
Data("IW_MU_F_PHOTON_B05_1001_name_1", valid=False),
Data("IW_MU_F_PHOTON_B05_1001_name_2", valid=False),
Data("IW_MU_F_PHOTON_B05_1001_name_3", valid=False),
Data("Faithful Lightblade II_1"),
Data("Faithful Lightblade II_2"),
Data("Faithful Lightblade II_3"),
Data("Steelbreaker Lightblade II_1"),
Data("Steelbreaker Lightblade II_2"),
Data("Steelbreaker Lightblade II_3"),
Data("Pulverizing Lightblade II_1"),
Data("Pulverizing Lightblade II_2"),
Data("Pulverizing Lightblade II_3"),
Data("Intrepid Lightblade II_1"),
Data("Intrepid Lightblade II_2"),
Data("Intrepid Lightblade II_3"),
Data("Audacious Lightblade II_1"),
Data("Audacious Lightblade II_2"),
Data("Audacious Lightblade II_3"),
Data("Advanced Iron Saber"),
Data("Worn Titanium Saber"),
Data("Advanced Titanium Saber"),
Data("Worn Chrome Saber"),
Data("Advanced Chrome Saber"),
Data("Worn Cobalt Saber"),
Data("Advanced Cobalt Saber"),
Data("Worn Chromoly Saber"),
Data("Advanced Chromoly Saber"),
Data("Worn Cermet Saber"),
Data("Advanced Cermet Saber"),
Data("Worn Carbide Saber"),
Data("Advanced Iron Fulge"),
Data("Worn Titanium Fulge"),
Data("Advanced Titanium Fulge"),
Data("Worn Chrome Fulge"),
Data("Advanced Chrome Fulge"),
Data("Worn Cobalt Fulge"),
Data("Advanced Cobalt Fulge"),
Data("Worn Chromoly Fulge"),
Data("Advanced Chromoly Fulge"),
Data("Worn Cermet Fulge"),
Data("Advanced Cermet Fulge"),
Data("Worn Carbide Fulge"),
Data("Advanced Iron Fulge II"),
Data("Worn Titanium Fulge II"),
Data("Advanced Titanium Fulge II"),
Data("Worn Chrome Fulge II"),
Data("Advanced Chrome Fulge II"),
Data("Worn Cobalt Fulge II"),
Data("Advanced Cobalt Fulge II"),
Data("Worn Chromoly Fulge II"),
Data("Advanced Chromoly Fulge II"),
Data("Worn Cermet Fulge II"),
Data("Advanced Cermet Fulge II"),
Data("Worn Carbide Fulge II"),
Data("Worn Chrome Candela"),
Data("Advanced Chrome Candela"),
Data("Worn Cobalt Candela"),
Data("Advanced Cobalt Candela"),
Data("Worn Chromoly Candela"),
Data("Advanced Chromoly Candela"),
Data("Worn Cermet Candela"),
Data("Advanced Cermet Candela"),
Data("Worn Carbide Candela"),
Data("Worn Chrome Candela II"),
Data("Advanced Chrome Candela II"),
Data("Worn Cobalt Candela II"),
Data("Advanced Cobalt Candela II"),
Data("Worn Chromoly Candela II"),
Data("Advanced Chromoly Candela II"),
Data("Worn Cermet Candela II"),
Data("Advanced Cermet Candela II"),
Data("Worn Carbide Candela II"),
Data("Worn Chrome Candela III"),
Data("Advanced Chrome Candela III"),
Data("Worn Cobalt Candela III"),
Data("Advanced Cobalt Candela III"),
Data("Worn Chromoly Candela III"),
Data("Advanced Chromoly Candela III"),
Data("Worn Cermet Candela III"),
Data("Advanced Cermet Candela III"),
Data("Worn Carbide Candela III"),
Data("Advanced Steelbreaker Lightblade"),
Data("Worn Pulverizing Lightblade"),
Data("Advanced Pulverizing Lightblade"),
Data("Worn Intrepid Lightblade"),
Data("Advanced Intrepid Lightblade"),
Data("Worn Audacious Lightblade"),
Data("Advanced Steelbreaker Lightblade II"),
Data("Worn Pulverizing Lightblade II"),
Data("Advanced Pulverizing Lightblade II"),
Data("Worn Intrepid Lightblade II"),
Data("Advanced Intrepid Lightblade II"),
Data("Worn Audacious Lightblade II"),
Data("Ultra Ceramic Saber"),
Data("Ultra Diamond Saber"),
Data("Ultra Ceramic Fulge"),
Data("Ultra Diamond Fulge"),
Data("Ultra Ceramic Fulge II"),
Data("Ultra Diamond Fulge II"),
Data("Ultra Ceramic Candela"),
Data("Ultra Diamond Candela"),
Data("Ultra Ceramic Candela II"),
Data("Ultra Diamond Candela II"),
Data("Ultra Ceramic Candela III"),
Data("Ultra Diamond Candela III"),
Data("Ultra Godbreaker Lightblade"),
Data("Ultra Phenomenon Lightblade"),
Data("Ultra Godbreaker Lightblade II"),
Data("Ultra Phenomenon Lightblade II"),
Data("Proto Assault Rifle"),
Data("Storm Assault Rifle_1"),
Data("Storm Assault Rifle_2"),
Data("Storm Assault Rifle_3"),
Data("Soldier Assault Rifle_1"),
Data("Soldier Assault Rifle_2"),
Data("Soldier Assault Rifle_3"),
Data("Warrior Assault Rifle_1"),
Data("Warrior Assault Rifle_2"),
Data("Warrior Assault Rifle_3"),
Data("Ophidian Assault Rifle_1"),
Data("Ophidian Assault Rifle_2"),
Data("Ophidian Assault Rifle_3"),
Data("Destroyer Assault Rifle_1"),
Data("Destroyer Assault Rifle_2"),
Data("Destroyer Assault Rifle_3"),
Data("Striker Assault Rifle_1"),
Data("Striker Assault Rifle_2"),
Data("Striker Assault Rifle_3"),
Data("Delta Assault Rifle_1"),
Data("Delta Assault Rifle_2"),
Data("Delta Assault Rifle_3"),
Data("Storm Assault Rifle III_1"),
Data("Storm Assault Rifle III_2"),
Data("Storm Assault Rifle III_3"),
Data("Soldier Assault Rifle III_1"),
Data("Soldier Assault Rifle III_2"),
Data("Soldier Assault Rifle III_3"),
Data("Warrior Assault Rifle III_1"),
Data("Warrior Assault Rifle III_2"),
Data("Warrior Assault Rifle III_3"),
Data("Ophidian Assault Rifle III_1"),
Data("Ophidian Assault Rifle III_2"),
Data("Ophidian Assault Rifle III_3"),
Data("Destroyer Assault Rifle III_1"),
Data("Destroyer Assault Rifle III_2"),
Data("Destroyer Assault Rifle III_3"),
Data("Striker Assault Rifle III_1"),
Data("Striker Assault Rifle III_2"),
Data("Striker Assault Rifle III_3"),
Data("Delta Assault Rifle III_1"),
Data("Delta Assault Rifle III_2"),
Data("Delta Assault Rifle III_3"),
Data("Storm Assault Rifle II_1"),
Data("Storm Assault Rifle II_2"),
Data("Storm Assault Rifle II_3"),
Data("Soldier Assault Rifle II_1"),
Data("Soldier Assault Rifle II_2"),
Data("Soldier Assault Rifle II_3"),
Data("Warrior Assault Rifle II_1"),
Data("Warrior Assault Rifle II_2"),
Data("Warrior Assault Rifle II_3"),
Data("Ophidian Assault Rifle II_1"),
Data("Ophidian Assault Rifle II_2"),
Data("Ophidian Assault Rifle II_3"),
Data("Destroyer Assault Rifle II_1"),
Data("Destroyer Assault Rifle II_2"),
Data("Destroyer Assault Rifle II_3"),
Data("Striker Assault Rifle II_1"),
Data("Striker Assault Rifle II_2"),
Data("Striker Assault Rifle II_3"),
Data("Delta Assault Rifle II_1"),
Data("Delta Assault Rifle II_2"),
Data("Delta Assault Rifle II_3"),
Data("Storm Avagar_1"),
Data("Storm Avagar_2"),
Data("Storm Avagar_3"),
Data("Soldier Avagar_1"),
Data("Soldier Avagar_2"),
Data("Soldier Avagar_3"),
Data("Warrior Avagar_1"),
Data("Warrior Avagar_2"),
Data("Warrior Avagar_3"),
Data("Ophidian Avagar_1"),
Data("Ophidian Avagar_2"),
Data("Ophidian Avagar_3"),
Data("Destroyer Avagar_1"),
Data("Destroyer Avagar_2"),
Data("Destroyer Avagar_3"),
Data("Striker Avagar_1"),
Data("Striker Avagar_2"),
Data("Striker Avagar_3"),
Data("Delta Avagar_1"),
Data("Delta Avagar_2"),
Data("Delta Avagar_3"),
Data("Storm Sclopetum_1"),
Data("Storm Sclopetum_2"),
Data("Storm Sclopetum_3"),
Data("Soldier Sclopetum_1"),
Data("Soldier Sclopetum_2"),
Data("Soldier Sclopetum_3"),
Data("Warrior Sclopetum_1"),
Data("Warrior Sclopetum_2"),
Data("Warrior Sclopetum_3"),
Data("Ophidian Sclopetum_1"),
Data("Ophidian Sclopetum_2"),
Data("Ophidian Sclopetum_3"),
Data("Destroyer Sclopetum_1"),
Data("Destroyer Sclopetum_2"),
Data("Destroyer Sclopetum_3"),
Data("Striker Sclopetum_1"),
Data("Striker Sclopetum_2"),
Data("Striker Sclopetum_3"),
Data("Delta Sclopetum_1"),
Data("Delta Sclopetum_2"),
Data("Delta Sclopetum_3"),
Data("Storm Assailer_1"),
Data("Storm Assailer_2"),
Data("Storm Assailer_3"),
Data("Soldier Assailer_1"),
Data("Soldier Assailer_2"),
Data("Soldier Assailer_3"),
Data("Warrior Assailer_1"),
Data("Warrior Assailer_2"),
Data("Warrior Assailer_3"),
Data("Ophidian Assailer_1"),
Data("Ophidian Assailer_2"),
Data("Ophidian Assailer_3"),
Data("Destroyer Assailer_1"),
Data("Destroyer Assailer_2"),
Data("Destroyer Assailer_3"),
Data("Striker Assailer_1"),
Data("Striker Assailer_2"),
Data("Striker Assailer_3"),
Data("Delta Assailer_1"),
Data("Delta Assailer_2"),
Data("Delta Assailer_3"),
Data("Storm Rapture_1"),
Data("Storm Rapture_2"),
Data("Storm Rapture_3"),
Data("Soldier Rapture_1"),
Data("Soldier Rapture_2"),
Data("Soldier Rapture_3"),
Data("Warrior Rapture_1"),
Data("Warrior Rapture_2"),
Data("Warrior Rapture_3"),
Data("Ophidian Rapture_1"),
Data("Ophidian Rapture_2"),
Data("Ophidian Rapture_3"),
Data("Destroyer Rapture_1"),
Data("Destroyer Rapture_2"),
Data("Destroyer Rapture_3"),
Data("Striker Rapture_1"),
Data("Striker Rapture_2"),
Data("Striker Rapture_3"),
Data("Delta Rapture_1"),
Data("Delta Rapture_2"),
Data("Delta Rapture_3"),
Data("IW_MU_S_ASSAULT_A04_0101_name_1", valid=False),
Data("IW_MU_S_ASSAULT_A04_0101_name_2", valid=False),
Data("IW_MU_S_ASSAULT_A04_0101_name_3", valid=False),
Data("IW_MU_S_ASSAULT_A05_1001_name_1", valid=False),
Data("IW_MU_S_ASSAULT_A05_1001_name_2", valid=False),
Data("IW_MU_S_ASSAULT_A05_1001_name_3", valid=False),
Data("Rugged Raidrifle_1"),
Data("Rugged Raidrifle_2"),
Data("Rugged Raidrifle_3"),
Data("Devastator Raidrifle_1"),
Data("Devastator Raidrifle_2"),
Data("Devastator Raidrifle_3"),
Data("Sparrow Raidrifle_1"),
Data("Sparrow Raidrifle_2"),
Data("Sparrow Raidrifle_3"),
Data("Foxfire Raidrifle_1"),
Data("Foxfire Raidrifle_2"),
Data("Foxfire Raidrifle_3"),
Data("Rectifier Raidrifle_1"),
Data("Rectifier Raidrifle_2"),
Data("Rectifier Raidrifle_3"),
Data("Advanced Storm Assault Rifle"),
Data("Worn Soldier Assault Rifle"),
Data("Advanced Soldier Assault Rifle_1"),
Data("Worn Warrior Assault Rifle"),
Data("Advanced Warrior Assault Rifle"),
Data("Worn Ophidian Assault Rifle"),
Data("Advanced Ophidian Assault Rifle"),
Data("Worn Destroyer Assault Rifle"),
Data("Advanced Destroyer Assault Rifle"),
Data("Worn Striker Assault Rifle"),
Data("Advanced Striker Assault Rifle"),
Data("Worn Delta Assault Rifle"),
Data("Advanced Storm Assault Rifle III"),
Data("Worn Soldier Assault Rifle III"),
Data("Advanced Soldier Assault Rifle III"),
Data("Worn Warrior Assault Rifle III"),
Data("Advanced Warrior Assault Rifle III"),
Data("Worn Ophidian Assault Rifle III"),
Data("Advanced Ophidian Assault Rifle III"),
Data("Worn Destroyer Assault Rifle III"),
Data("Advanced Destroyer Assault Rifle III"),
Data("Worn Striker Assault Rifle III"),
Data("Advanced Striker Assault Rifle III"),
Data("Worn Delta Assault Rifle III"),
Data("Advanced Storm Assault Rifle II"),
Data("Worn Soldier Assault Rifle II"),
Data("Advanced Soldier Assault Rifle II"),
Data("Worn Warrior Assault Rifle II"),
Data("Advanced Warrior Assault Rifle II"),
Data("Worn Ophidian Assault Rifle II"),
Data("Advanced Ophidian Assault Rifle II"),
Data("Worn Destroyer Assault Rifle II"),
Data("Advanced Destroyer Assault Rifle II"),
Data("Worn Striker Assault Rifle II"),
Data("Advanced Striker Assault Rifle II"),
Data("Worn Delta Assault Rifle II"),
Data("Advanced Storm Avagar"),
Data("Worn Soldier Avagar"),
Data("Advanced Soldier Avagar"),
Data("Worn Warrior Avagar"),
Data("Advanced Warrior Avagar"),
Data("Worn Ophidian Avagar"),
Data("Advanced Ophidian Avagar"),
Data("Worn Destroyer Avagar"),
Data("Advanced Destroyer Avagar"),
Data("Worn Striker Avagar"),
Data("Advanced Striker Avagar"),
Data("Worn Delta Avagar"),
Data("Worn Warrior Sclopetum"),
Data("Advanced Warrior Sclopetum"),
Data("Worn Ophidian Sclopetum"),
Data("Advanced Ophidian Sclopetum"),
Data("Worn Destroyer Sclopetum"),
Data("Advanced Destroyer Sclopetum"),
Data("Worn Striker Sclopetum"),
Data("Advanced Striker Sclopetum"),
Data("Worn Delta Sclopetum"),
Data("Advanced Warrior Assailer"),
Data("Worn Ophidian Assailer"),
Data("Advanced Ophidian Assailer"),
Data("Worn Destroyer Assailer"),
Data("Advanced Destroyer Assailer"),
Data("Worn Striker Assailer"),
Data("Advanced Striker Assailer"),
Data("Worn Delta Assailer"),
Data("Advanced Warrior Rapture"),
Data("Worn Ophidian Rapture"),
Data("Advanced Ophidian Rapture"),
Data("Worn Destroyer Rapture"),
Data("Advanced Destroyer Rapture"),
Data("Worn Striker Rapture"),
Data("Advanced Striker Rapture"),
Data("Worn Delta Rapture"),
Data("Advanced Devastator Raidrifle"),
Data("Worn Sparrow Raidrifle"),
Data("Advanced Sparrow Raidrifle"),
Data("Worn Foxfire Raidrifle"),
Data("Advanced Foxfire Raidrifle"),
Data("Worn Rectifier Raidrifle"),
Data("Ultra Cosmic Assault Rifle"),
Data("Ultra Nebulan Assault Rifle"),
Data("Ultra Cosmic Assault Rifle III"),
Data("Ultra Nebulan Assault Rifle III"),
Data("Ultra Cosmic Assault Rifle II"),
Data("Ultra Nebulan Assault Rifle II"),
Data("Ultra Cosmic Avagar"),
Data("Ultra Nebulan Avagar"),
Data("Ultra Cosmic Sclopetum"),
Data("Ultra Nebulan Sclopetum"),
Data("Ultra Cosmic Assailer"),
Data("Ultra Nebulan Assailer"),
Data("Ultra Cosmic Rapture"),
Data("Ultra Nebulan Rapture"),
Data("Ultra Virtue Raidrifle"),
Data("Ultra Transience Raidrifle"),
Data("Storm Dual Guns_1"),
Data("Storm Dual Guns_2"),
Data("Storm Dual Guns_3"),
Data("Soldier Dual Guns_1"),
Data("Soldier Dual Guns_2"),
Data("Soldier Dual Guns_3"),
Data("Warrior Dual Guns_1"),
Data("Warrior Dual Guns_2"),
Data("Warrior Dual Guns_3"),
Data("Ophidian Dual Guns_1"),
Data("Ophidian Dual Guns_2"),
Data("Ophidian Dual Guns_3"),
Data("Destroyer Dual Guns_1"),
Data("Destroyer Dual Guns_2"),
Data("Destroyer Dual Guns_3"),
Data("Striker Dual Guns_1"),
Data("Striker Dual Guns_2"),
Data("Striker Dual Guns_3"),
Data("Delta Dual Guns_1"),
Data("Delta Dual Guns_2"),
Data("Delta Dual Guns_3"),
Data("Storm Dual Guns II_1"),
Data("Storm Dual Guns II_2"),
Data("Storm Dual Guns II_3"),
Data("Soldier Dual Guns II_1"),
Data("Soldier Dual Guns II_2"),
Data("Soldier Dual Guns II_3"),
Data("Warrior Dual Guns II_1"),
Data("Warrior Dual Guns II_2"),
Data("Warrior Dual Guns II_3"),
Data("Ophidian Dual Guns II_1"),
Data("Ophidian Dual Guns II_2"),
Data("Ophidian Dual Guns II_3"),
Data("Destroyer Dual Guns II_1"),
Data("Destroyer Dual Guns II_2"),
Data("Destroyer Dual Guns II_3"),
Data("Striker Dual Guns II_1"),
Data("Striker Dual Guns II_2"),
Data("Striker Dual Guns II_3"),
Data("Delta Dual Guns II_1"),
Data("Delta Dual Guns II_2"),
Data("Delta Dual Guns II_3"),
Data("Storm Gemels_1"),
Data("Storm Gemels_2"),
Data("Storm Gemels_3"),
Data("Soldier Gemels_1"),
Data("Soldier Gemels_2"),
Data("Soldier Gemels_3"),
Data("Warrior Gemels_1"),
Data("Warrior Gemels_2"),
Data("Warrior Gemels_3"),
Data("Ophidian Gemels_1"),
Data("Ophidian Gemels_2"),
Data("Ophidian Gemels_3"),
Data("Destroyer Gemels_1"),
Data("Destroyer Gemels_2"),
Data("Destroyer Gemels_3"),
Data("Striker Gemels_1"),
Data("Striker Gemels_2"),
Data("Striker Gemels_3"),
Data("Delta Gemels_1"),
Data("Delta Gemels_2"),
Data("Delta Gemels_3"),
Data("Storm Pistolia_1"),
Data("Storm Pistolia_2"),
Data("Storm Pistolia_3"),
Data("Soldier Pistolia_1"),
Data("Soldier Pistolia_2"),
Data("Soldier Pistolia_3"),
Data("Warrior Pistolia_1"),
Data("Warrior Pistolia_2"),
Data("Warrior Pistolia_3"),
Data("Ophidian Pistolia_1"),
Data("Ophidian Pistolia_2"),
Data("Ophidian Pistolia_3"),
Data("Destroyer Pistolia_1"),
Data("Destroyer Pistolia_2"),
Data("Destroyer Pistolia_3"),
Data("Striker Pistolia_1"),
Data("Striker Pistolia_2"),
Data("Striker Pistolia_3"),
Data("Delta Pistolia_1"),
Data("Delta Pistolia_2"),
Data("Delta Pistolia_3"),
Data("Storm Dyads_1"),
Data("Storm Dyads_2"),
Data("Storm Dyads_3"),
Data("Soldier Dyads_1"),
Data("Soldier Dyads_2"),
Data("Soldier Dyads_3"),
Data("Warrior Dyads_1"),
Data("Warrior Dyads_2"),
Data("Warrior Dyads_3"),
Data("Ophidian Dyads_1"),
Data("Ophidian Dyads_2"),
Data("Ophidian Dyads_3"),
Data("Destroyer Dyads_1"),
Data("Destroyer Dyads_2"),
Data("Destroyer Dyads_3"),
Data("Striker Dyads_1"),
Data("Striker Dyads_2"),
Data("Striker Dyads_3"),
Data("Delta Dyads_1"),
Data("Delta Dyads_2"),
Data("Delta Dyads_3"),
Data("Storm Dyads III_1"),
Data("Storm Dyads III_2"),
Data("Storm Dyads III_3"),
Data("Soldier Dyads III_1"),
Data("Soldier Dyads III_2"),
Data("Soldier Dyads III_3"),
Data("Warrior Dyads III_1"),
Data("Warrior Dyads III_2"),
Data("Warrior Dyads III_3"),
Data("Ophidian Dyads III_1"),
Data("Ophidian Dyads III_2"),
Data("Ophidian Dyads III_3"),
Data("Destroyer Dyads III_1"),
Data("Destroyer Dyads III_2"),
Data("Destroyer Dyads III_3"),
Data("Striker Dyads III_1"),
Data("Striker Dyads III_2"),
Data("Striker Dyads III_3"),
Data("Delta Dyads III_1"),
Data("Delta Dyads III_2"),
Data("Delta Dyads III_3"),
Data("Storm Dyads II_1"),
Data("Storm Dyads II_2"),
Data("Storm Dyads II_3"),
Data("Soldier Dyads II_1"),
Data("Soldier Dyads II_2"),
Data("Soldier Dyads II_3"),
Data("Warrior Dyads II_1"),
Data("Warrior Dyads II_2"),
Data("Warrior Dyads II_3"),
Data("Ophidian Dyads II_1"),
Data("Ophidian Dyads II_2"),
Data("Ophidian Dyads II_3"),
Data("Destroyer Dyads II_1"),
Data("Destroyer Dyads II_2"),
Data("Destroyer Dyads II_3"),
Data("Striker Dyads II_1"),
Data("Striker Dyads II_2"),
Data("Striker Dyads II_3"),
Data("Delta Dyads II_1"),
Data("Delta Dyads II_2"),
Data("Delta Dyads II_3"),
Data("Storm Bangbangs_1"),
Data("Storm Bangbangs_2"),
Data("Storm Bangbangs_3"),
Data("Soldier Bangbangs_1"),
Data("Soldier Bangbangs_2"),
Data("Soldier Bangbangs_3"),
Data("Warrior Bangbangs_1"),
Data("Warrior Bangbangs_2"),
Data("Warrior Bangbangs_3"),
Data("Ophidian Bangbangs_1"),
Data("Ophidian Bangbangs_2"),
Data("Ophidian Bangbangs_3"),
Data("Destroyer Bangbangs_1"),
Data("Destroyer Bangbangs_2"),
Data("Destroyer Bangbangs_3"),
Data("Striker Bangbangs_1"),
Data("Striker Bangbangs_2"),
Data("Striker Bangbangs_3"),
Data("Delta Bangbangs_1"),
Data("Delta Bangbangs_2"),
Data("Delta Bangbangs_3"),
Data("IW_MU_S_DUALGUN_A03_0101_name_1", valid=False),
Data("IW_MU_S_DUALGUN_A03_0101_name_2", valid=False),
Data("IW_MU_S_DUALGUN_A03_0101_name_3", valid=False),
Data("IW_MU_S_DUALGUN_A05_1001_name_1", valid=False),
Data("IW_MU_S_DUALGUN_A05_1001_name_2", valid=False),
Data("IW_MU_S_DUALGUN_A05_1001_name_3", valid=False),
Data("Rugged Sidearm_1"),
Data("Rugged Sidearm_2"),
Data("Rugged Sidearm_3"),
Data("Devastator Sidearm_1"),
Data("Devastator Sidearm_2"),
Data("Devastator Sidearm_3"),
Data("Sparrow Sidearm_1"),
Data("Sparrow Sidearm_2"),
Data("Sparrow Sidearm_3"),
Data("Foxfire Sidearm_1"),
Data("Foxfire Sidearm_2"),
Data("Foxfire Sidearm_3"),
Data("Rectifier Sidearm_1"),
Data("Rectifier Sidearm_2"),
Data("Rectifier Sidearm_3"),
Data("Advanced Storm Dual Guns"),
Data("Worn Soldier Dual Guns"),
Data("Advanced Soldier Dual Guns"),
Data("Worn Warrior Dual Guns"),
Data("Advanced Warrior Dual Guns"),
Data("Worn Ophidian Dual Guns"),
Data("Advanced Ophidian Dual Guns"),
Data("Worn Destroyer Dual Guns"),
Data("Advanced Destroyer Dual Guns"),
Data("Worn Striker Dual Guns"),
Data("Advanced Striker Dual Guns"),
Data("Worn Delta Dual Guns"),
Data("Advanced Storm Dual Guns II"),
Data("Worn Soldier Dual Guns II"),
Data("Advanced Soldier Dual Guns II"),
Data("Worn Warrior Dual Guns II"),
Data("Advanced Warrior Dual Guns II"),
Data("Worn Ophidian Dual Guns II"),
Data("Advanced Ophidian Dual Guns II"),
Data("Worn Destroyer Dual Guns II"),
Data("Advanced Destroyer Dual Guns II"),
Data("Worn Striker Dual Guns II"),
Data("Advanced Striker Dual Guns II"),
Data("Worn Delta Dual Guns II"),
Data("Advanced Storm Gemels"),
Data("Worn Soldier Gemels"),
Data("Advanced Soldier Gemels"),
Data("Worn Warrior Gemels"),
Data("Advanced Warrior Gemels"),
Data("Worn Ophidian Gemels"),
Data("Advanced Ophidian Gemels"),
Data("Worn Destroyer Gemels"),
Data("Advanced Destroyer Gemels"),
Data("Worn Striker Gemels"),
Data("Advanced Striker Gemels"),
Data("Worn Delta Gemels"),
Data("Worn Warrior Pistolia"),
Data("Advanced Warrior Pistolia"),
Data("Worn Ophidian Pistolia"),
Data("Advanced Ophidian Pistolia"),
Data("Worn Destroyer Pistolia"),
Data("Advanced Destroyer Pistolia"),
Data("Worn Striker Pistolia"),
Data("Advanced Striker Pistolia"),
Data("Worn Delta Pistolia"),
Data("Advanced Warrior Dyads"),
Data("Worn Ophidian Dyads"),
Data("Advanced Ophidian Dyads"),
Data("Worn Destroyer Dyads"),
Data("Advanced Destroyer Dyads"),
Data("Worn Striker Dyads"),
Data("Advanced Striker Dyads"),
Data("Worn Delta Dyads"),
Data("Advanced Warrior Dyads III"),
Data("Worn Ophidian Dyads III"),
Data("Advanced Ophidian Dyads III"),
Data("Worn Destroyer Dyads III"),
Data("Advanced Destroyer Dyads III"),
Data("Worn Striker Dyads III"),
Data("Advanced Striker Dyads III"),
Data("Worn Delta Dyads III"),
Data("Advanced Warrior Dyads II"),
Data("Worn Ophidian Dyads II"),
Data("Advanced Ophidian Dyads II"),
Data("Worn Destroyer Dyads II"),
Data("Advanced Destroyer Dyads II"),
Data("Worn Striker Dyads II"),
Data("Advanced Striker Dyads II"),
Data("Worn Delta Dyads II"),
Data("Advanced Warrior Bangbangs"),
Data("Worn Ophidian Bangbangs"),
Data("Advanced Ophidian Bangbangs"),
Data("Worn Destroyer Bangbangs"),
Data("Advanced Destroyer Bangbangs"),
Data("Worn Striker Bangbangs"),
Data("Advanced Striker Bangbangs"),
Data("Worn Delta Bangbangs"),
Data("Advanced Devastator Sidearm"),
Data("Worn Sparrow Sidearm"),
Data("Advanced Sparrow Sidearm"),
Data("Worn Foxfire Sidearm"),
Data("Advanced Foxfire Sidearm"),
Data("Worn Rectifier Sidearm"),
Data("Ultra Cosmic Dual Guns"),
Data("Ultra Nebulan Dual Guns"),
Data("Ultra Cosmic Dual Guns II"),
Data("Ultra Nebulan Dual Guns II"),
Data("Ultra Cosmic Gemels"),
Data("Ultra Nebulan Gemels"),
Data("Ultra Cosmic Pistolia"),
Data("Ultra Nebulan Pistolia"),
Data("Ultra Cosmic Dyads"),
Data("Ultra Nebulan Dyads"),
Data("Ultra Cosmic Dyads III"),
Data("Ultra Nebulan Dyads III"),
Data("Ultra Cosmic Dyads II"),
Data("Ultra Nebulan Dyads II"),
Data("Ultra Cosmic Bangbangs"),
Data("Ultra Nebulan Bangbangs"),
Data("Ultra Virtue Sidearm"),
Data("Ultra Transience Sidearm"),
Data("Storm Raygun_1"),
Data("Storm Raygun_2"),
Data("Storm Raygun_3"),
Data("Soldier Raygun_1"),
Data("Soldier Raygun_2"),
Data("Soldier Raygun_3"),
Data("Warrior Raygun_1"),
Data("Warrior Raygun_2"),
Data("Warrior Raygun_3"),
Data("Ophidian Raygun_1"),
Data("Ophidian Raygun_2"),
Data("Ophidian Raygun_3"),
Data("Destroyer Raygun_1"),
Data("Destroyer Raygun_2"),
Data("Destroyer Raygun_3"),
Data("Striker Raygun_1"),
Data("Striker Raygun_2"),
Data("Striker Raygun_3"),
Data("Delta Raygun_1"),
Data("Delta Raygun_2"),
Data("Delta Raygun_3"),
Data("Storm Lastyr_1"),
Data("Storm Lastyr_2"),
Data("Storm Lastyr_3"),
Data("Soldier Lastyr_1"),
Data("Soldier Lastyr_2"),
Data("Soldier Lastyr_3"),
Data("Warrior Lastyr_1"),
Data("Warrior Lastyr_2"),
Data("Warrior Lastyr_3"),
Data("Ophidian Lastyr_1"),
Data("Ophidian Lastyr_2"),
Data("Ophidian Lastyr_3"),
Data("Destroyer Lastyr_1"),
Data("Destroyer Lastyr_2"),
Data("Destroyer Lastyr_3"),
Data("Striker Lastyr_1"),
Data("Striker Lastyr_2"),
Data("Striker Lastyr_3"),
Data("Delta Lastyr_1"),
Data("Delta Lastyr_2"),
Data("Delta Lastyr_3"),
Data("Storm Lastyr II_1"),
Data("Storm Lastyr II_2"),
Data("Storm Lastyr II_3"),
Data("Soldier Lastyr II_1"),
Data("Soldier Lastyr II_2"),
Data("Soldier Lastyr II_3"),
Data("Warrior Lastyr II_1"),
Data("Warrior Lastyr II_2"),
Data("Warrior Lastyr II_3"),
Data("Ophidian Lastyr II_1"),
Data("Ophidian Lastyr II_2"),
Data("Ophidian Lastyr II_3"),
Data("Destroyer Lastyr II_1"),
Data("Destroyer Lastyr II_2"),
Data("Destroyer Lastyr II_3"),
Data("Striker Lastyr II_1"),
Data("Striker Lastyr II_2"),
Data("Striker Lastyr II_3"),
Data("Delta Lastyr II_1"),
Data("Delta Lastyr II_2"),
Data("Delta Lastyr II_3"),
Data("Storm Lastyr III_1"),
Data("Storm Lastyr III_2"),
Data("Storm Lastyr III_3"),
Data("Soldier Lastyr III_1"),
Data("Soldier Lastyr III_2"),
Data("Soldier Lastyr III_3"),
Data("Warrior Lastyr III_1"),
Data("Warrior Lastyr III_2"),
Data("Warrior Lastyr III_3"),
Data("Ophidian Lastyr III_1"),
Data("Ophidian Lastyr III_2"),
Data("Ophidian Lastyr III_3"),
Data("Destroyer Lastyr III_1"),
Data("Destroyer Lastyr III_2"),
Data("Destroyer Lastyr III_3"),
Data("Striker Lastyr III_1"),
Data("Striker Lastyr III_2"),
Data("Striker Lastyr III_3"),
Data("Delta Lastyr III_1"),
Data("Delta Lastyr III_2"),
Data("Delta Lastyr III_3"),
Data("Storm Radius_1"),
Data("Storm Radius_2"),
Data("Storm Radius_3"),
Data("Soldier Radius_1"),
Data("Soldier Radius_2"),
Data("Soldier Radius_3"),
Data("Warrior Radius_1"),
Data("Warrior Radius_2"),
Data("Warrior Radius_3"),
Data("Ophidian Radius_1"),
Data("Ophidian Radius_2"),
Data("Ophidian Radius_3"),
Data("Destroyer Radius_1"),
Data("Destroyer Radius_2"),
Data("Destroyer Radius_3"),
Data("Striker Radius_1"),
Data("Striker Radius_2"),
Data("Striker Radius_3"),
Data("Delta Radius_1"),
Data("Delta Radius_2"),
Data("Delta Radius_3"),
Data("Storm Radius II_1"),
Data("Storm Radius II_2"),
Data("Storm Radius II_3"),
Data("Soldier Radius II_1"),
Data("Soldier Radius II_2"),
Data("Soldier Radius II_3"),
Data("Warrior Radius II_1"),
Data("Warrior Radius II_2"),
Data("Warrior Radius II_3"),
Data("Ophidian Radius II_1"),
Data("Ophidian Radius II_2"),
Data("Ophidian Radius II_3"),
Data("Destroyer Radius II_1"),
Data("Destroyer Radius II_2"),
Data("Destroyer Radius II_3"),
Data("Striker Radius II_1"),
Data("Striker Radius II_2"),
Data("Striker Radius II_3"),
Data("Delta Radius II_1"),
Data("Delta Radius II_2"),
Data("Delta Radius II_3"),
Data("Storm Strobe_1"),
Data("Storm Strobe_2"),
Data("Storm Strobe_3"),
Data("Soldier Strobe_1"),
Data("Soldier Strobe_2"),
Data("Soldier Strobe_3"),
Data("Warrior Strobe_1"),
Data("Warrior Strobe_2"),
Data("Warrior Strobe_3"),
Data("Ophidian Strobe_1"),
Data("Ophidian Strobe_2"),
Data("Ophidian Strobe_3"),
Data("Destroyer Strobe_1"),
Data("Destroyer Strobe_2"),
Data("Destroyer Strobe_3"),
Data("Striker Strobe_1"),
Data("Striker Strobe_2"),
Data("Striker Strobe_3"),
Data("Delta Strobe_1"),
Data("Delta Strobe_2"),
Data("Delta Strobe_3"),
Data("Storm Faith_1"),
Data("Storm Faith_2"),
Data("Storm Faith_3"),
Data("Soldier Faith_1"),
Data("Soldier Faith_2"),
Data("Soldier Faith_3"),
Data("Warrior Faith_1"),
Data("Warrior Faith_2"),
Data("Warrior Faith_3"),
Data("Ophidian Faith_1"),
Data("Ophidian Faith_2"),
Data("Ophidian Faith_3"),
Data("Destroyer Faith_1"),
Data("Destroyer Faith_2"),
Data("Destroyer Faith_3"),
Data("Striker Faith_1"),
Data("Striker Faith_2"),
Data("Striker Faith_3"),
Data("Delta Faith_1"),
Data("Delta Faith_2"),
Data("Delta Faith_3"),
Data("Advanced Storm Raygun"),
Data("Worn Soldier Raygun"),
Data("Advanced Soldier Raygun"),
Data("Worn Warrior Raygun"),
Data("Advanced Warrior Raygun"),
Data("Worn Ophidian Raygun"),
Data("Advanced Ophidian Raygun"),
Data("Worn Destroyer Raygun"),
Data("Advanced Destroyer Raygun"),
Data("Worn Striker Raygun"),
Data("Advanced Striker Raygun"),
Data("Worn Delta Raygun"),
Data("Advanced Storm Lastyr"),
Data("Worn Soldier Lastyr"),
Data("Advanced Soldier Lastyr"),
Data("Worn Warrior Lastyr"),
Data("Advanced Warrior Lastyr"),
Data("Worn Ophidian Lastyr"),
Data("Advanced Ophidian Lastyr"),
Data("Worn Destroyer Lastyr"),
Data("Advanced Destroyer Lastyr"),
Data("Worn Striker Lastyr"),
Data("Advanced Striker Lastyr"),
Data("Worn Delta Lastyr"),
Data("Advanced Storm Lastyr II"),
Data("Worn Soldier Lastyr II"),
Data("Advanced Soldier Lastyr II"),
Data("Worn Warrior Lastyr II"),
Data("Advanced Warrior Lastyr II"),
Data("Worn Ophidian Lastyr II"),
Data("Advanced Ophidian Lastyr II"),
Data("Worn Destroyer Lastyr II"),
Data("Advanced Destroyer Lastyr II"),
Data("Worn Striker Lastyr II"),
Data("Advanced Striker Lastyr II"),
Data("Worn Delta Lastyr II"),
Data("Advanced Storm Lastyr III"),
Data("Worn Soldier Lastyr III"),
Data("Advanced Soldier Lastyr III"),
Data("Worn Warrior Lastyr III"),
Data("Advanced Warrior Lastyr III"),
Data("Worn Ophidian Lastyr III"),
Data("Advanced Ophidian Lastyr III"),
Data("Worn Destroyer Lastyr III"),
Data("Advanced Destroyer Lastyr III"),
Data("Worn Striker Lastyr III"),
Data("Advanced Striker Lastyr III"),
Data("Worn Delta Lastyr III"),
Data("Worn Warrior Radius"),
Data("Advanced Warrior Radius"),
Data("Worn Ophidian Radius"),
Data("Advanced Ophidian Radius"),
Data("Worn Destroyer Radius"),
Data("Advanced Destroyer Radius"),
Data("Worn Striker Radius"),
Data("Advanced Striker Radius"),
Data("Worn Delta Radius"),
Data("Worn Warrior Radius II"),
Data("Advanced Warrior Radius II"),
Data("Worn Ophidian Radius II"),
Data("Advanced Ophidian Radius II"),
Data("Worn Destroyer Radius II"),
Data("Advanced Destroyer Radius II"),
Data("Worn Striker Radius II"),
Data("Advanced Striker Radius II"),
Data("Worn Delta Radius II"),
Data("Advanced Warrior Strobe"),
Data("Worn Ophidian Strobe"),
Data("Advanced Ophidian Strobe"),
Data("Worn Destroyer Strobe"),
Data("Advanced Destroyer Strobe"),
Data("Worn Striker Strobe"),
Data("Advanced Striker Strobe"),
Data("Worn Delta Strobe"),
Data("Advanced Warrior Faith"),
Data("Worn Ophidian Faith"),
Data("Advanced Ophidian Faith"),
Data("Worn Destroyer Faith"),
Data("Advanced Destroyer Faith"),
Data("Worn Striker Faith"),
Data("Advanced Striker Faith"),
Data("Worn Delta Faith"),
Data("Ultra Cosmic Raygun"),
Data("Ultra Nebulan Raygun"),
Data("Ultra Cosmic Lastyr"),
Data("Ultra Nebulan Lastyr"),
Data("Ultra Cosmic Lastyr II"),
Data("Ultra Nebulan Lastyr II"),
Data("Ultra Cosmic Lastyr III"),
Data("Ultra Nebulan Lastyr III"),
Data("Ultra Cosmic Radius"),
Data("Ultra Nebulan Radius"),
Data("Ultra Cosmic Radius II"),
Data("Ultra Nebulan Radius II"),
Data("Ultra Cosmic Strobe"),
Data("Ultra Nebulan Strobe"),
Data("Ultra Cosmic Faith"),
Data("Ultra Nebulan Faith"),
Data("Storm Machine_1"),
Data("Storm Machine_2"),
Data("Storm Machine_3"),
Data("Soldier Machine_1"),
Data("Soldier Machine_2"),
Data("Soldier Machine_3"),
Data("Warrior Machine_1"),
Data("Warrior Machine_2"),
Data("Warrior Machine_3"),
Data("Ophidian Machine_1"),
Data("Ophidian Machine_2"),
Data("Ophidian Machine_3"),
Data("Destroyer Machine_1"),
Data("Destroyer Machine_2"),
Data("Destroyer Machine_3"),
Data("Striker Machine_1"),
Data("Striker Machine_2"),
Data("Striker Machine_3"),
Data("Delta Machine_1"),
Data("Delta Machine_2"),
Data("Delta Machine_3"),
Data("Storm Machine II_1"),
Data("Storm Machine II_2"),
Data("Storm Machine II_3"),
Data("Soldier Machine II_1"),
Data("Soldier Machine II_2"),
Data("Soldier Machine II_3"),
Data("Warrior Machine II_1"),
Data("Warrior Machine II_2"),
Data("Warrior Machine II_3"),
Data("Ophidian Machine II_1"),
Data("Ophidian Machine II_2"),
Data("Ophidian Machine II_3"),
Data("Destroyer Machine II_1"),
Data("Destroyer Machine II_2"),
Data("Destroyer Machine II_3"),
Data("Striker Machine II_1"),
Data("Striker Machine II_2"),
Data("Striker Machine II_3"),
Data("Delta Machine II_1"),
Data("Delta Machine II_2"),
Data("Delta Machine II_3"),
Data("Storm Repethe_1"),
Data("Storm Repethe_2"),
Data("Storm Repethe_3"),
Data("Soldier Repethe_1"),
Data("Soldier Repethe_2"),
Data("Soldier Repethe_3"),
Data("Warrior Repethe_1"),
Data("Warrior Repethe_2"),
Data("Warrior Repethe_3"),
Data("Ophidian Repethe_1"),
Data("Ophidian Repethe_2"),
Data("Ophidian Repethe_3"),
Data("Destroyer Repethe_1"),
Data("Destroyer Repethe_2"),
Data("Destroyer Repethe_3"),
Data("Striker Repethe_1"),
Data("Striker Repethe_2"),
Data("Striker Repethe_3"),
Data("Delta Repethe_1"),
Data("Delta Repethe_2"),
Data("Delta Repethe_3"),
Data("Storm Grando II_1"),
Data("Storm Grando II_2"),
Data("Storm Grando II_3"),
Data("Soldier Grando II_1"),
Data("Soldier Grando II_2"),
Data("Soldier Grando II_3"),
Data("Warrior Grando II_1"),
Data("Warrior Grando II_2"),
Data("Warrior Grando II_3"),
Data("Ophidian Grando II_1"),
Data("Ophidian Grando II_2"),
Data("Ophidian Grando II_3"),
Data("Destroyer Grando II_1"),
Data("Destroyer Grando II_2"),
Data("Destroyer Grando II_3"),
Data("Striker Grando II_1"),
Data("Striker Grando II_2"),
Data("Striker Grando II_3"),
Data("Delta Grando II_1"),
Data("Delta Grando II_2"),
Data("Delta Grando II_3"),
Data("Storm Grando_1"),
Data("Storm Grando_2"),
Data("Storm Grando_3"),
Data("Soldier Grando_1"),
Data("Soldier Grando_2"),
Data("Soldier Grando_3"),
Data("Warrior Grando_1"),
Data("Warrior Grando_2"),
Data("Warrior Grando_3"),
Data("Ophidian Grando_1"),
Data("Ophidian Grando_2"),
Data("Ophidian Grando_3"),
Data("Destroyer Grando_1"),
Data("Destroyer Grando_2"),
Data("Destroyer Grando_3"),
Data("Striker Grando_1"),
Data("Striker Grando_2"),
Data("Striker Grando_3"),
Data("Delta Grando_1"),
Data("Delta Grando_2"),
Data("Delta Grando_3"),
Data("Storm Crank_1"),
Data("Storm Crank_2"),
Data("Storm Crank_3"),
Data("Soldier Crank_1"),
Data("Soldier Crank_2"),
Data("Soldier Crank_3"),
Data("Warrior Crank_1"),
Data("Warrior Crank_2"),
Data("Warrior Crank_3"),
Data("Ophidian Crank_1"),
Data("Ophidian Crank_2"),
Data("Ophidian Crank_3"),
Data("Destroyer Crank_1"),
Data("Destroyer Crank_2"),
Data("Destroyer Crank_3"),
Data("Striker Crank_1"),
Data("Striker Crank_2"),
Data("Striker Crank_3"),
Data("Delta Crank_1"),
Data("Delta Crank_2"),
Data("Delta Crank_3"),
Data("Storm Ratatatta_1"),
Data("Storm Ratatatta_2"),
Data("Storm Ratatatta_3"),
Data("Soldier Ratatatta_1"),
Data("Soldier Ratatatta_2"),
Data("Soldier Ratatatta_3"),
Data("Warrior Ratatatta_1"),
Data("Warrior Ratatatta_2"),
Data("Warrior Ratatatta_3"),
Data("Ophidian Ratatatta_1"),
Data("Ophidian Ratatatta_2"),
Data("Ophidian Ratatatta_3"),
Data("Destroyer Ratatatta_1"),
Data("Destroyer Ratatatta_2"),
Data("Destroyer Ratatatta_3"),
Data("Striker Ratatatta_1"),
Data("Striker Ratatatta_2"),
Data("Striker Ratatatta_3"),
Data("Delta Ratatatta_1"),
Data("Delta Ratatatta_2"),
Data("Delta Ratatatta_3"),
Data("Storm Ziyse_1"),
Data("Storm Ziyse_2"),
Data("Storm Ziyse_3"),
Data("Soldier Ziyse_1"),
Data("Soldier Ziyse_2"),
Data("Soldier Ziyse_3"),
Data("Warrior Ziyse_1"),
Data("Warrior Ziyse_2"),
Data("Warrior Ziyse_3"),
Data("Ophidian Ziyse_1"),
Data("Ophidian Ziyse_2"),
Data("Ophidian Ziyse_3"),
Data("Destroyer Ziyse_1"),
Data("Destroyer Ziyse_2"),
Data("Destroyer Ziyse_3"),
Data("Striker Ziyse_1"),
Data("Striker Ziyse_2"),
Data("Striker Ziyse_3"),
Data("Delta Ziyse_1"),
Data("Delta Ziyse_2"),
Data("Delta Ziyse_3"),
Data("Advanced Storm Machine"),
Data("Worn Soldier Machine"),
Data("Advanced Soldier Machine"),
Data("Worn Warrior Machine"),
Data("Advanced Warrior Machine"),
Data("Worn Ophidian Machine"),
Data("Advanced Ophidian Machine"),
Data("Worn Destroyer Machine"),
Data("Advanced Destroyer Machine"),
Data("Worn Striker Machine"),
Data("Advanced Striker Machine"),
Data("Worn Delta Machine"),
Data("Advanced Storm Machine II"),
Data("Worn Soldier Machine II"),
Data("Advanced Soldier Machine II"),
Data("Worn Warrior Machine II"),
Data("Advanced Warrior Machine II"),
Data("Worn Ophidian Machine II"),
Data("Advanced Ophidian Machine II"),
Data("Worn Destroyer Machine II"),
Data("Advanced Destroyer Machine II"),
Data("Worn Striker Machine II"),
Data("Advanced Striker Machine II"),
Data("Worn Delta Machine II"),
Data("Advanced Storm Repethe"),
Data("Worn Soldier Repethe"),
Data("Advanced Soldier Repethe"),
Data("Worn Warrior Repethe"),
Data("Advanced Warrior Repethe"),
Data("Worn Ophidian Repethe"),
Data("Advanced Ophidian Repethe"),
Data("Worn Destroyer Repethe"),
Data("Advanced Destroyer Repethe"),
Data("Worn Striker Repethe"),
Data("Advanced Striker Repethe"),
Data("Worn Delta Repethe"),
Data("Worn Warrior Grando II"),
Data("Advanced Warrior Grando II"),
Data("Worn Ophidian Grando II"),
Data("Advanced Ophidian Grando II"),
Data("Worn Destroyer Grando II"),
Data("Advanced Destroyer Grando II"),
Data("Worn Striker Grando II"),
Data("Advanced Striker Grando II"),
Data("Worn Delta Grando II"),
Data("Worn Warrior Grando"),
Data("Advanced Warrior Grando"),
Data("Worn Ophidian Grando"),
Data("Advanced Ophidian Grando"),
Data("Worn Destroyer Grando"),
Data("Advanced Destroyer Grando"),
Data("Worn Striker Grando"),
Data("Advanced Striker Grando"),
Data("Worn Delta Grando"),
Data("Advanced Warrior Crank"),
Data("Worn Ophidian Crank"),
Data("Advanced Ophidian Crank"),
Data("Worn Destroyer Crank"),
Data("Advanced Destroyer Crank"),
Data("Worn Striker Crank"),
Data("Advanced Striker Crank"),
Data("Worn Delta Crank"),
Data("Advanced Warrior Ratatatta"),
Data("Worn Ophidian Ratatatta"),
Data("Advanced Ophidian Ratatatta"),
Data("Worn Destroyer Ratatatta"),
Data("Advanced Destroyer Ratatatta"),
Data("Worn Striker Ratatatta"),
Data("Advanced Striker Ratatatta"),
Data("Worn Delta Ratatatta"),
Data("Worn Ophidian Ziyse"),
Data("Advanced Ophidian Ziyse"),
Data("Worn Destroyer Ziyse"),
Data("Advanced Destroyer Ziyse"),
Data("Worn Striker Ziyse"),
Data("Advanced Striker Ziyse"),
Data("Worn Delta Ziyse"),
Data("Ultra Cosmic Machine"),
Data("Ultra Nebulan Machine"),
Data("Ultra Cosmic Machine II"),
Data("Ultra Nebulan Machine II"),
Data("Ultra Cosmic Repethe"),
Data("Ultra Nebulan Repethe"),
Data("Ultra Cosmic Grando II"),
Data("Ultra Nebulan Grando II"),
Data("Ultra Cosmic Grando"),
Data("Ultra Nebulan Grando"),
Data("Ultra Cosmic Crank"),
Data("Ultra Nebulan Crank"),
Data("Ultra Cosmic Ratatatta"),
Data("Ultra Nebulan Ratatatta"),
Data("Ultra Cosmic Ziyse"),
Data("Ultra Nebulan Ziyse"),
Data("Storm Sniper Rifle_1"),
Data("Storm Sniper Rifle_2"),
Data("Storm Sniper Rifle_3"),
Data("Soldier Sniper Rifle_1"),
Data("Soldier Sniper Rifle_2"),
Data("Soldier Sniper Rifle_3"),
Data("Warrior Sniper Rifle_1"),
Data("Warrior Sniper Rifle_2"),
Data("Warrior Sniper Rifle_3"),
Data("Ophidian Sniper Rifle_1"),
Data("Ophidian Sniper Rifle_2"),
Data("Ophidian Sniper Rifle_3"),
Data("Destroyer Sniper Rifle_1"),
Data("Destroyer Sniper Rifle_2"),
Data("Destroyer Sniper Rifle_3"),
Data("Striker Sniper Rifle_1"),
Data("Striker Sniper Rifle_2"),
Data("Striker Sniper Rifle_3"),
Data("Delta Sniper Rifle_1"),
Data("Delta Sniper Rifle_2"),
Data("Delta Sniper Rifle_3"),
Data("Storm Sniper Rifle II_1"),
Data("Storm Sniper Rifle II_2"),
Data("Storm Sniper Rifle II_3"),
Data("Soldier Sniper Rifle II_1"),
Data("Soldier Sniper Rifle II_2"),
Data("Soldier Sniper Rifle II_3"),
Data("Warrior Sniper Rifle II_1"),
Data("Warrior Sniper Rifle II_2"),
Data("Warrior Sniper Rifle II_3"),
Data("Ophidian Sniper Rifle II_1"),
Data("Ophidian Sniper Rifle II_2"),
Data("Ophidian Sniper Rifle II_3"),
Data("Destroyer Sniper Rifle II_1"),
Data("Destroyer Sniper Rifle II_2"),
Data("Destroyer Sniper Rifle II_3"),
Data("Striker Sniper Rifle II_1"),
Data("Striker Sniper Rifle II_2"),
Data("Striker Sniper Rifle II_3"),
Data("Delta Sniper Rifle II_1"),
Data("Delta Sniper Rifle II_2"),
Data("Delta Sniper Rifle II_3"),
Data("Storm Retic_1"),
Data("Storm Retic_2"),
Data("Storm Retic_3"),
Data("Soldier Retic_1"),
Data("Soldier Retic_2"),
Data("Soldier Retic_3"),
Data("Warrior Retic_1"),
Data("Warrior Retic_2"),
Data("Warrior Retic_3"),
Data("Ophidian Retic_1"),
Data("Ophidian Retic_2"),
Data("Ophidian Retic_3"),
Data("Destroyer Retic_1"),
Data("Destroyer Retic_2"),
Data("Destroyer Retic_3"),
Data("Striker Retic_1"),
Data("Striker Retic_2"),
Data("Striker Retic_3"),
Data("Delta Retic_1"),
Data("Delta Retic_2"),
Data("Delta Retic_3"),
Data("Storm Sicarius_1"),
Data("Storm Sicarius_2"),
Data("Storm Sicarius_3"),
Data("Soldier Sicarius_1"),
Data("Soldier Sicarius_2"),
Data("Soldier Sicarius_3"),
Data("Warrior Sicarius_1"),
Data("Warrior Sicarius_2"),
Data("Warrior Sicarius_3"),
Data("Ophidian Sicarius_1"),
Data("Ophidian Sicarius_2"),
Data("Ophidian Sicarius_3"),
Data("Destroyer Sicarius_1"),
Data("Destroyer Sicarius_2"),
Data("Destroyer Sicarius_3"),
Data("Striker Sicarius_1"),
Data("Striker Sicarius_2"),
Data("Striker Sicarius_3"),
Data("Delta Sicarius_1"),
Data("Delta Sicarius_2"),
Data("Delta Sicarius_3"),
Data("Storm Trigger_1"),
Data("Storm Trigger_2"),
Data("Storm Trigger_3"),
Data("Soldier Trigger_1"),
Data("Soldier Trigger_2"),
Data("Soldier Trigger_3"),
Data("Warrior Trigger_1"),
Data("Warrior Trigger_2"),
Data("Warrior Trigger_3"),
Data("Ophidian Trigger_1"),
Data("Ophidian Trigger_2"),
Data("Ophidian Trigger_3"),
Data("Destroyer Trigger_1"),
Data("Destroyer Trigger_2"),
Data("Destroyer Trigger_3"),
Data("Striker Trigger_1"),
Data("Striker Trigger_2"),
Data("Striker Trigger_3"),
Data("Delta Trigger_1"),
Data("Delta Trigger_2"),
Data("Delta Trigger_3"),
Data("Storm Thwipper_1"),
Data("Storm Thwipper_2"),
Data("Storm Thwipper_3"),
Data("Soldier Thwipper_1"),
Data("Soldier Thwipper_2"),
Data("Soldier Thwipper_3"),
Data("Warrior Thwipper_1"),
Data("Warrior Thwipper_2"),
Data("Warrior Thwipper_3"),
Data("Ophidian Thwipper_1"),
Data("Ophidian Thwipper_2"),
Data("Ophidian Thwipper_3"),
Data("Destroyer Thwipper_1"),
Data("Destroyer Thwipper_2"),
Data("Destroyer Thwipper_3"),
Data("Striker Thwipper_1"),
Data("Striker Thwipper_2"),
Data("Striker Thwipper_3"),
Data("Delta Thwipper_1"),
Data("Delta Thwipper_2"),
Data("Delta Thwipper_3"),
Data("IW_MU_S_SNIPER_A04_0101_name_1", valid=False),
Data("IW_MU_S_SNIPER_A04_0101_name_2", valid=False),
Data("IW_MU_S_SNIPER_A04_0101_name_3", valid=False),
Data("IW_MU_S_SNIPER_A05_1001_name_1", valid=False),
Data("IW_MU_S_SNIPER_A05_1001_name_2", valid=False),
Data("IW_MU_S_SNIPER_A05_1001_name_3", valid=False),
Data("Rugged Deadsight_1"),
Data("Rugged Deadsight_2"),
Data("Rugged Deadsight_3"),
Data("Devastator Deadsight_1"),
Data("Devastator Deadsight_2"),
Data("Devastator Deadsight_3"),
Data("Sparrow Deadsight_1"),
Data("Sparrow Deadsight_2"),
Data("Sparrow Deadsight_3"),
Data("Foxfire Deadsight_1"),
Data("Foxfire Deadsight_2"),
Data("Foxfire Deadsight_3"),
Data("Rectifier Deadsight_1"),
Data("Rectifier Deadsight_2"),
Data("Rectifier Deadsight_3"),
Data("IW_MU_S_SNIPER_B05_0101_name_1", valid=False),
Data("IW_MU_S_SNIPER_B05_0101_name_2", valid=False),
Data("IW_MU_S_SNIPER_B05_0101_name_3", valid=False),
Data("IW_MU_S_SNIPER_B07_1001_name_1", valid=False),
Data("IW_MU_S_SNIPER_B07_1001_name_2", valid=False),
Data("IW_MU_S_SNIPER_B07_1001_name_3", valid=False),
Data("Rugged Deadsight II_1"),
Data("Rugged Deadsight II_2"),
Data("Rugged Deadsight II_3"),
Data("Devastator Deadsight II_1"),
Data("Devastator Deadsight II_2"),
Data("Devastator Deadsight II_3"),
Data("Sparrow Deadsight II_1"),
Data("Sparrow Deadsight II_2"),
Data("Sparrow Deadsight II_3"),
Data("Foxfire Deadsight II_1"),
Data("Foxfire Deadsight II_2"),
Data("Foxfire Deadsight II_3"),
Data("Rectifier Deadsight II_1"),
Data("Rectifier Deadsight II_2"),
Data("Rectifier Deadsight II_3"),
Data("Advanced Storm Sniper Rifle"),
Data("Worn Soldier Sniper Rifle"),
Data("Advanced Soldier Sniper Rifle"),
Data("Worn Warrior Sniper Rifle"),
Data("Advanced Warrior Sniper Rifle"),
Data("Worn Ophidian Sniper Rifle"),
Data("Advanced Ophidian Sniper Rifle"),
Data("Worn Destroyer Sniper Rifle"),
Data("Advanced Destroyer Sniper Rifle"),
Data("Worn Striker Sniper Rifle"),
Data("Advanced Striker Sniper Rifle"),
Data("Worn Delta Sniper Rifle"),
Data("Advanced Storm Sniper Rifle II"),
Data("Worn Soldier Sniper Rifle II"),
Data("Advanced Soldier Sniper Rifle II"),
Data("Worn Warrior Sniper Rifle II"),
Data("Advanced Warrior Sniper Rifle II"),
Data("Worn Ophidian Sniper Rifle II"),
Data("Advanced Ophidian Sniper Rifle II"),
Data("Worn Destroyer Sniper Rifle II"),
Data("Advanced Destroyer Sniper Rifle II"),
Data("Worn Striker Sniper Rifle II"),
Data("Advanced Striker Sniper Rifle II"),
Data("Worn Delta Sniper Rifle II"),
Data("Advanced Storm Retic"),
Data("Worn Soldier Retic"),
Data("Advanced Soldier Retic"),
Data("Worn Warrior Retic"),
Data("Advanced Warrior Retic"),
Data("Worn Ophidian Retic"),
Data("Advanced Ophidian Retic"),
Data("Worn Destroyer Retic"),
Data("Advanced Destroyer Retic"),
Data("Worn Striker Retic"),
Data("Advanced Striker Retic"),
Data("Worn Delta Retic"),
Data("Worn Warrior Sicarius"),
Data("Advanced Warrior Sicarius"),
Data("Worn Ophidian Sicarius"),
Data("Advanced Ophidian Sicarius"),
Data("Worn Destroyer Sicarius"),
Data("Advanced Destroyer Sicarius"),
Data("Worn Striker Sicarius"),
Data("Advanced Striker Sicarius"),
Data("Worn Delta Sicarius"),
Data("Advanced Warrior Trigger"),
Data("Worn Ophidian Trigger"),
Data("Advanced Ophidian Trigger"),
Data("Worn Destroyer Trigger"),
Data("Advanced Destroyer Trigger"),
Data("Worn Striker Trigger"),
Data("Advanced Striker Trigger"),
Data("Worn Delta Trigger"),
Data("Advanced Warrior Thwipper"),
Data("Worn Ophidian Thwipper"),
Data("Advanced Ophidian Thwipper"),
Data("Worn Destroyer Thwipper"),
Data("Advanced Destroyer Thwipper"),
Data("Worn Striker Thwipper"),
Data("Advanced Striker Thwipper"),
Data("Worn Delta Thwipper"),
Data("Advanced Devastator Deadsight"),
Data("Worn Sparrow Deadsight"),
Data("Advanced Sparrow Deadsight"),
Data("Worn Foxfire Deadsight"),
Data("Advanced Foxfire Deadsight"),
Data("Worn Rectifier Deadsight"),
Data("Advanced Devastator Deadsight II"),
Data("Worn Sparrow Deadsight II"),
Data("Advanced Sparrow Deadsight II"),
Data("Worn Foxfire Deadsight II"),
Data("Advanced Foxfire Deadsight II"),
Data("Worn Rectifier Deadsight II"),
Data("Ultra Cosmic Sniper Rifle"),
Data("Ultra Nebulan Sniper Rifle"),
Data("Ultra Cosmic Sniper Rifle II"),
Data("Ultra Nebulan Sniper Rifle II"),
Data("Ultra Cosmic Retic"),
Data("Ultra Nebulan Retic"),
Data("Ultra Cosmic Sicarius"),
Data("Ultra Nebulan Sicarius"),
Data("Ultra Cosmic Trigger"),
Data("Ultra Nebulan Trigger"),
Data("Ultra Cosmic Thwipper"),
Data("Ultra Nebulan Thwipper"),
Data("Ultra Virtue Deadsight"),
Data("Ultra Transience Deadsight"),
Data("Ultra Virtue Deadsight II"),
Data("Ultra Transience Deadsight II"),
Data("Storm Launchers_1"),
Data("Storm Launchers_2"),
Data("Storm Launchers_3"),
Data("Soldier Launchers_1"),
Data("Soldier Launchers_2"),
Data("Soldier Launchers_3"),
Data("Warrior Launchers_1"),
Data("Warrior Launchers_2"),
Data("Warrior Launchers_3"),
Data("Ophidian Launchers_1"),
Data("Ophidian Launchers_2"),
Data("Ophidian Launchers_3"),
Data("Destroyer Launchers_1"),
Data("Destroyer Launchers_2"),
Data("Destroyer Launchers_3"),
Data("Striker Launchers_1"),
Data("Striker Launchers_2"),
Data("Striker Launchers_3"),
Data("Delta Launchers_1"),
Data("Delta Launchers_2"),
Data("Delta Launchers_3"),
Data("Storm Psylans_1"),
Data("Storm Psylans_2"),
Data("Storm Psylans_3"),
Data("Soldier Psylans_1"),
Data("Soldier Psylans_2"),
Data("Soldier Psylans_3"),
Data("Warrior Psylans_1"),
Data("Warrior Psylans_2"),
Data("Warrior Psylans_3"),
Data("Ophidian Psylans_1"),
Data("Ophidian Psylans_2"),
Data("Ophidian Psylans_3"),
Data("Destroyer Psylans_1"),
Data("Destroyer Psylans_2"),
Data("Destroyer Psylans_3"),
Data("Striker Psylans_1"),
Data("Striker Psylans_2"),
Data("Striker Psylans_3"),
Data("Delta Psylans_1"),
Data("Delta Psylans_2"),
Data("Delta Psylans_3"),
Data("Storm Ruina_1"),
Data("Storm Ruina_2"),
Data("Storm Ruina_3"),
Data("Soldier Ruina_1"),
Data("Soldier Ruina_2"),
Data("Soldier Ruina_3"),
Data("Warrior Ruina_1"),
Data("Warrior Ruina_2"),
Data("Warrior Ruina_3"),
Data("Ophidian Ruina_1"),
Data("Ophidian Ruina_2"),
Data("Ophidian Ruina_3"),
Data("Destroyer Ruina_1"),
Data("Destroyer Ruina_2"),
Data("Destroyer Ruina_3"),
Data("Striker Ruina_1"),
Data("Striker Ruina_2"),
Data("Striker Ruina_3"),
Data("Delta Ruina_1"),
Data("Delta Ruina_2"),
Data("Delta Ruina_3"),
Data("Storm Ruina II_1"),
Data("Storm Ruina II_2"),
Data("Storm Ruina II_3"),
Data("Soldier Ruina II_1"),
Data("Soldier Ruina II_2"),
Data("Soldier Ruina II_3"),
Data("Warrior Ruina II_1"),
Data("Warrior Ruina II_2"),
Data("Warrior Ruina II_3"),
Data("Ophidian Ruina II_1"),
Data("Ophidian Ruina II_2"),
Data("Ophidian Ruina II_3"),
Data("Destroyer Ruina II_1"),
Data("Destroyer Ruina II_2"),
Data("Destroyer Ruina II_3"),
Data("Striker Ruina II_1"),
Data("Striker Ruina II_2"),
Data("Striker Ruina II_3"),
Data("Delta Ruina II_1"),
Data("Delta Ruina II_2"),
Data("Delta Ruina II_3"),
Data("Storm Ruina III_1"),
Data("Storm Ruina III_2"),
Data("Storm Ruina III_3"),
Data("Soldier Ruina III_1"),
Data("Soldier Ruina III_2"),
Data("Soldier Ruina III_3"),
Data("Warrior Ruina III_1"),
Data("Warrior Ruina III_2"),
Data("Warrior Ruina III_3"),
Data("Ophidian Ruina III_1"),
Data("Ophidian Ruina III_2"),
Data("Ophidian Ruina III_3"),
Data("Destroyer Ruina III_1"),
Data("Destroyer Ruina III_2"),
Data("Destroyer Ruina III_3"),
Data("Striker Ruina III_1"),
Data("Striker Ruina III_2"),
Data("Striker Ruina III_3"),
Data("Delta Ruina III_1"),
Data("Delta Ruina III_2"),
Data("Delta Ruina III_3"),
Data("Storm Saboteurs_1"),
Data("Storm Saboteurs_2"),
Data("Storm Saboteurs_3"),
Data("Soldier Saboteurs_1"),
Data("Soldier Saboteurs_2"),
Data("Soldier Saboteurs_3"),
Data("Warrior Saboteurs_1"),
Data("Warrior Saboteurs_2"),
Data("Warrior Saboteurs_3"),
Data("Ophidian Saboteurs_1"),
Data("Ophidian Saboteurs_2"),
Data("Ophidian Saboteurs_3"),
Data("Destroyer Saboteurs_1"),
Data("Destroyer Saboteurs_2"),
Data("Destroyer Saboteurs_3"),
Data("Striker Saboteurs_1"),
Data("Striker Saboteurs_2"),
Data("Striker Saboteurs_3"),
Data("Delta Saboteurs_1"),
Data("Delta Saboteurs_2"),
Data("Delta Saboteurs_3"),
Data("Storm Fwooshers_1"),
Data("Storm Fwooshers_2"),
Data("Storm Fwooshers_3"),
Data("Soldier Fwooshers_1"),
Data("Soldier Fwooshers_2"),
Data("Soldier Fwooshers_3"),
Data("Warrior Fwooshers_1"),
Data("Warrior Fwooshers_2"),
Data("Warrior Fwooshers_3"),
Data("Ophidian Fwooshers_1"),
Data("Ophidian Fwooshers_2"),
Data("Ophidian Fwooshers_3"),
Data("Destroyer Fwooshers_1"),
Data("Destroyer Fwooshers_2"),
Data("Destroyer Fwooshers_3"),
Data("Striker Fwooshers_1"),
Data("Striker Fwooshers_2"),
Data("Striker Fwooshers_3"),
Data("Delta Fwooshers_1"),
Data("Delta Fwooshers_2"),
Data("Delta Fwooshers_3"),
Data("Storm Zorcyses_1"),
Data("Storm Zorcyses_2"),
Data("Storm Zorcyses_3"),
Data("Soldier Zorcyses_1"),
Data("Soldier Zorcyses_2"),
Data("Soldier Zorcyses_3"),
Data("Warrior Zorcyses_1"),
Data("Warrior Zorcyses_2"),
Data("Warrior Zorcyses_3"),
Data("Ophidian Zorcyses_1"),
Data("Ophidian Zorcyses_2"),
Data("Ophidian Zorcyses_3"),
Data("Destroyer Zorcyses_1"),
Data("Destroyer Zorcyses_2"),
Data("Destroyer Zorcyses_3"),
Data("Striker Zorcyses_1"),
Data("Striker Zorcyses_2"),
Data("Striker Zorcyses_3"),
Data("Delta Zorcyses_1"),
Data("Delta Zorcyses_2"),
Data("Delta Zorcyses_3"),
Data("Advanced Storm Launchers"),
Data("Worn Soldier Launchers"),
Data("Advanced Soldier Launchers"),
Data("Worn Warrior Launchers"),
Data("Advanced Warrior Launchers"),
Data("Worn Ophidian Launchers"),
Data("Advanced Ophidian Launchers"),
Data("Worn Destroyer Launchers"),
Data("Advanced Destroyer Launchers"),
Data("Worn Striker Launchers"),
Data("Advanced Striker Launchers"),
Data("Worn Delta Launchers"),
Data("Advanced Storm Psylans"),
Data("Worn Soldier Psylans"),
Data("Advanced Soldier Psylans"),
Data("Worn Warrior Psylans"),
Data("Advanced Warrior Psylans"),
Data("Worn Ophidian Psylans"),
Data("Advanced Ophidian Psylans"),
Data("Worn Destroyer Psylans"),
Data("Advanced Destroyer Psylans"),
Data("Worn Striker Psylans"),
Data("Advanced Striker Psylans"),
Data("Worn Delta Psylans"),
Data("Worn Warrior Ruina"),
Data("Advanced Warrior Ruina"),
Data("Worn Ophidian Ruina"),
Data("Advanced Ophidian Ruina"),
Data("Worn Destroyer Ruina"),
Data("Advanced Destroyer Ruina"),
Data("Worn Striker Ruina"),
Data("Advanced Striker Ruina"),
Data("Worn Delta Ruina"),
Data("Worn Warrior Ruina II"),
Data("Advanced Warrior Ruina II"),
Data("Worn Ophidian Ruina II"),
Data("Advanced Ophidian Ruina II"),
Data("Worn Destroyer Ruina II"),
Data("Advanced Destroyer Ruina II"),
Data("Worn Striker Ruina II"),
Data("Advanced Striker Ruina II"),
Data("Worn Delta Ruina II"),
Data("Worn Warrior Ruina III"),
Data("Advanced Warrior Ruina III"),
Data("Worn Ophidian Ruina III"),
Data("Advanced Ophidian Ruina III"),
Data("Worn Destroyer Ruina III"),
Data("Advanced Destroyer Ruina III"),
Data("Worn Striker Ruina III"),
Data("Advanced Striker Ruina III"),
Data("Worn Delta Ruina III"),
Data("Advanced Warrior Saboteurs"),
Data("Worn Ophidian Saboteurs"),
Data("Advanced Ophidian Saboteurs"),
Data("Worn Destroyer Saboteurs"),
Data("Advanced Destroyer Saboteurs"),
Data("Worn Striker Saboteurs"),
Data("Advanced Striker Saboteurs"),
Data("Worn Delta Saboteurs"),
Data("Advanced Warrior Fwooshers"),
Data("Worn Ophidian Fwooshers"),
Data("Advanced Ophidian Fwooshers"),
Data("Worn Destroyer Fwooshers"),
Data("Advanced Destroyer Fwooshers"),
Data("Worn Striker Fwooshers"),
Data("Advanced Striker Fwooshers"),
Data("Worn Delta Fwooshers"),
Data("Worn Ophidian Zorcyses"),
Data("Advanced Ophidian Zorcyses"),
Data("Worn Destroyer Zorcyses"),
Data("Advanced Destroyer Zorcyses"),
Data("Worn Striker Zorcyses"),
Data("Advanced Striker Zorcyses"),
Data("Worn Delta Zorcyses"),
Data("Ultra Cosmic Launchers"),
Data("Ultra Nebulan Launchers"),
Data("Ultra Cosmic Psylans"),
Data("Ultra Nebulan Psylans"),
Data("Ultra Cosmic Ruina"),
Data("Ultra Nebulan Ruina"),
Data("Ultra Cosmic Ruina II"),
Data("Ultra Nebulan Ruina II"),
Data("Ultra Cosmic Ruina III"),
Data("Ultra Nebulan Ruina III"),
Data("Ultra Cosmic Saboteurs"),
Data("Ultra Nebulan Saboteurs"),
Data("Ultra Cosmic Fwooshers"),
Data("Ultra Nebulan Fwooshers"),
Data("Ultra Cosmic Zorcyses"),
Data("Ultra Nebulan Zorcyses"),
Data("Warrior Bliss_1"),
Data("Warrior Bliss_2"),
Data("Warrior Bliss_3"),
Data("Ophidian Bliss_1"),
Data("Ophidian Bliss_2"),
Data("Ophidian Bliss_3"),
Data("Destroyer Bliss_1"),
Data("Destroyer Bliss_2"),
Data("Destroyer Bliss_3"),
Data("Striker Bliss_1"),
Data("Striker Bliss_2"),
Data("Striker Bliss_3"),
Data("Delta Bliss_1"),
Data("Delta Bliss_2"),
Data("Delta Bliss_3"),
Data("Advanced Warrior Bliss"),
Data("Worn Ophidian Bliss"),
Data("Advanced Ophidian Bliss"),
Data("Worn Destroyer Bliss"),
Data("Advanced Destroyer Bliss"),
Data("Worn Striker Bliss"),
Data("Advanced Striker Bliss"),
Data("Worn Delta Bliss"),
Data("Cosmic Bliss"),
Data("Nebulan Bliss"),
Data("Masterstroke Glaive"),
Data("Masterstroke Glaive II"),
Data("Original Twins"),
Data("Original Watxes"),
Data("Masterstroke Edges II"),
Data("Masterstroke Edges"),
Data("Original Pokepoke"),
Data("Original Iyst"),
Data("Original Iyst II"),
Data("Original Haven"),
Data("Original Haven II"),
Data("Original Thudclang"),
Data("Original Bolide"),
Data("Original Jyth"),
Data("Masterstroke Lance"),
Data("Masterstroke Lightblade"),
Data("Masterstroke Lightblade II"),
Data("Original Assailer"),
Data("Masterstroke Raidrifle"),
Data("Original Dyads"),
Data("Original Dyads III"),
Data("Original Dyads II"),
Data("Original Bangbangs"),
Data("Masterstroke Sidearm"),
Data("Original Strobe"),
Data("Original Crank"),
Data("Original Ratatatta"),
Data("Original Ziyse"),
Data("Original Trigger"),
Data("Original Thwipper"),
Data("Masterstroke Deadsight"),
Data("Masterstroke Deadsight II"),
Data("Original Saboteurs"),
Data("Original Fwooshers"),
Data("Original Zorcyses"),
Data("Archetype Sword"),
Data("Archetype Slair II"),
Data("Archetype Sword II"),
Data("Archetype Blades"),
Data("Archetype Ralzes"),
Data("Archetype Blades II"),
Data("Archetype Knife III"),
Data("Archetype Riv"),
Data("Archetype Knife II"),
Data("Archetype Paive"),
Data("Archetype Shield"),
Data("Advanced Archetype Paive"),
Data("Archetype Spear"),
Data("Archetype Parce"),
Data("Archetype Spear II"),
Data("Archetype Fulge"),
Data("Archetype Saber"),
Data("Archetype Fulge II"),
Data("Archetype Assault Rifle III"),
Data("Archetype Avagar"),
Data("Archetype Assault Rifle II"),
Data("Archetype Dual Guns"),
Data("Archetype Gemels"),
Data("Archetype Dual Guns II"),
Data("Archetype Lastyr II"),
Data("Archetype Raygun"),
Data("Archetype Lastyr III"),
Data("Archetype Machine"),
Data("Archetype Repethe"),
Data("Archetype Machine II"),
Data("Archetype Sniper Rifle"),
Data("Archetype Retic"),
Data("Archetype Sniper Rifle II"),
Data("Archetype Psylans"),
Data("Archetype Launchers"),
Data("Advanced Archetype Psylans"),
Data("Signature Glaive: Fledgling"),
Data("Signature Glaive: Four Virtues"),
Data("Ethereal Glaive: Helldragon"),
Data("Bewitched Glaive: Blood Dance"),
Data("Signature Glaive: Allegiance"),
Data("Mighty Glaive: Galaxy Chief"),
Data("Bewitched Glaive: Receding Rust"),
Data("Legendary Nopopopopon"),
Data("Trial Knife"),
Data("Trial Assault Rifle"),
Data("Trial Sword"),
Data("Titanium Knife_4"),
Data("Advanced Soldier Assault Rifle_2"),
]
