from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/BTL_SkillClass.html
# flake8: noqa
skills_data: list[Data] = [
Data("Steel Flesh"),
Data("Unwavering Courage"),
Data("Flame Trigger"),
Data("Mighty Muscle"),
Data("Combat Presence"),
Data("Dismantler"),
Data("Agile Gunslinger"),
Data("Steady Hand"),
Data("Boosted Bullets"),
Data("Background Noise"),
Data("Combo Gunner"),
Data("Third Eye"),
Data("Master Edge"),
Data("Aura Burst"),
Data("Inner Search"),
Data("Beam Boost"),
Data("Beam Guard"),
Data("Buff Heal"),
Data("Healing Touch"),
Data("High Tension"),
Data("CQC Master"),
Data("Auto Melee Boost"),
Data("Iron Knuckle"),
Data("Healing Aura"),
Data("Weapon Guard"),
Data("Blazing Auto"),
Data("Theroid Slayer"),
Data("Yamato Spirit"),
Data("Thermal Shield"),
Data("Topple Topper"),
Data("Shield Screen"),
Data("Rising Renewal"),
Data("Long Topple"),
Data("Trauma Tension"),
Data("Dirty Fighter"),
Data("Stand Strong"),
Data("Deep Fang"),
Data("Mortal Enemy"),
Data("Trigger Happy"),
Data("Lifeline"),
Data("Mindscape"),
Data("Hellhound"),
Data("Killshot"),
Data("Electric Guard"),
Data("Electric Boost"),
Data("Knock 'n' Shock"),
Data("Fleet Feet"),
Data("Piscinoid Slayer"),
Data("Beauty Sleep"),
Data("Brain Wall"),
Data("Gentle Approach"),
Data("King's Decree"),
Data("Extra Armor"),
Data("Feather Touch"),
Data("Unpleasant Dream"),
Data("Core Crusher"),
Data("Ether Boost"),
Data("Mechanoid Slayer"),
Data("Knight's Soul"),
Data("Aura Assault"),
Data("Buff Extender"),
Data("Supreme Sword"),
Data("Conflagrant Edge"),
Data("Aggro Boost"),
Data("Fortified Flesh"),
Data("Grand Procession"),
Data("Machine Gunner"),
Data("Heatseeker"),
Data("Double Spike"),
Data("Double Reflect"),
Data("Night Vision"),
Data("Zero Lapse"),
Data("Red Zone"),
Data("Crisis Catalyst"),
Data("Blood Carnival"),
Data("Phantom Counter"),
Data("Long Shot"),
Data("Unstoppable"),
Data("Quick Reload"),
Data("Conductive Strike"),
Data("Electric Flesh"),
Data("TP Overdrive"),
Data("Ether Guard"),
Data("Gravity Boost"),
Data("Well-Weathered"),
Data("Appendage Erosion"),
Data("Resistant Flesh"),
Data("Tactical Analyst"),
Data("King's Boon"),
Data("Secondary Accelerator"),
Data("Gravity Guard"),
Data("Fast Forward"),
Data("Stellar Entry"),
Data("Synchrony"),
]