from ..Locations import Loc as Data

#https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html
# flake8: noqa
locations_data: list[Data] = [
Data("Barracks Interior"),
Data("Interior"),
Data("West Gate"),
Data("Central Industrial District"),
Data("Integrated Production Plant"),
Data("Outfitters Test Hangar"),
Data("Repenta Diner"),
Data("Professor B's Lab"),
Data("West Melville Street"),
Data("Central Melville Street"),
Data("East Melville Street"),
Data("Barista Court"),
Data("North Founders Street"),
Data("Nopon Bazaar"),
Data("Deck"),
Data("Starboard"),
Data("Port Side"),
Data("Water Purification Plant"),
Data("Deliverance Park"),
Data("Cathedral"),
Data("Sports Complex"),
Data("Ishmael Hills"),
Data("Division Drive"),
Data("Armory Alley"),
Data("Yardley's Hideaway"),
Data("East Gate"),
Data("BLADE Tower"),
Data("BLADE Concourse"),
Data("BLADE Barracks"),
Data("Mimeosome Maintenance Center"),
Data("Hangar"),
Data("Restricted Hangar Entrance"),
Data("Bedrock Hold"),
Data("Stonelattice Cavern"),
Data("Greater Gemini Bridge"),
Data("Castaway Cavern"),
Data("Stickstone Rise"),
Data("Lesser Gemini Bridge"),
Data("Plundered Ruin"),
Data("Unicorn Rock"),
Data("Turtle Nest"),
Data("Molten Hollow"),
Data("Bedrock Hold Approach"),
Data("Biahno River"),
Data("Green Threshold"),
Data("Headwater Cavern"),
Data("Headwater Summit"),
Data("Headwater Cliff"),
Data("Biahno Water-Purification Plant"),
Data("Biahno Lake"),
Data("Fallshorn Isle"),
Data("Grieving Plains"),
Data("Biahno Grassland"),
Data("Drop Shaft"),
Data("Silent Mire"),
Data("Seaswept Base"),
Data("Wonderment Bluff"),
Data("Sickle Rock Rise"),
Data("Roof Rock"),
Data("Janpath Lake"),
Data("La Mancha"),
Data("North Janpath Plain"),
Data("Arendt Bridge"),
Data("Tallpach Peak"),
Data("Beasts' Lair"),
Data("Northpointe Cove"),
Data("Northpointe Beach"),
Data("East Janpath Plain"),
Data("South Janpath Plain"),
Data("West Janpath Plain"),
Data("Cliffside Beach"),
Data("East Gate Plain"),
Data("West Gate Plain"),
Data("Talon Rock Prominence"),
Data("Talon Rock Third Terrane"),
Data("Talon Rock Second Terrane"),
Data("Sayram Northeast Plain"),
Data("Shadow Rise"),
Data("Biahno Hills"),
Data("Starfall Basin"),
Data("Rock Cavern"),
Data("Seaswept Rise"),
Data("Sayram Lake"),
Data("Talon Rock Summit"),
Data("FN Site 101"),
Data("FN Site 102"),
Data("FN Site 103"),
Data("FN Site 104"),
Data("FN Site 106"),
Data("Seaswept Ridge"),
Data("FN Site 108"),
Data("FN Site 107"),
Data("FN Site 109"),
Data("FN Site 110"),
Data("FN Site 111"),
Data("FN Site 112"),
Data("FN Site 113"),
Data("FN Site 114"),
Data("FN Site 115"),
Data("FN Site 116"),
Data("FN Site 117"),
Data("FN Site 118"),
Data("FN Site 119"),
Data("FN Site 120"),
Data("FN Site 121"),
Data("FN Site 105"),
Data("Rustpool Banks"),
Data("Potter's Rock"),
Data("Whale's Gullet"),
Data("Rust Lake"),
Data("Waterway Tangle"),
Data("Ensanguined Font"),
Data("Lakeview Stronghold"),
Data("Jasper Incline"),
Data("Old Dragontail Tree"),
Data("Redsnake Pass"),
Data("Whale's Nostril"),
Data("Yagami's Vista"),
Data("Sapphire Carpet"),
Data("Sapphire Table"),
Data("Garden Spring"),
Data("Tripod Rock"),
Data("Humdrum Peaks"),
Data("Goblin's Narrow"),
Data("Sunlit Spring"),
Data("Orochi's Belly"),
Data("Elephant's Trunk"),
Data("Seabound Coil Tree"),
Data("Nopon Highroad"),
Data("Coil Tree Cape"),
Data("Decapotamon Vista"),
Data("Decapotamon"),
Data("Cascade Isle"),
Data("Serpentine Pass"),
Data("Vitriol Cesspool"),
Data("Qing Long Glade"),
Data("Rockmole's Burrow"),
Data("Fukai Pass"),
Data("Everwhelm Falls"),
Data("Sato Headwater"),
Data("Weeping Whitewood"),
Data("Ensconced Citadel"),
Data("Suncatch Ravine"),
Data("Middle Hushflood"),
Data("Great Trident Crossing"),
Data("Bloodpond Basin"),
Data("Millstone Ridge"),
Data("Dead Man's Gulch"),
Data("Shark's Jaws"),
Data("Dead Man's Ingress"),
Data("Upper Hushflood"),
Data("Divine Roost"),
Data("Whale's Weeper"),
Data("Nopon Braidbridge"),
Data("Skybound Coil Tree"),
Data("Great Nail"),
Data("Bident Crossing"),
Data("Blackback Bridge"),
Data("Narcissus Tree"),
Data("Celestial Ascent"),
Data("Celestial Cleave"),
Data("Sentinel's Nest"),
Data("Canopied Nightwood"),
Data("Lotus Keep Building Site"),
Data("Twin Hammers"),
Data("Breakwater Narrow"),
Data("Skygazer's Atrium"),
Data("Idyll Beach"),
Data("FN Site 201"),
Data("FN Site 202"),
Data("FN Site 203"),
Data("FN Site 204"),
Data("FN Site 205"),
Data("FN Site 206"),
Data("FN Site 207"),
Data("FN Site 208"),
Data("FN Site 209"),
Data("FN Site 210"),
Data("FN Site 211"),
Data("FN Site 212"),
Data("FN Site 213"),
Data("FN Site 214"),
Data("FN Site 215"),
Data("FN Site 216"),
Data("FN Site 217"),
Data("FN Site 218"),
Data("FN Site 219"),
Data("FN Site 220"),
Data("FN Site 221"),
Data("FN Site 222"),
Data("FN Site 223"),
Data("FN Site 224"),
Data("FN Site 225"),
Data("Oblivia Ingress"),
Data("Yawning Giant"),
Data("Mesa Fortress"),
Data("Demon's Pocket"),
Data("Scabland Fortress"),
Data("River Isle"),
Data("Rooney Cavern"),
Data("Atop the Giant Ring"),
Data("Ejiri Promontory"),
Data("Leaning Ring"),
Data("Drowning Ring"),
Data("Beachside Trove"),
Data("Azure Lagoon"),
Data("Balance Rock"),
Data("South Coast"),
Data("Barbarich Desert"),
Data("Primeval Meadow"),
Data("Cryptic Sign"),
Data("Jair Fortress"),
Data("Sea Whisper Valley"),
Data("West Ibra Ravine"),
Data("Central Ibra Ravine"),
Data("East Ibra Ravine"),
Data("Victory Rock"),
Data("Alexander Ridge"),
Data("Wrothian Stronghold"),
Data("Dorian Caravan"),
Data("Lake Basel"),
Data("Floating Reef"),
Data("Ruins on the Sandbank"),
Data("King's Falls"),
Data("Milligan Supply Base"),
Data("North Coast"),
Data("Big Arch"),
Data("Ruins on the Butte"),
Data("Kintrees"),
Data("Aaroy Plain"),
Data("Twin Arches"),
Data("Devil's Colony"),
Data("Great Washington Isle"),
Data("Cliffside Camp"),
Data("Crater Oasis"),
Data("North Ant's Nest"),
Data("Ant's Nest"),
Data("South Ant's Nest"),
Data("Keegan Ridge"),
Data("Stoyanov Trail"),
Data("Mount Edge Peak"),
Data("Beehive Rock"),
Data("Eddie's Conquest"),
Data("FN Site 301"),
Data("FN Site 302"),
Data("FN Site 303"),
Data("FN Site 304"),
Data("FN Site 305"),
Data("FN Site 306"),
Data("FN Site 307"),
Data("FN Site 308"),
Data("FN Site 309"),
Data("FN Site 310"),
Data("FN Site 311"),
Data("FN Site 312"),
Data("FN Site 313"),
Data("FN Site 314"),
Data("FN Site 315"),
Data("FN Site 316"),
Data("FN Site 317"),
Data("FN Site 318"),
Data("FN Site 320"),
Data("FN Site 321"),
Data("FN Site 319"),
Data("FN Site 322"),
Data("Seabird's Beak"),
Data("Needle Rock Sandsea"),
Data("South Silent Sandsea"),
Data("North Silent Sandsea"),
Data("Lake Ciel"),
Data("South Ciel Sandsea"),
Data("West Ciel Sandsea"),
Data("East Ciel Sandsea"),
Data("North Ciel Sandsea"),
Data("Shivering Sands"),
Data("Xanadu Overlook"),
Data("Cleansing Spring"),
Data("Badr Stonebridge"),
Data("Anvil Rock Two"),
Data("Anvil Rock One"),
Data("Anvil Sandplain"),
Data("South Hardheart Canyon"),
Data("Hardheart Canyon"),
Data("North Hardheart Canyon"),
Data("Southern Searoad"),
Data("Sylvalum Searoad"),
Data("Northern Searoad"),
Data("Delusians North Summit"),
Data("Gehenna Span"),
Data("Delusians South Summit"),
Data("South Cinderdunes"),
Data("West Cinderdunes"),
Data("North Cinderdunes"),
Data("Samuel Incline"),
Data("Cauldros Threshold"),
Data("Hilal Meadow"),
Data("Hilal Stronghold"),
Data("Badr Basin"),
Data("Badr Stronghold"),
Data("Secluded Lava Lake"),
Data("Cavernous Abyss"),
Data("Banshee Cave"),
Data("Quay Hollows"),
Data("Den of the Dead"),
Data("Behemoth's Shadows"),
Data("Sandsprint Slope"),
Data("Lesser Anvil"),
Data("Arc Rock"),
Data("Abyss Reservoir"),
Data("Noctilucent Sphere"),
Data("Lower Delusian Mountains"),
Data("Sandsprint Cavity"),
Data("Noctilucent Sphere Interior"),
Data("FN Site 401"),
Data("FN Site 402"),
Data("FN Site 403"),
Data("FN Site 404"),
Data("FN Site 405"),
Data("FN Site 406"),
Data("FN Site 407"),
Data("FN Site 408"),
Data("FN Site 409"),
Data("FN Site 410"),
Data("FN Site 411"),
Data("FN Site 412"),
Data("FN Site 413"),
Data("FN Site 414"),
Data("FN Site 415"),
Data("FN Site 416"),
Data("FN Site 417"),
Data("FN Site 418"),
Data("FN Site 419"),
Data("FN Site 420"),
Data("Drongo Caravan"),
Data("Scholes Battlegrounds"),
Data("Infernal Ledges"),
Data("Ancient Warscape"),
Data("Wildcat Fortress"),
Data("White Phosphor Lake"),
Data("O'rrh Sim Gate"),
Data("Ganglion Antropolis"),
Data("Ruined City of O'rrh Sim"),
Data("G'nahan Villa"),
Data("Emerian Battlegrounds"),
Data("Forgotten Mining Frigates"),
Data("Adder Byroad"),
Data("Bandits' Refuge"),
Data("Slavebird Isle"),
Data("Ganglion Weapons Hangar"),
Data("O'rrh Sim Castle Ruins"),
Data("Tengu's Playground"),
Data("T'phnom Shelf"),
Data("Kitsune Stronghold"),
Data("Sunset Falls"),
Data("Kw'arah Villa"),
Data("Kw'arah Cloister"),
Data("Boxtrap Checkpoint"),
Data("M'gando Mineral Spring"),
Data("Bestial Utopia"),
Data("M'gando Volcanic Crater"),
Data("Mount M'gando"),
Data("Old Ceremonial Hollow_1"),
Data("Old Ceremonial Hollow_2"),
Data("Beneath O'rrh Sim Keep"),
Data("Dragonbone Promontory"),
Data("Ternion Fork"),
Data("Abandoned Bivouac"),
Data("M'gando Gorge"),
Data("Titan's Table"),
Data("Cauldros Gate"),
Data("Capital Wreckage"),
Data("O'rrh Sim Capital Remains"),
Data("O'rrh Sim Watchtowers"),
Data("Far Isle of Tzu'o"),
Data("FN Site 501"),
Data("FN Site 502"),
Data("FN Site 503"),
Data("FN Site 504"),
Data("FN Site 505"),
Data("FN Site 506"),
Data("FN Site 507"),
Data("FN Site 508"),
Data("FN Site 509"),
Data("FN Site 510"),
Data("FN Site 511"),
Data("FN Site 512"),
Data("FN Site 513"),
Data("FN Site 514"),
Data("FN Site 515"),
Data("FN Site 516"),
Data("Shadow Rise BC"),
Data("Shadow Beach BC"),
Data("East Gate BC"),
Data("South Janpath BC"),
Data("Biahno Grassland BC"),
Data("North Janpath BC"),
Data("Sayram Lake BC"),
Data("Roof Rock BC"),
Data("camp1501_09"),
Data("camp1501_10"),
Data("Rustpool Banks BC"),
Data("Whale's Nostril BC"),
Data("Tripod Rock BC"),
Data("Canopied Nightwood BC"),
Data("Decapotamon BC"),
Data("Qing Long Glade BC"),
Data("Bloodpond Basin BC"),
Data("Dead Man's Ingress BC"),
Data("camp1601_09"),
Data("camp1601_10"),
Data("Oblivia Ingress BC"),
Data("Aaroy Plain BC"),
Data("Needle Bridge BC"),
Data("Broken Hill BC"),
Data("River Isle BC"),
Data("Balance Rock BC"),
Data("North Coast BC"),
Data("Cliff's Edge BC"),
Data("camp1701_09"),
Data("camp1701_10"),
Data("Ancient Warscape BC"),
Data("Titan's Table BC"),
Data("Emerian Battlegrounds BC"),
Data("Rocky Lagoon BC"),
Data("Adder Byroad BC"),
Data("Ternion Fork BC"),
Data("T'phnom Shelf BC"),
Data("M'gando Gorge BC"),
Data("camp2001_09"),
Data("camp2001_10"),
Data("Seabird's Beak BC"),
Data("Needle Rock BC"),
Data("NW Ciel Sandsea BC"),
Data("Hardheart Ravine BC"),
Data("Delusians North Summit BC"),
Data("Samuel Incline BC"),
Data("North Silent Sandsea BC"),
Data("Cauldros Threshold BC"),
Data("camp2201_09"),
Data("camp2201_10"),
Data("NLA Last Defense Line"),
Data("NLA Primary Defense Line"),
Data("Zu Pharg Interception Line"),
Data("Lifehold Core"),
Data("O'rrh Sim Keep"),
]