from ..Locations import Loc as Data

# from helper
# flake8: noqa
segments_data: list[Data] = [
Data("Name: Celica[ST:n ]Affinity: 5[ST:n ]Appears: Night[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Name: Nagi[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: Complete 1st heart-to-heart"),
Data("Mission: The Gauntlet[ST:n ]Client: Zo Ozuchi"),
Data("Mission: Two Warriors[ST:n ]Client: Go Belg"),
Data("Mission: Data Probe Challenge[ST:n ]Client: Hugo"),
Data("Mission: Good Fortun[ST:n ]Client: HT665: Erio"),
Data("Name: Celica[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Completed Celica and Rock's affinity mission[ST:n ]\"New in New LA.\""),
Data("Celica can often be found here."),
Data("Mission: Yardley's Scheme[ST:n ]Client: Yardley"),
Data("Mission: Off the Record[ST:n ]Client: ???_1"),
Data("Completed Gwin's affinity mission[ST:n ]\"Boot Camp.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_1"),
Data("Completed Lin's affinity mission[ST:n ]\"A Girl's Wings.\""),
Data("Mission: Muimui's Meltdown[ST:n ]Client: Moimoi"),
Data("Mission: Turf War[ST:n ]Client: Enrai"),
Data("Name: Doug[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: A Proper Chopper[ST:n ]Client: Roscoe"),
Data("Name: Murderess[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: Forest Foray[ST:n ]Client: Sullivan"),
Data("Mission: Pollution Solution[ST:n ]Client: Liza"),
Data("Mission: Good Neighbors[ST:n ]Client: Tan'celeg"),
Data("Name: Irina[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Name: Lin[ST:n ]Affinity: 1[ST:n ]Appears: Night"),
Data("Mission: Data Probe Breakthrough[ST:n ]Client: Hugo"),
Data("Mission: Data Probe Revolution[ST:n ]Client: Hugo"),
Data("Name: Elma[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Mission: Lone Survivors[ST:n ]Client: Robert"),
Data("Mission: Entrepreneurial Spirit[ST:n ]Client: Tobias"),
Data("Mission: Child of Mira[ST:n ]Client: Orleron"),
Data("Object: Container[ST:n ]Required Field Skill: Mechanical Level 3"),
Data("Mission: Orphe Pluck[ST:n ]Client: San'luarb"),
Data("Mission: Data Probe Progress[ST:n ]Client: Hugo"),
Data("Mission: Data Probe Evolution[ST:n ]Client: Hugo"),
Data("Mission: The Pip-Squeak[ST:n ]Client: Matthew"),
Data("Mission: Professorial[ST:n ]Client: Veven"),
Data("Mission: Rise of the Blood Lobster[ST:n ]Client: The Blood Lobster"),
Data("Name: Mia[ST:n ]Affinity: 3[ST:n ]Appears: Late Night[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Name: Hope[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: Pack It In[ST:n ]Client: Nococche"),
Data("Name: Irina[ST:n ]Affinity: 1[ST:n ]Appears: Night"),
Data("Name: Frye [ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Alexa can often be found here."),
Data("Name: Celica[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Mission: Mystery Man[ST:n ]Client: Professor B"),
Data("Mission: The Voltant Visionary[ST:n ]Client: Trachlo Lythren"),
Data("Name: Horonalderon[ST:n ]Situation: He was saved by a squad[ST:n ]of rather odd characters outside."),
Data("Frye can often be found here."),
Data("Mission: The Good Thief[ST:n ]Client: Horonalderon"),
Data("Completed Celica and Rock's affinity mission[ST:n ]\"Fitting In.\""),
Data("Mission: Professor B's Return[ST:n ]Client: Veven"),
Data("Mission: Gold Rush[ST:n ]Client: Adolphus"),
Data("Name: Frye[ST:n ]Affinity: 1[ST:n ]Appears: Late Night"),
Data("Completed Frye's affinity mission[ST:n ]\"Bottoms Up.\""),
Data("Mission: Going Viral[ST:n ]Client: Julius"),
Data("Name: Gwin[ST:n ]Affinity: 5[ST:n ]Appears: Evening[ST:n ]Requirements: View 4th heart-to-heart,[ST:n ]Irina must not be in the party"),
Data("Mission: Alien Nation[ST:n ]Client: Alex"),
Data("Name: Lin[ST:n ]Affinity: 2[ST:n ]Appears: Afternoon[ST:n ]Pet: Dog[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Name: Mia[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Boz\u00e9 can often be found here."),
Data("Name: Celica[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Object: Container[ST:n ]Required Field Skill: Mechanical Level 2_1"),
Data("Mission: Stop, Thief![ST:n ]Client: Shiraton"),
Data("Mission: A Dubious Operation[ST:n ]Client: Shiraton"),
Data("Name: Mia[ST:n ]Affinity: 2[ST:n ]Appears: Late Night[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_1"),
Data("Name: Phog[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Mission: A Hero's Ride[ST:n ]Client: Justin"),
Data("Mission: Better Latte Than Never[ST:n ]Client: Jo"),
Data("Name: Doug[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Name: Quiquat[ST:n ]Situation: This Ma-non is set on learning[ST:n ]about FrontierNav."),
Data("Name: Lin[ST:n ]Affinity: 4[ST:n ]Appears: Evening[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Mission: Emotion Commotion[ST:n ]Client: Chiopitus"),
Data("Completed Lao's affinity mission[ST:n ]\"The Matchmaker.\""),
Data("Mission: Definian Downfall[ST:n ]Client: HT665: Erio"),
Data("Name: Irina[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Name: Veverta[ST:n ]Situation: She dropped her device somewhere[ST:n ]and is in a fix."),
Data("Completed Gwin's affinity mission[ST:n ]\"Nine Lives.\""),
Data("Completed Irina's affinity mission[ST:n ]\"Renewed Will.\""),
Data("Mission: No Ma-non Need Apply[ST:n ]Client: Wersal"),
Data("Name: L[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Name: Nagi[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: Sparking a Smile[ST:n ]Client: Ngogo"),
Data("Mission: Unsatisfied Customer[ST:n ]Client: Chiroro"),
Data("Mission: The Fashionista[ST:n ]Client: Victoria"),
Data("Mission: Planetary Pioneer (Part III)[ST:n ]Client: Kirsty"),
Data("Yelv can often be found here."),
Data("Mission: The Sword of Legendaryness[ST:n ]Client: Muimui"),
Data("Name: Murderess[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Completed the Murderess's affinity mission[ST:n ]\"Serial Thriller.\""),
Data("Name: Frye[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Mission: My Angel, My Lana[ST:n ]Client: Bubu"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3_1"),
Data("Name: Hope[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Mission: Trade Agreement[ST:n ]Client: Warawa"),
Data("Completed Tatsu's affinity mission[ST:n ]\"The Ties That Bind.\""),
Data("Name: L[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Name: Beats[ST:n ]Situation: He seems to be looking for[ST:n ]some kind of manuscript data."),
Data("Mission: Murder Most Foul[ST:n ]Client: Ackwar"),
Data("Mission: Wrothian Innovation[ST:n ]Client: Go Sirho"),
Data("Name: Hope[ST:n ]Affinity: 2[ST:n ]Appears: Evening[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: A Dish Served Cold[ST:n ]Client: Zo Langra"),
Data("Name: Elma[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: Forbidden Love[ST:n ]Client: Loda Gorida"),
Data("Mission: No-Show Nen'celeg[ST:n ]Client: Nan'celeg"),
Data("Mission: Gorkwa Games[ST:n ]Client: Troylan"),
Data("Mission: House Call[ST:n ]Client: Nan'celeg"),
Data("Mission: A New Life[ST:n ]Client: Bazis Wolfen"),
Data("Mission: Here Come the Brides[ST:n ]Client: Nemard Wolfen"),
Data("Mission: The Unbreakable Sword[ST:n ]Client: De Zing"),
Data("Mission: A Grim Undertaking[ST:n ]Client: Hala Gorida"),
Data("Name: L[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: The Lurker[ST:n ]Client: Go Rogan"),
Data("Mission: Snipe Hunt[ST:n ]Client: Bihabba"),
Data("Mia can often be found here."),
Data("Mission: Sun'celeg Rises[ST:n ]Client: Sun'barac"),
Data("Name: Zurranik[ST:n ]Situation: Rumor has it he received a large[ST:n ]sum of money from a suspicious Wrothian..."),
Data("Mission: The Membership[ST:n ]Client: May May"),
Data("Mission: Tree-mendous[ST:n ]Client: Sevvy Belgazus"),
Data("Name: Elma[ST:n ]Affinity: 4[ST:n ]Appears: Evening[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Mission: The Old Gods[ST:n ]Client: Feloran"),
Data("Mission: An Ancient Legend[ST:n ]Client: Nimu Turton"),
Data("Mission: Training Day[ST:n ]Client: Zarch Quokett"),
Data("Mission: The Art of War[ST:n ]Client: Sajif Scoppio"),
Data("Mission: Slovity's Revenge[ST:n ]Client: Slovity Pagus"),
Data("Mission: The Party Line[ST:n ]Client: Sun'barac"),
Data("Name: Phog[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Mission: Circle of Life[ST:n ]Client: Kon'luarb"),
Data("Phog can often be found here."),
Data("Name: Lin[ST:n ]Affinity: 5[ST:n ]Appears: Morning[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Mission: Off the Record[ST:n ]Client: ???_2"),
Data("Name: Phog[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_2"),
Data("Name: Gwin[ST:n ]Affinity: 2[ST:n ]Appears: Late Night[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: Herbivores, Unite![ST:n ]Client: Naza Tenpanzi"),
Data("Completed Hope's affinity mission[ST:n ]\"A Present for Hope.\""),
Data("Mission: The Celeste Three[ST:n ]Client: Fosdyke"),
Data("Name: L[ST:n ]Affinity: 5[ST:n ]Appears: Early Morning[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Name: Celica[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Name: Doug[ST:n ]Affinity: 3[ST:n ]Appears: Daytime[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Name: Gwin[ST:n ]Affinity: 3[ST:n ]Appears: Late Night[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Name: Frye[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: The Line of Fire[ST:n ]Client: Alice"),
Data("Hope can often be found here."),
Data("Mission: Planetary Pioneer (Part V)[ST:n ]Client: Kirsty"),
Data("Name: Gwin[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Dog[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Name: Mia[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Name: Hope[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Dog[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Name: Phog[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Completed Phog's affinity mission[ST:n ]\"Foggy Dilemma.\""),
Data("Name: Murderess[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Name: Murderess[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3_2"),
Data("Name: Doug[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon[ST:n ]Pet: Dog"),
Data("Mission: Bread and a Circus[ST:n ]Client: Moimoi"),
Data("Name: Elma[ST:n ]Affinity: 2[ST:n ]Appears: Night[ST:n ]Pet: Cat[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: New Frontier[ST:n ]Client: Kirsty"),
Data("Mission: Off the Record[ST:n ]Client: ???_3"),
Data("Name: Mia[ST:n ]Affinity: 1[ST:n ]Appears: Late Night"),
Data("Name: Caroline[ST:n ]Situation: She was the victim of an Orphean[ST:n ]breaking and entering."),
Data("Mission: Alex's Last Stand[ST:n ]Client: Eliza"),
Data("Name: Phog[ST:n ]Affinity: 2[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Name: Kon'luarb[ST:n ]Situation: Apparently he is digging up info on[ST:n ]the water plant."),
Data("Mission: Lakeside Getaway[ST:n ]Client: Rosie"),
Data("Mission: Water Woes[ST:n ]Client: Ajoa"),
Data("Name: Irina[ST:n ]Affinity: 2[ST:n ]Appears: Evening[ST:n ]Pet: Dog[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Name: L[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Name: Murderess[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Name: Wendy[ST:n ]Situation: A Nopon salesman is giving[ST:n ]her trouble."),
Data("Name: Nagi[ST:n ]Affinity: 5[ST:n ]Appears: Afternoon[ST:n ]Requirements: View 4th heart-to-heart"),
Data("H.B. can often be found here."),
Data("Completed Hope's affinity mission[ST:n ]\"Hope Springs Eternal.\""),
Data("Mission: The Miracle Maker[ST:n ]Client: Staccata"),
Data("Mission: The Divine Nopopon[ST:n ]Client: Shinshin"),
Data("Completed Phog's affinity mission[ST:n ]\"A Great Divide.\""),
Data("Mission: The Bug Whisperer[ST:n ]Client: Min'barac"),
Data("Mission: Shotgun Diplomacy[ST:n ]Client: Eliza"),
Data("Name: Letrick[ST:n ]Situation: He is searching for whoever it was[ST:n ]that dropped by the cathedral in his absence."),
Data("Mission: Rites of Ruin[ST:n ]Client: Jalimbo"),
Data("Mission: Definian Love[ST:n ]Client: Lyvia[ST:n ]or[ST:n ]Mission: Fortun and Glory[ST:n ]Client: Erio"),
Data("Name: Phoskeran[ST:n ]Situation: Predicting the future is his[ST:n ]new hobby."),
Data("Object: Container[ST:n ]Required Field Skill: Mechanical Level 2_2"),
Data("Object: Trailer[ST:n ]Required Field Skill: Mechanical Level 3"),
Data("Mission: A Fateful Choice[ST:n ]Client: On'tonam"),
Data("Mission: The Journey Begins[ST:n ]Client: Kun'luarb"),
Data("Name: Hope[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Mission: The Duel (Part II)[ST:n ]Client: Gi Zang"),
Data("Nagi can often be found here."),
Data("Mission: Cavern Crushers[ST:n ]Client: Stella"),
Data("Mission: Attack on Biahno Hills[ST:n ]Client: Lara Nara"),
Data("Mission: Dead Men Tell No Tales[ST:n ]Client: Stella"),
Data("Mission: Prone Sweet Prone[ST:n ]Client: Stella"),
Data("Object: Large Container[ST:n ]Required Field Skill: Mechanical Level 4"),
Data("Name: Gwin[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Name: Irina[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Doug can often be found here."),
Data("Object: Trailer[ST:n ]Required Field Skill: Mechanical Level 2"),
Data("Completed Celica and Rock's affinity mission[ST:n ]\"Manhunt.\""),
Data("Completed Chausson's affinity mission[ST:n ]\"Spy Games.\""),
Data("Mission: Rescue at the Ensconced Citadel[ST:n ]Client: Julius"),
Data("Mission: The Ultimate Price[ST:n ]Client: Quincy"),
Data("Mission: The Handy Ma-non[ST:n ]Client: Sostenasa"),
Data("Completed the Murderess's affinity mission[ST:n ]\"My Dream.\""),
Data("Name: Cedric[ST:n ]Situation: He seems to be under pressure[ST:n ]to run an errand."),
Data("Completed L's affinity mission[ST:n ]\"The Nopon Heir.\""),
Data("L can often be found here."),
Data("Mission: That's In-Credible![ST:n ]Client: Tutura"),
Data("Completed Nagi's affinity mission[ST:n ]\"Reporting for Duty.\""),
Data("Completed Hope's affinity mission[ST:n ]\"A False Hope.\""),
Data("Mission: Planetary Pioneer (Part II)[ST:n ]Client: Kirsty"),
Data("Name: Nopopon[ST:n ]Situation: Word is a Nopon ghost roams[ST:n ]the administrative district late at night."),
Data("Mission: Mamma Mia![ST:n ]Client: Mia"),
Data("Completed Mia's affinity mission[ST:n ]\"Mia Grows Up.\""),
Data("Completed Frye and Phog's affinity mission[ST:n ]\"Brotherly Love.\""),
Data("Name: Doug[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Completed L's affinity mission[ST:n ]\"L's Conundrum.\""),
Data("Mission: Booming Business[ST:n ]Client: L"),
Data("Mission: Lend an Ear[ST:n ]Client: Gu Ladha"),
Data("Mission: Setting Forth[ST:n ]Client: Muimui"),
Data("Name: Nagi[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon"),
Data("Mission: Planetary Pioneer (Part IV)[ST:n ]Client: Kirsty"),
Data("Mission: Waste Not, Want Not [ST:n ]Client: Lara Mara"),
Data("Mission: Skell License[ST:n ]Client: Vandham"),
Data("Name: Frye[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart"),
Data("Mission: House of Cards[ST:n ]Client: Yardley"),
Data("Mission: White Lifehold[ST:n ]Client: Lara Mara"),
Data("Mission: BLADE Level Basics[ST:n ]Client: Eleonora"),
Data("Completed Doug's affinity mission[ST:n ]\"Soldier of the Harriers.\""),
Data("Mission: The Probe-fessional[ST:n ]Client: Kirsty"),
Data("Mission: The Duel (Part III)[ST:n ]Client: Gi Zang"),
Data("Completed the Murderess's affinity mission[ST:n ]\"The Little Rich Girl.\""),
Data("Lao can often be found here."),
Data("Gwin can often be found here."),
Data("Mission: City Saviors[ST:n ]Client: Carl"),
Data("Completed Doug's affinity mission[ST:n ]\"Close Comrades.\""),
Data("Mission: Planetary Pioneer (Part I)[ST:n ]Client: Kirsty"),
Data("Name: Wolf[ST:n ]Situation: He seems to be recruiting[ST:n ]non-human BLADE operatives."),
Data("Mission: Ovah and Out[ST:n ]Client: Han'barac"),
Data("Mission: Cooking Schooled[ST:n ]Client: Sherry"),
Data("Mission: Mia Is Missing![ST:n ]Client: Mia"),
Data("Mission: Unknown Assailant[ST:n ]Client: Raleigh"),
Data("Mission: Frontier Spirit[ST:n ]Client: Corwin"),
Data("Name: Lin[ST:n ]Affinity: 3[ST:n ]Appears: Afternoon[ST:n ]Requirements: View 2nd heart-to-heart"),
Data("Mission: Close Encounters[ST:n ]Client: Sarona"),
Data("Mission: The Root of All Evil[ST:n ]Client: Tobias"),
Data("Irina can often be found here."),
Data("The Murderess can often be found here."),
Data("Mission: Myles to Go[ST:n ]Client: Satie"),
Data("Mission: Slovity's Rampage[ST:n ]Client: Trigo Bambott"),
Data("Completed Frye and Phog's affinity mission[ST:n ]\"Blitzkrieg.\""),
Data("Enemy: Caesar, the Hundred-Eyed[ST:n ]Subcategory: Petramand[ST:n ]Appears: Always"),
Data("Completed mission \"Snipe Hunt.\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1_1"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 5"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1_2"),
Data("Enemy: Celestin, the Spring Storm[ST:n ]Subcategory: Progen[ST:n ]Appears: Always"),
Data("Completed mission \"The Repair Job.\""),
Data("Completed mission \"The Queen Is Dead.\"_1"),
Data("Object: Strange Insect Nest[ST:n ]Required Field Skill: Biological Level 1"),
Data("Enemy: Zdenka, the Raucous[ST:n ]Subcategory: Saltat[ST:n ]Appears: Always"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1_1"),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 1_1"),
Data("Enemy: Sapara, the Laconic[ST:n ]Subcategory: Saltat[ST:n ]Appears: Rarely"),
Data("Completed mission \"A Day in the Life.\""),
Data("Completed mission \"Haywire!\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1_2"),
Data("Completed mission \"Forbidden Love.\""),
Data("Enemy: Bohdan, the Mistral[ST:n ]Subcategory: Auravis[ST:n ]Appears: Daytime"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_1"),
Data("Completed mission \"Cinicula Assault.\""),
Data("Completed mission \"Renewed Will.\""),
Data("Enemy: Casper, the Unhealthy Eater[ST:n ]Subcategory: Blatta[ST:n ]Appears: Nighttime"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 5"),
Data("Completed mission \"The Lurker.\""),
Data("Enemy: Eckart, the Indestructible[ST:n ]Subcategory: Cinicula[ST:n ]Appears: Always"),
Data("Enemy: Ridill, the Arrogant[ST:n ]Subcategory: Lophid[ST:n ]Appears: Rarely"),
Data("Enemy: Necro, the Cavelord[ST:n ]Subcategory: Vesper[ST:n ]Appears: Always"),
Data("Enemy: Experimental Composite Qmoeva[ST:n ]Subcategory: Qmoeva[ST:n ]Appears: Nighttime"),
Data("Completed mission \"City Saviors.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_3"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1_3"),
Data("Enemy: Dieter, the Epicure[ST:n ]Subcategory: Grex[ST:n ]Appears: Always"),
Data("Enemy: Daril, the Eradicator[ST:n ]Subcategory: Marnuck[ST:n ]Appears: Nighttime"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 1"),
Data("Completed mission \"The Good Thief.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 3_1"),
Data("Enemy: Mesgen, the Fairweathered[ST:n ]Subcategory: Potamus[ST:n ]Appears: Always"),
Data("Completed mission \"Close Encounters.\""),
Data("Completed mission \"Nagi's Time.\""),
Data("Enemy: Shatskikh, the Flash[ST:n ]Subcategory: Xiphias[ST:n ]Appears: Rarely"),
Data("Completed mission \"Welcome Back, Conner.\""),
Data("Completed mission \"Here Come the Brides.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_2"),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 1_2"),
Data("Completed mission \"An Ancient Legend.\""),
Data("Completed mission \"We Were Soldiers.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2_1"),
Data("Enemy: Etutanne, the Bloodthirsty[ST:n ]Subcategory: Adsecula[ST:n ]Appears: Always"),
Data("Enemy: Hephaestus, the Absconder[ST:n ]Subcategory: Duoguill[ST:n ]Appears: Nighttime"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1_4"),
Data("Completed mission \"Nine Lives.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_4"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_1"),
Data("Enemy: Gugli, the Relentless[ST:n ]Subcategory: Suid[ST:n ]Appears: Always"),
Data("Enemy: Luciel, the Eternal[ST:n ]Subcategory: Millesaur[ST:n ]Appears: Always"),
Data("Enemy: Eutropio, the Sea Rumble[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always"),
Data("Completed mission \"A Dubious Operation.\""),
Data("Completed mission \"Muimui's Meltdown.\""),
Data("Completed mission \"Training Day.\""),
Data("Completed mission \"A False Hope.\""),
Data("Enemy: Bogdan, the Dense[ST:n ]Subcategory: Suid[ST:n ]Appears: Always"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3_3"),
Data("Completed mission \"Stop, Thief!\""),
Data("Enemy: Ji-ett, the Thunderclap[ST:n ]Subcategory: Fal-swo[ST:n ]Appears: Nighttime"),
Data("Enemy: Rajidi, the Cumuliform[ST:n ]Subcategory: Balaena[ST:n ]Appears: Rarely"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_1"),
Data("Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 5"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_2"),
Data("Completed mission \"A Fateful Choice.\""),
Data("Completed mission \"The Nopon Heir.\""),
Data("Enemy: Planetes, the Torrential[ST:n ]Subcategory: Unafulge[ST:n ]Appears: Always"),
Data("Completed mission \"House Call.\""),
Data("Enemy: Pyotr, the Shepherd[ST:n ]Subcategory: Sylooth[ST:n ]Appears: Always"),
Data("Completed mission \"Prospective Partners.\""),
Data("Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 4"),
Data("Completed mission \"Frontier Spirit.\""),
Data("Enemy: Froste, the Courteous[ST:n ]Subcategory: Vesper[ST:n ]Appears: Always"),
Data("Enemy: Telethia, the Endbringer[ST:n ]Subcategory: Telethia[ST:n ]Appears: Always[ST:n ][ST:n ](Must be defeated in a non-mission encounter.)"),
Data("Enemy: Joker, the Unknowable[ST:n ]Subcategory: Blatta[ST:n ]Appears: Always"),
Data("Enemy: Frajeel, the Purgatorial[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always"),
Data("Completed mission \"The Art of War.\""),
Data("Completed mission \"Rescue at the[ST:n ]Ensconced Citadel.\""),
Data("Completed mission \"My Dream.\""),
Data("Enemy: Katerina, the Cliffhanger[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always"),
Data("Enemy: Schneider, the Cliffpercher[ST:n ]Subcategory: Forfex[ST:n ]Appears: Always"),
Data("Completed mission \"The Voltant Visionary.\""),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_2"),
Data("Completed mission \"Circle of Life.\""),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_1"),
Data("Completed mission \"No-show Nen'celeg.\""),
Data("Object: Trailer Wreckage[ST:n ]Required Field Skill: Mechanical Level 1"),
Data("Completed mission \"Dodonga Caravan.\""),
Data("Completed mission \"Manhunt.\""),
Data("Enemy: Demetrio, the Tempestuous[ST:n ]Subcategory: Simius[ST:n ]Appears: Always"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_3"),
Data("Completed mission \"Close Comrades.\""),
Data("Completed mission \"A Proper Chopper.\""),
Data("Completed mission \"Dead Men Tell No Tales.\""),
Data("Completed mission \"Murder Most Foul.\""),
Data("Enemy: Elena, the Infernal[ST:n ]Subcategory: Scirpo[ST:n ]Appears: Fog"),
Data("Enemy: Griffus, the Tartarean[ST:n ]Subcategory: Insidia[ST:n ]Appears: Always"),
Data("Completed mission \"Adventure!\""),
Data("Enemy: Tormenta, the Scarlet-Clad[ST:n ]Subcategory: Turba[ST:n ]Appears: Always"),
Data("Completed mission \"Lone Survivors.\""),
Data("Enemy: Sarcosuchus, the Iron-Eater[ST:n ]Subcategory: Dilus[ST:n ]Appears: Always"),
Data("Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 1"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_2"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_1"),
Data("Completed mission \"The Duel (Part II).\""),
Data("Enemy: Clemente, the Iron Meteor[ST:n ]Subcategory: Falsaxum[ST:n ]Appears: Always"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_1"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1_3"),
Data("Completed mission \"Missing in Action.\""),
Data("Enemy: Desdemona, the Subterranean[ST:n ]Subcategory: Scirpo[ST:n ]Appears: Always"),
Data("Enemy: Buchwald, the Guardian[ST:n ]Subcategory: Virago[ST:n ]Appears: Always"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_3"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_1"),
Data("Completed mission \"Data Miner.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_3"),
Data("Enemy: Melanya, the Sound Sleeper[ST:n ]Subcategory: Suid[ST:n ]Appears: Always"),
Data("Completed mission \"Sun'celeg Rises.\""),
Data("Enemy: Gotthard, the Intimidating[ST:n ]Subcategory: Auravis[ST:n ]Appears: Always"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_4"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 4_1"),
Data("Enemy: Germaine, the Treasure Keeper[ST:n ]Subcategory: Ovis[ST:n ]Appears: Always"),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 2"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_4"),
Data("Enemy: Vendura, the Spellbinder[ST:n ]Subcategory: Prone (Cavern Clan)[ST:n ]Appears: Daytime"),
Data("Enemy: Libra, the Long-Lived[ST:n ]Subcategory: Purgovent[ST:n ]Appears: Always"),
Data("Enemy: Jindriska, the Serene[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always"),
Data("Enemy: Barnabas, the Despot[ST:n ]Subcategory: Vigent[ST:n ]Appears: Daytime"),
Data("Completed mission \"A Dish Served Cold.\""),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 2_1"),
Data("Completed mission \"Prone Sweet Prone.\""),
Data("Enemy: Edgardo, the Carefree[ST:n ]Subcategory: Thallus[ST:n ]Appears: Always"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_2"),
Data("Enemy: Squallo, the Sand Mirer[ST:n ]Subcategory: Sabula[ST:n ]Appears: Daytime"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2_2"),
Data("Completed mission \"Foggy Dilemma.\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_3"),
Data("Enemy: Ro-darm, the Demon Claw[ST:n ]Subcategory: Oc-serv[ST:n ]Appears: Always"),
Data("Completed mission \"Slovity's Rampage.\""),
Data("Completed mission \"Mayday.\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_5"),
Data("Enemy: Hartmut, the Calamity[ST:n ]Subcategory: Millepod[ST:n ]Appears: Always"),
Data("Enemy: Valeriano, the Rolling Thunder[ST:n ]Subcategory: Duoguill[ST:n ]Appears: Electromagnetic storm"),
Data("Completed mission \"A Friend in Need.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_4"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_4"),
Data("Enemy: Ernest, the Contemplative[ST:n ]Subcategory: Progen[ST:n ]Appears: Always"),
Data("Enemy: Celedonio, the Battle-Tested[ST:n ]Subcategory: Grex[ST:n ]Appears: Always"),
Data("Object: Indigen Dung[ST:n ]Required Field Skill: Biological Level 2"),
Data("Enemy: Vittorio, the Battle-Scarred[ST:n ]Subcategory: Tectinsula[ST:n ]Appears: Always"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2_3"),
Data("Completed mission \"Mighty Mia.\""),
Data("Object: Trailer Wreckage[ST:n ]Required Field Skill: Mechanical Level 2"),
Data("Completed mission \"The Duel (Part I).\""),
Data("Enemy: Rolf, the Sonorous[ST:n ]Subcategory: Saltat[ST:n ]Appears: Always"),
Data("Enemy: Ludvik, the Picky Eater[ST:n ]Subcategory: Casuari[ST:n ]Appears: Daytime"),
Data("Completed mission \"A Grim Undertaking.\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_5"),
Data("Completed mission \"The Little Rich Girl.\""),
Data("Enemy: Elaine, the Lunar Eclipse[ST:n ]Subcategory: Ceto[ST:n ]Appears: Nighttime"),
Data("Completed mission \"A Challenger Approaches.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_5"),
Data("Completed mission \"Then and Now.\""),
Data("Enemy: Eliane, the Unmoved[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always"),
Data("Enemy: Sviatoslav, the Reproachful[ST:n ]Subcategory: Aprica[ST:n ]Appears: Rain"),
Data("Completed mission \"A Great Divide.\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_6"),
Data("Enemy: Ferdinand, the Fortuitous[ST:n ]Subcategory: Mephite[ST:n ]Appears: Always"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 4_2"),
Data("Completed mission \"Bread and a Circus.\""),
Data("Enemy: Climati, the Chilling Wind[ST:n ]Subcategory: Sylooth[ST:n ]Appears: Always"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 5_1"),
Data("Completed mission \"Shotgun Diplomacy.\""),
Data("Enemy: Silvestre, the Morning Light[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4_6"),
Data("Completed mission \"Dorian Caravan.\""),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_2"),
Data("Object: Indigen Dung[ST:n ]Required Field Skill: Biological Level 3"),
Data("Enemy: Feliciano, the All-Seeing[ST:n ]Subcategory: Sphinx[ST:n ]Appears: Daytime"),
Data("Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 3"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3_1"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_7"),
Data("Enemy: Vilem, the Gold-Scaled[ST:n ]Subcategory: Aetrygon[ST:n ]Appears: Always"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 3_2"),
Data("Enemy: Bertrand, the Gorge Scourge[ST:n ]Subcategory: Adsecula[ST:n ]Appears: Always"),
Data("Completed mission \"The Trading Floor.\""),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_2"),
Data("Completed mission \"Spy Games.\""),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1_5"),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2_1"),
Data("Completed mission \"Supplies Surprise.\""),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 1"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 5_2"),
Data("Completed mission \"Gorkwa Games.\""),
Data("Completed mission \"Sparking a Smile.\""),
Data("Completed mission \"Slovity's Revenge.\""),
Data("Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 2_1"),
Data("Enemy: Kringe, the Hunting Arrow[ST:n ]Subcategory: Caro[ST:n ]Appears: Always"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2_4"),
Data("Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2_5"),
Data("Completed mission \"The Bodyguard.\""),
Data("Completed mission \"My Angel, My Lana.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_5"),
Data("Completed mission \"Definian Downfall.\""),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2_2"),
Data("Enemy: Coil, the Never-Ending[ST:n ]Subcategory: Scintimure[ST:n ]Appears: Electromagnetic storm"),
Data("Enemy: Prinsipe, the Ravenous[ST:n ]Subcategory: Blatta[ST:n ]Appears: Nighttime"),
Data("Completed mission \"The Old Gods.\""),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2_3"),
Data("Completed mission \"Mia Is Missing!\""),
Data("Completed mission \"The Duel (Part IV).\""),
Data("Enemy: Chantai's Galdr[ST:n ]Subcategory: Galdr[ST:n ]Appears: Daytime"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 3_1"),
Data("Completed mission \"To Serve Nopon.\""),
Data("Completed mission \"Rites of Ruin.\""),
Data("Completed mission \"Black Lifehold.\""),
Data("Enemy: Eisen, the Ebon Rock[ST:n ]Subcategory: Petramand[ST:n ]Appears: Nighttime"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2_1"),
Data("Completed mission \"Lionhearted.\""),
Data("Enemy: Pelicollo, the Panzer[ST:n ]Subcategory: Caecus[ST:n ]Appears: Always"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 3_1"),
Data("Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 3_1"),
Data("Enemy: Chantai, the Insect Maiden[ST:n ]Subcategory: Milsaadi[ST:n ]Appears: Nighttime"),
Data("Enemy: Armored Cruiser Seidr[ST:n ]Subcategory: Seidr[ST:n ]Appears: Daytime"),
Data("Enemy: Duran, the Draconian[ST:n ]Subcategory: Marnuck[ST:n ]Appears: Always (except late night)"),
Data("Enemy: Ilithios, the Enlightened[ST:n ]Subcategory: Gularth[ST:n ]Appears: Always (except flaming hail)"),
Data("Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 3_2"),
Data("Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 2_2"),
Data("Completed mission \"A Present for Hope.\""),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_6"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 2_2"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2_2"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_2"),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2_4"),
Data("Enemy: Terenty, the Blademaster[ST:n ]Subcategory: Ictus[ST:n ]Appears: Always"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2_3"),
Data("Completed mission \"Until the End.\""),
Data("Enemy: Gi-zho, the Iron Deity[ST:n ]Subcategory: Xe-dom[ST:n ]Appears: Always"),
Data("Enemy: Jia Mian, the Beloved[ST:n ]Subcategory: Jacul[ST:n ]Appears: Always"),
Data("Completed mission \"The Queen Is Dead.\"_2"),
Data("Enemy: Sharnaak, the Technician[ST:n ]Subcategory: Milsaadi[ST:n ]Appears: Nighttime"),
Data("Completed mission \"Alex's Last Stand.\""),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_3"),
Data("Completed mission \"The Unbreakable Sword.\""),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4_1"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_7"),
Data("Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 3"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_3"),
Data("Enemy: Yune, the Ambusher[ST:n ]Subcategory: Visigel[ST:n ]Appears: Rarely"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3_1"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 5"),
Data("Enemy: Behemoth, the Netherdweller[ST:n ]Subcategory: Virago[ST:n ]Appears: Rarely"),
Data("Completed mission \"Lesson from the Grave.\""),
Data("Completed mission \"Predator and Prey.\""),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 2_1"),
Data("Completed mission \"Bottoms Up.\""),
Data("Enemy: Stola, the Champion[ST:n ]Subcategory: Liceor[ST:n ]Appears: Crimson aurora"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_4"),
Data("Enemy: Alexei, the Jade[ST:n ]Subcategory: Monoceros[ST:n ]Appears: Always"),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4_2"),
Data("Completed mission \"Castle in the Sky.\""),
Data("Enemy: Florence, the Hell Maggot[ST:n ]Subcategory: Germivore[ST:n ]Appears: Nighttime"),
Data("Enemy: Antara, the Water Diviner[ST:n ]Subcategory: Arenatect[ST:n ]Appears: Always"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 3_2"),
Data("Completed mission \"Plans of Attack.\""),
Data("Enemy: Radovan, the Sky Baron[ST:n ]Subcategory: Jacul[ST:n ]Appears: Daytime"),
Data("Enemy: Laurencio, the Fog Bow[ST:n ]Subcategory: Filiavent[ST:n ]Appears: Always"),
Data("Enemy: Asana, the Azure Star[ST:n ]Subcategory: Cervus[ST:n ]Appears: Always"),
Data("Completed mission \"The Line of Fire.\""),
Data("Enemy: Damaged Zig[ST:n ]Subcategory: Zig[ST:n ]Appears: Always"),
Data("Completed mission \"Unknown Assailant.\""),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 5"),
Data("Enemy: Candelario, the Bronze[ST:n ]Subcategory: Petramand[ST:n ]Appears: Always"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_5"),
Data("Completed mission \"Soldier of the Harriers.\""),
Data("Completed mission \"Hair Apparent.\"[ST:n ]Clearing out the stray potamus was only[ST:n ]the start of one funny episode..."),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 3_2"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_6"),
Data("Enemy: Luxaar's Xern[ST:n ]Subcategory: Xern[ST:n ]Appears: Always"),
Data("Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 5"),
Data("Completed mission \"Law and Orders.\""),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3_2"),
Data("Completed mission \"Serial Thriller.\""),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 5"),
Data("Completed mission \"It's-a Mia!\""),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3_2"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4_8"),
Data("Completed mission \"Good Fortun.\""),
Data("Enemy: Gesserith, the Wileworm[ST:n ]Subcategory: Sabula[ST:n ]Appears: When Atreides the Distinguished[ST:n ]is present."),
Data("Enemy: Ramus, the Supersonic[ST:n ]Subcategory: Aetrygon[ST:n ]Appears: Always"),
Data("Enemy: Ignit, the Ultimate Chaos[ST:n ]Subcategory: Coronid[ST:n ]Appears: Crimson auroras"),
Data("Enemy: Lockhart, the Killer of Hope[ST:n ]Subcategory: Vivohast[ST:n ]Appears: Rarely"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3_4"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_5"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4_1"),
Data("Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3_3"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3_3"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4_6"),
Data("Enemy: Man'an, the Water Whisperer[ST:n ]Subcategory: Arenatect[ST:n ]Appears: Always"),
Data("Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4_3"),
Data("Enemy: Thaddaeus, the Ultramafic[ST:n ]Subcategory: Cinicula[ST:n ]Appears: Always"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_7"),
Data("Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2_8"),
Data("Completed mission \"Special Delivery.\""),
Data("Completed mission \"The Duel (Part III).\""),
Data("Completed mission \"Brotherly Love.\""),
Data("Enemy: Sadar's Qmoeva[ST:n ]Subcategory: Qmoeva[ST:n ]Appears: Daytime"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4_2"),
Data("Completed mission \"Leaving the Nest.\""),
Data("Enemy: Clara, the Pure White[ST:n ]Subcategory: Ovis[ST:n ]Appears: Daytime"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_8"),
Data("Completed mission \"Orphe Pluck.\""),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 2_2"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3_4"),
Data("Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4_3"),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4_9"),
Data("Completed mission \"The Sword of[ST:n ]Legendaryness.\""),
Data("Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2_3"),
Data("Enemy: Oc-serv, the Ancient[ST:n ]Subcategory: Oc-serv[ST:n ]Appears: Always"),
Data("Completed Lin's affinity mission[ST:n ]\"The Repair Job.\""),
Data("Lin can often be found here."),
Data("Completed Vandham's affinity mission[ST:n ]\"A Day in the Life.\""),
Data("Completed Elma's affinity mission[ST:n ]\"Then and Now.\""),
Data("Completed Lin and Tatsu's affinity mission[ST:n ]\"To Serve Nopon.\""),
Data("Name: Elma[ST:n ]Affinity: 5[ST:n ]Appears: Night[ST:n ]Requirements: View 4th heart-to-heart"),
Data("Completed Nagi's affinity mission[ST:n ]\"Nagi's Time.\""),
Data("Completed Chausson's affinity mission[ST:n ]\"A Challenger Approaches.\""),
Data("Name: Nagi[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart"),
Data("Completed Elma's affinity mission[ST:n ]\"We Were Soldiers.\""),
Data("Elma can often be found here."),
Data("Completed Lin and Vandham's affinity mission[ST:n ]\"Two Peas in a Pod.\""),
Data("Completed Irina's affinity mission[ST:n ]\"Fathers and Sons.\""),
Data("Completed Tatsu's affinity mission[ST:n ]\"BFFs.\""),
Data("Completed Chausson's affinity mission[ST:n ]\"Prospective Partners.\""),
Data("Completed Lao's affinity mission[ST:n ]\"A Friend in Need.\""),
]
# use helper
# id: https://xenoblade.github.io/xbx/bdat/common_local_us/SEG_NormalList.html
# text: https://xenoblade.github.io/xbx/bdat/common_ms/SEG_Segment_ms.html
