"""
YAML Creator - Dynamic form generation for Archipelago games (Simple Parser Version)

Uses text-based parsing to avoid Archipelago dependencies.
"""

import yaml
import logging
from typing import Dict, Any
from parse_game_options_simple import get_game_options as parse_game_options, get_all_games

logger = logging.getLogger(__name__)


def get_game_options(game_slug: str) -> Dict[str, Any]:
    """
    Get options for a specific game using simple parser

    Returns dict with game info and options
    """
    try:
        options = parse_game_options(game_slug)

        if 'error' in options:
            return options

        # Format for frontend - group all options under "Game Options"
        return {
            'game_slug': game_slug,
            'game_name': game_slug.replace('_', ' ').title(),
            'option_groups': {
                'Game Options': options
            }
        }
    except Exception as e:
        logger.error(f"Error getting game options for {game_slug}: {e}")
        return {'error': str(e)}


def form_data_to_yaml(game_slug: str, form_data: Dict[str, str]) -> str:
    """
    Convert form data to Archipelago YAML format

    Args:
        game_slug: Game identifier
        form_data: Form field values from POST request

    Returns:
        YAML string
    """
    # Get player name
    player_name = form_data.get('name', 'Player')

    # Get game name for YAML
    game_name = game_slug.replace('_', ' ').title()

    # Build YAML dict
    yaml_dict = {
        'name': player_name,
        'game': game_name,
        'description': f'Generated by SekaiLink for {game_name}'
    }

    # Add game-specific options
    game_options = {}

    for key, value in form_data.items():
        # Skip special fields
        if key in ['name', 'intent', 'description']:
            continue

        # Convert value to appropriate type
        if value == '':
            continue

        # Try to convert to int
        try:
            value = int(value)
        except ValueError:
            pass

        game_options[key] = value

    # Add game options section
    yaml_dict[game_name] = game_options

    # Convert to YAML string
    yaml_string = yaml.dump(yaml_dict, default_flow_style=False, allow_unicode=True, sort_keys=False)

    return yaml_string


def validate_and_save_yaml(user_id: str, game_slug: str, yaml_content: str, db_session) -> Dict[str, Any]:
    """
    Validate and save YAML to database

    Args:
        user_id: User ID
        game_slug: Game slug
        yaml_content: YAML content string
        db_session: Database session

    Returns:
        Dict with success status and message
    """
    from models import YamlFile

    try:
        # Parse YAML to validate
        yaml_data = yaml.safe_load(yaml_content)

        if not yaml_data:
            return {'success': False, 'error': 'Invalid YAML - empty content'}

        # Get player name for filename
        player_name = yaml_data.get('name', 'player')
        filename = f"{player_name}_{game_slug}.yaml"

        # Check if file already exists
        existing = YamlFile.query.filter_by(user_id=user_id, filename=filename).first()
        if existing:
            # Update existing
            existing.content = yaml_content
            existing.game = yaml_data.get('game', game_slug)
        else:
            # Create new
            new_yaml = YamlFile(
                user_id=user_id,
                filename=filename,
                content=yaml_content,
                game=yaml_data.get('game', game_slug)
            )
            db_session.add(new_yaml)

        db_session.commit()

        return {
            'success': True,
            'message': 'YAML saved successfully',
            'filename': filename
        }

    except yaml.YAMLError as e:
        return {'success': False, 'error': f'Invalid YAML syntax: {str(e)}'}
    except Exception as e:
        logger.error(f"Error saving YAML: {e}")
        return {'success': False, 'error': f'Failed to save YAML: {str(e)}'}
