ScriptHost:LoadScript("scripts/item_spec/class.lua")
ScriptHost:LoadScript("scripts/item_spec/custom_item.lua")
ScriptHost:LoadScript("scripts/item_spec/figurine.lua")
ScriptHost:LoadScript("scripts/item_spec/SwordToggle.lua")
ScriptHost:LoadScript("scripts/item_spec/SwordProgress.lua")
ScriptHost:LoadScript("scripts/item_spec/SwordOptions.lua")
local figurine10 = FigurineButton("figurine plus 10", "figurine10", 10, "images/options/figurine10.png")
local figurine50 = FigurineButton("figurine plus 50", "figurine50", 50, "images/options/figurine50.png")
local figurinemax = FigurineButton("figurine plus 136", "figurinemax", 136, "images/options/figurineMax.png")
smithsword = ToggleItem("Smith's Sword", "smithsword", "images/items/Smith's Sword.png")
greensword = ToggleItem("Smith's Sword", "greensword", "images/items/Green Sword.png")
redsword = ToggleItem("Smith's Sword", "redsword", "images/items/Red Sword.png")
bluesword = ToggleItem("Smith's Sword", "bluesword", "images/items/Blue Sword.png")
foursword = ToggleItem("Smith's Sword", "foursword", "images/items/Four Sword.png")
sword = SwordProgress("progression sword", "sword0")
progression = SwordOptions("progression", "progression", "images/options/progression.png")
