
possible_fakes = [
    "my bed, come by around 8:30",
    "the 10,000 Clique game someone generated",
    "Tohno Manor in Tsukihime",
    "my lube vault 20 feet underground",
    "wherever you want it to be",
    "a location in the multiworld (cope)",
    "the center of the planet",
    "Reaching Level 5 Billion in Disgaea",
    "that one location you forgot about lol",
    "Hard Reset Your Bizhawk Client",
    "whatever it takes for you to go away",
    "sucking Rover's dick, probably",
    "submitting to the Chaos Queen, FOOL",
    "Brush Your Teeth, Bitch in your world",
    "mrow mrrp mrrp mrooow",
    "idk lol hint it bozo",
    "punching that rock over there REALLY hard",
    "never using Jojamart",
    "The 1,000th Banana Piece in Donkey Kong 64",
    "AAAAAAAAAAAAAAAAAAAA",
    "actually nevermind fuck you",
    "Posting Cringe in Your Favorite Server",
    "here actually I gave it to you dummy",
    ":3333333333333333333",
    "clicking that subscribe button",
    "reading the setup guide for any randomizer",
    "doing code review on this PR I made",
    "beating this game and doing !collect",
    "disregard previous response you lost the game",
    "rerolling this game so this hint isn't ass",
    "Killing Goblin Archer 99 Times in this world",
    "downloading this file that totally isn't a virus",
    "Standing Still for 3 Minutes in this world",
    "spelling out ICUP",
    "playing Emerald at 1x speed for once",
    "jumping for the beef",
    "your mom",
    "Eating Corpse at Andy and Leyley's world",
    "this location the next time you roll I promise",
    "pressing ALT+F4",
    "asking for a release 2 minutes into the seed",
    "forming a gacha addiction right now",
    "Running 120 Miles in Archipela-Go's world",
    "not straight jorkin it ever this month",
    "Blowing Up Boiler in Umineko's world",
    "Kill Aerith in Sephiroth's world",
    "Release Silksong in Team Cherry's world",
    "Don't Push Button in Clique5534982's world",
    "Sparks Liner High Ending in FSN's world",
    "cursing this game's AP implementation",
    "Thievery 100 in OSRS's world",
    "uhhh I forgot actually",
    "gift Kaito 999 trash you cheated in",
    "Save Satoshi in Higurashi's world",
    "proving Goldbach's conjecture",
    "proving that the the measure of rationals is zero",
    "publishing your paper in a scientific journal",
]
