import json
import sys

# flake8: noqa
replacement = [
"Name: Celica[ST:n ]Affinity: 5[ST:n ]Appears: Night[ST:n ]Requirements: View 4th heart-to-heart",
"Name: Nagi[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: Complete 1st heart-to-heart",
"Mission: The Gauntlet[ST:n ]Client: Zo Ozuchi",
"Mission: Two Warriors[ST:n ]Client: Go Belg",
"Mission: Data Probe Challenge[ST:n ]Client: Hugo",
"Mission: Good Fortun[ST:n ]Client: HT665: Erio",
"Name: Celica[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart",
"Completed Celica and Rock's affinity mission[ST:n ]\"New in New LA.\"",
"Celica can often be found here.",
"Mission: Yardley's Scheme[ST:n ]Client: Yardley",
"Mission: Off the Record[ST:n ]Client: ???",
"Completed Gwin's affinity mission[ST:n ]\"Boot Camp.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed Lin's affinity mission[ST:n ]\"A Girl's Wings.\"",
"Mission: Muimui's Meltdown[ST:n ]Client: Moimoi",
"Mission: Turf War[ST:n ]Client: Enrai",
"Name: Doug[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: The Pip-Squeak[ST:n ]Client: Matthew",
"Name: Murderess[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: Forest Foray[ST:n ]Client: Sullivan",
"Mission: Pollution Solution[ST:n ]Client: Liza",
"Mission: Good Neighbors[ST:n ]Client: Tan'celeg",
"Name: Irina[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Name: Lin[ST:n ]Affinity: 1[ST:n ]Appears: Night",
"Mission: Data Probe Breakthrough[ST:n ]Client: Hugo",
"Mission: Data Probe Revolution[ST:n ]Client: Hugo",
"Name: Elma[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Mission: Lone Survivors[ST:n ]Client: Robert",
"Mission: Entrepreneurial Spirit[ST:n ]Client: Tobias",
"Mission: Child of Mira[ST:n ]Client: Orleron",
"Object: Container[ST:n ]Required Field Skill: Mechanical Level 3",
"Mission: Orphe Pluck[ST:n ]Client: San'luarb",
"Mission: Data Probe Progress[ST:n ]Client: Hugo",
"Mission: Data Probe Evolution[ST:n ]Client: Hugo",
"Mission: A Proper Chopper[ST:n ]Client: Roscoe",
"Mission: Professorial[ST:n ]Client: Veven",
"Mission: Rise of the Blood Lobster[ST:n ]Client: The Blood Lobster",
"Name: Mia[ST:n ]Affinity: 3[ST:n ]Appears: Late Night[ST:n ]Requirements: View 2nd heart-to-heart",
"Name: Hope[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: Pack It In[ST:n ]Client: Nococche",
"Name: Irina[ST:n ]Affinity: 1[ST:n ]Appears: Night",
"Name: Frye [ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Alexa can often be found here.",
"Name: Celica[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Mission: Mystery Man[ST:n ]Client: Professor B",
"Mission: The Voltant Visionary[ST:n ]Client: Trachlo Lythren",
"Name: Horonalderon[ST:n ]Situation: He was saved by a squad[ST:n ]of rather odd characters outside.",
"Frye can often be found here.",
"Mission: The Good Thief[ST:n ]Client: Horonalderon",
"Completed Celica and Rock's affinity mission[ST:n ]\"Fitting In.\"",
"Mission: Professor B's Return[ST:n ]Client: Veven",
"Mission: Gold Rush[ST:n ]Client: Adolphus",
"Name: Frye[ST:n ]Affinity: 1[ST:n ]Appears: Late Night",
"Completed Frye's affinity mission[ST:n ]\"Bottoms Up.\"",
"Mission: Going Viral[ST:n ]Client: Julius",
"Name: Gwin[ST:n ]Affinity: 5[ST:n ]Appears: Evening[ST:n ]Requirements: View 4th heart-to-heart,[ST:n ]Irina must not be in the party",
"Mission: Alien Nation[ST:n ]Client: Alex",
"Name: Lin[ST:n ]Affinity: 2[ST:n ]Appears: Afternoon[ST:n ]Pet: Dog[ST:n ]Requirements: View 1st heart-to-heart",
"Name: Mia[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart",
"Bozé can often be found here.",
"Name: Celica[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart",
"Object: Container[ST:n ]Required Field Skill: Mechanical Level 2",
"Mission: Stop, Thief![ST:n ]Client: Shiraton",
"Mission: A Dubious Operation[ST:n ]Client: Shiraton",
"Name: Mia[ST:n ]Affinity: 2[ST:n ]Appears: Late Night[ST:n ]Requirements: View 1st heart-to-heart",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Name: Phog[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Mission: A Hero's Ride[ST:n ]Client: Justin",
"Mission: Better Latte Than Never[ST:n ]Client: Jo",
"Name: Doug[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Name: Quiquat[ST:n ]Situation: This Ma-non is set on learning[ST:n ]about FrontierNav.",
"Name: Lin[ST:n ]Affinity: 4[ST:n ]Appears: Evening[ST:n ]Requirements: View 3rd heart-to-heart",
"Mission: Emotion Commotion[ST:n ]Client: Chiopitus",
"Completed Lao's affinity mission[ST:n ]\"The Matchmaker.\"",
"Mission: Definian Downfall[ST:n ]Client: HT665: Erio",
"Name: Irina[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Name: Veverta[ST:n ]Situation: She dropped her device somewhere[ST:n ]and is in a fix.",
"Completed Gwin's affinity mission[ST:n ]\"Nine Lives.\"",
"Completed Irina's affinity mission[ST:n ]\"Renewed Will.\"",
"Mission: The Fashionista[ST:n ]Client: Victoria",
"Name: L[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Name: Nagi[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: Sparking a Smile[ST:n ]Client: Ngogo",
"Mission: Unsatisfied Customer[ST:n ]Client: Chiroro",
"Mission: No Ma-non Need Apply[ST:n ]Client: Wersal",
"Mission: Planetary Pioneer (Part III)[ST:n ]Client: Kirsty",
"Yelv can often be found here.",
"Mission: The Sword of Legendaryness[ST:n ]Client: Muimui",
"Name: Murderess[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart",
"Completed the Murderess's affinity mission[ST:n ]\"Serial Thriller.\"",
"Name: Frye[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Mission: My Angel, My Lana[ST:n ]Client: Bubu",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3",
"Name: Hope[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Mission: Trade Agreement[ST:n ]Client: Warawa",
"Completed Tatsu's affinity mission[ST:n ]\"The Ties That Bind.\"",
"Name: L[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Name: Beats[ST:n ]Situation: He seems to be looking for[ST:n ]some kind of manuscript data.",
"Mission: Murder Most Foul[ST:n ]Client: Ackwar",
"Mission: Wrothian Innovation[ST:n ]Client: Go Sirho",
"Name: Hope[ST:n ]Affinity: 2[ST:n ]Appears: Evening[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: A Dish Served Cold[ST:n ]Client: Zo Langra",
"Name: Elma[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: Forbidden Love[ST:n ]Client: Loda Gorida",
"Mission: No-Show Nen'celeg[ST:n ]Client: Nan'celeg",
"Mission: Gorkwa Games[ST:n ]Client: Troylan",
"Mission: House Call[ST:n ]Client: Nan'celeg",
"Mission: A New Life[ST:n ]Client: Bazis Wolfen",
"Mission: Here Come the Brides[ST:n ]Client: Nemard Wolfen",
"Mission: The Unbreakable Sword[ST:n ]Client: De Zing",
"Mission: A Grim Undertaking[ST:n ]Client: Hala Gorida",
"Name: L[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: The Lurker[ST:n ]Client: Go Rogan",
"Mission: Snipe Hunt[ST:n ]Client: Bihabba",
"Mia can often be found here.",
"Mission: Sun'celeg Rises[ST:n ]Client: Sun'barac",
"Name: Zurranik[ST:n ]Situation: Rumor has it he received a large[ST:n ]sum of money from a suspicious Wrothian...",
"Mission: The Membership[ST:n ]Client: May May",
"Mission: Tree-mendous[ST:n ]Client: Sevvy Belgazus",
"Name: Elma[ST:n ]Affinity: 4[ST:n ]Appears: Evening[ST:n ]Requirements: View 3rd heart-to-heart",
"Mission: The Old Gods[ST:n ]Client: Feloran",
"Mission: An Ancient Legend[ST:n ]Client: Nimu Turton",
"Mission: Training Day[ST:n ]Client: Zarch Quokett",
"Mission: The Art of War[ST:n ]Client: Sajif Scoppio",
"Mission: Slovity's Revenge[ST:n ]Client: Slovity Pagus",
"Mission: The Party Line[ST:n ]Client: Sun'barac",
"Name: Phog[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Mission: Circle of Life[ST:n ]Client: Kon'luarb",
"Phog can often be found here.",
"Name: Lin[ST:n ]Affinity: 5[ST:n ]Appears: Morning[ST:n ]Requirements: View 4th heart-to-heart",
"Mission: Off the Record[ST:n ]Client: ???",
"Name: Phog[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Requirements: View 2nd heart-to-heart",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Name: Gwin[ST:n ]Affinity: 2[ST:n ]Appears: Late Night[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: Herbivores, Unite![ST:n ]Client: Naza Tenpanzi",
"Completed Hope's affinity mission[ST:n ]\"A Present for Hope.\"",
"Mission: The Celeste Three[ST:n ]Client: Fosdyke",
"Name: L[ST:n ]Affinity: 5[ST:n ]Appears: Early Morning[ST:n ]Requirements: View 4th heart-to-heart",
"Name: Celica[ST:n ]Affinity: 2[ST:n ]Appears: Morning[ST:n ]Requirements: View 1st heart-to-heart",
"Name: Doug[ST:n ]Affinity: 3[ST:n ]Appears: Daytime[ST:n ]Requirements: View 2nd heart-to-heart",
"Name: Gwin[ST:n ]Affinity: 3[ST:n ]Appears: Late Night[ST:n ]Requirements: View 2nd heart-to-heart",
"Name: Frye[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: The Line of Fire[ST:n ]Client: Alice",
"Hope can often be found here.",
"Mission: Planetary Pioneer (Part V)[ST:n ]Client: Kirsty",
"Name: Gwin[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Dog[ST:n ]Requirements: View 3rd heart-to-heart",
"Name: Mia[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Name: Hope[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Dog[ST:n ]Requirements: View 3rd heart-to-heart",
"Name: Phog[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Completed Phog's affinity mission[ST:n ]\"Foggy Dilemma.\"",
"Name: Murderess[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Name: Murderess[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 3rd heart-to-heart",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3",
"Name: Doug[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon[ST:n ]Pet: Dog",
"Mission: Bread and a Circus[ST:n ]Client: Moimoi",
"Name: Elma[ST:n ]Affinity: 2[ST:n ]Appears: Night[ST:n ]Pet: Cat[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: New Frontier[ST:n ]Client: Kirsty",
"Mission: Off the Record[ST:n ]Client: ???",
"Name: Mia[ST:n ]Affinity: 1[ST:n ]Appears: Late Night",
"Name: Caroline[ST:n ]Situation: She was the victim of an Orphean[ST:n ]breaking and entering.",
"Mission: Alex's Last Stand[ST:n ]Client: Eliza",
"Name: Phog[ST:n ]Affinity: 2[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 1st heart-to-heart",
"Name: Kon'luarb[ST:n ]Situation: Apparently he is digging up info on[ST:n ]the water plant.",
"Mission: Lakeside Getaway[ST:n ]Client: Rosie",
"Mission: Water Woes[ST:n ]Client: Ajoa",
"Name: Irina[ST:n ]Affinity: 2[ST:n ]Appears: Evening[ST:n ]Pet: Dog[ST:n ]Requirements: View 1st heart-to-heart",
"Name: L[ST:n ]Affinity: 3[ST:n ]Appears: ---[ST:n ]Pet: Cat[ST:n ]Requirements: View 2nd heart-to-heart",
"Name: Murderess[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Name: Wendy[ST:n ]Situation: A Nopon salesman is giving[ST:n ]her trouble.",
"Name: Nagi[ST:n ]Affinity: 5[ST:n ]Appears: Afternoon[ST:n ]Requirements: View 4th heart-to-heart",
"H.B. can often be found here.",
"Completed Hope's affinity mission[ST:n ]\"Hope Springs Eternal.\"",
"Mission: The Miracle Maker[ST:n ]Client: Staccata",
"Mission: The Divine Nopopon[ST:n ]Client: Shinshin",
"Completed Phog's affinity mission[ST:n ]\"A Great Divide.\"",
"Mission: The Bug Whisperer[ST:n ]Client: Min'barac",
"Mission: Shotgun Diplomacy[ST:n ]Client: Eliza",
"Name: Letrick[ST:n ]Situation: He is searching for whoever it was[ST:n ]that dropped by the cathedral in his absence.",
"Mission: Rites of Ruin[ST:n ]Client: Jalimbo",
"Mission: Definian Love[ST:n ]Client: Lyvia[ST:n ]or[ST:n ]Mission: Fortun and Glory[ST:n ]Client: Erio",
"Name: Phoskeran[ST:n ]Situation: Predicting the future is his[ST:n ]new hobby.",
"Object: Container[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Trailer[ST:n ]Required Field Skill: Mechanical Level 3",
"Mission: A Fateful Choice[ST:n ]Client: On'tonam",
"Mission: The Journey Begins[ST:n ]Client: Kun'luarb",
"Name: Hope[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Mission: The Duel (Part II)[ST:n ]Client: Gi Zang",
"Nagi can often be found here.",
"Mission: Cavern Crushers[ST:n ]Client: Stella",
"Mission: Attack on Biahno Hills[ST:n ]Client: Lara Nara",
"Mission: Dead Men Tell No Tales[ST:n ]Client: Stella",
"Mission: Prone Sweet Prone[ST:n ]Client: Stella",
"Object: Trailer[ST:n ]Required Field Skill: Mechanical Level 2",
"Name: Gwin[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Name: Irina[ST:n ]Affinity: 3[ST:n ]Appears: Morning[ST:n ]Requirements: View 2nd heart-to-heart",
"Doug can often be found here.",
"Object: Large Container[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed Celica and Rock's affinity mission[ST:n ]\"Manhunt.\"",
"Completed Chausson's affinity mission[ST:n ]\"Spy Games.\"",
"Mission: Rescue at the Ensconced Citadel[ST:n ]Client: Julius",
"Mission: The Ultimate Price[ST:n ]Client: Quincy",
"Mission: The Handy Ma-non[ST:n ]Client: Sostenasa",
"Completed the Murderess's affinity mission[ST:n ]\"My Dream.\"",
"Name: Cedric[ST:n ]Situation: He seems to be under pressure[ST:n ]to run an errand.",
"Completed L's affinity mission[ST:n ]\"The Nopon Heir.\"",
"L can often be found here.",
"Mission: That's In-Credible![ST:n ]Client: Tutura",
"Completed Nagi's affinity mission[ST:n ]\"Reporting for Duty.\"",
"Completed Hope's affinity mission[ST:n ]\"A False Hope.\"",
"Mission: Planetary Pioneer (Part II)[ST:n ]Client: Kirsty",
"Name: Nopopon[ST:n ]Situation: Word is a Nopon ghost roams[ST:n ]the administrative district late at night.",
"Mission: Mamma Mia![ST:n ]Client: Mia",
"Completed Mia's affinity mission[ST:n ]\"Mia Grows Up.\"",
"Completed Frye and Phog's affinity mission[ST:n ]\"Brotherly Love.\"",
"Name: Doug[ST:n ]Affinity: 5[ST:n ]Appears: ---[ST:n ]Requirements: View 4th heart-to-heart",
"Completed L's affinity mission[ST:n ]\"L's Conundrum.\"",
"Mission: Booming Business[ST:n ]Client: L",
"Mission: Lend an Ear[ST:n ]Client: Gu Ladha",
"Mission: Setting Forth[ST:n ]Client: Muimui",
"Name: Nagi[ST:n ]Affinity: 1[ST:n ]Appears: Afternoon",
"Mission: Planetary Pioneer (Part IV)[ST:n ]Client: Kirsty",
"Mission: Waste Not, Want Not [ST:n ]Client: Lara Mara",
"Mission: Skell License[ST:n ]Client: Vandham",
"Name: Frye[ST:n ]Affinity: 2[ST:n ]Appears: Nighttime[ST:n ]Requirements: View 1st heart-to-heart",
"Mission: House of Cards[ST:n ]Client: Yardley",
"Mission: White Lifehold[ST:n ]Client: Lara Mara",
"Mission: BLADE Level Basics[ST:n ]Client: Eleonora",
"Completed Doug's affinity mission[ST:n ]\"Soldier of the Harriers.\"",
"Mission: The Probe-fessional[ST:n ]Client: Kirsty",
"Mission: The Duel (Part III)[ST:n ]Client: Gi Zang",
"Completed the Murderess's affinity mission[ST:n ]\"The Little Rich Girl.\"",
"Lao can often be found here.",
"Gwin can often be found here.",
"Mission: City Saviors[ST:n ]Client: Carl",
"Completed Doug's affinity mission[ST:n ]\"Close Comrades.\"",
"Mission: Planetary Pioneer (Part I)[ST:n ]Client: Kirsty",
"Name: Wolf[ST:n ]Situation: He seems to be recruiting[ST:n ]non-human BLADE operatives.",
"Mission: Ovah and Out[ST:n ]Client: Han'barac",
"Mission: Cooking Schooled[ST:n ]Client: Sherry",
"Mission: Mia Is Missing![ST:n ]Client: Mia",
"Mission: Unknown Assailant[ST:n ]Client: Raleigh",
"Mission: Frontier Spirit[ST:n ]Client: Corwin",
"Name: Lin[ST:n ]Affinity: 3[ST:n ]Appears: Afternoon[ST:n ]Requirements: View 2nd heart-to-heart",
"Mission: Close Encounters[ST:n ]Client: Sarona",
"Mission: The Root of All Evil[ST:n ]Client: Tobias",
"Irina can often be found here.",
"The Murderess can often be found here.",
"Mission: Myles to Go[ST:n ]Client: Satie",
"Mission: Slovity's Rampage[ST:n ]Client: Trigo Bambott",
"Completed Frye and Phog's affinity mission[ST:n ]\"Blitzkrieg.\"",
"Enemy: Caesar, the Hundred-Eyed[ST:n ]Subcategory: Petramand[ST:n ]Appears: Always",
"Completed mission \"Snipe Hunt.\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 5",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Enemy: Celestin, the Spring Storm[ST:n ]Subcategory: Progen[ST:n ]Appears: Always",
"Completed mission \"The Repair Job.\"",
"Completed mission \"The Queen Is Dead.\"",
"Object: Strange Insect Nest[ST:n ]Required Field Skill: Biological Level 1",
"Enemy: Zdenka, the Raucous[ST:n ]Subcategory: Saltat[ST:n ]Appears: Always",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Enemy: Sapara, the Laconic[ST:n ]Subcategory: Saltat[ST:n ]Appears: Rarely",
"Completed mission \"A Day in the Life.\"",
"Completed mission \"Haywire!\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"Forbidden Love.\"",
"Enemy: Bohdan, the Mistral[ST:n ]Subcategory: Auravis[ST:n ]Appears: Daytime",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"Cinicula Assault.\"",
"Completed mission \"Renewed Will.\"",
"Enemy: Casper, the Unhealthy Eater[ST:n ]Subcategory: Blatta[ST:n ]Appears: Nighttime",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 5",
"Completed mission \"The Lurker.\"",
"Enemy: Eckart, the Indestructible[ST:n ]Subcategory: Cinicula[ST:n ]Appears: Always",
"Enemy: Ridill, the Arrogant[ST:n ]Subcategory: Lophid[ST:n ]Appears: Rarely",
"Enemy: Necro, the Cavelord[ST:n ]Subcategory: Vesper[ST:n ]Appears: Always",
"Enemy: Experimental Composite Qmoeva[ST:n ]Subcategory: Qmoeva[ST:n ]Appears: Nighttime",
"Completed mission \"City Saviors.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1",
"Enemy: Dieter, the Epicure[ST:n ]Subcategory: Grex[ST:n ]Appears: Always",
"Enemy: Daril, the Eradicator[ST:n ]Subcategory: Marnuck[ST:n ]Appears: Nighttime",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"The Good Thief.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 3",
"Enemy: Mesgen, the Fairweathered[ST:n ]Subcategory: Potamus[ST:n ]Appears: Always",
"Completed mission \"Close Encounters.\"",
"Completed mission \"Nagi's Time.\"",
"Enemy: Shatskikh, the Flash[ST:n ]Subcategory: Xiphias[ST:n ]Appears: Rarely",
"Completed mission \"Welcome Back, Conner.\"",
"Completed mission \"Here Come the Brides.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"An Ancient Legend.\"",
"Completed mission \"We Were Soldiers.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2",
"Enemy: Etutanne, the Bloodthirsty[ST:n ]Subcategory: Adsecula[ST:n ]Appears: Always",
"Enemy: Hephaestus, the Absconder[ST:n ]Subcategory: Duoguill[ST:n ]Appears: Nighttime",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"Nine Lives.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Gugli, the Relentless[ST:n ]Subcategory: Suid[ST:n ]Appears: Always",
"Enemy: Luciel, the Eternal[ST:n ]Subcategory: Millesaur[ST:n ]Appears: Always",
"Enemy: Eutropio, the Sea Rumble[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always",
"Completed mission \"A Dubious Operation.\"",
"Completed mission \"Muimui's Meltdown.\"",
"Completed mission \"Training Day.\"",
"Completed mission \"A False Hope.\"",
"Enemy: Bogdan, the Dense[ST:n ]Subcategory: Suid[ST:n ]Appears: Always",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3",
"Completed mission \"Stop, Thief!\"",
"Enemy: Ji-ett, the Thunderclap[ST:n ]Subcategory: Fal-swo[ST:n ]Appears: Nighttime",
"Enemy: Rajidi, the Cumuliform[ST:n ]Subcategory: Balaena[ST:n ]Appears: Rarely",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 5",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"A Fateful Choice.\"",
"Completed mission \"The Nopon Heir.\"",
"Enemy: Planetes, the Torrential[ST:n ]Subcategory: Unafulge[ST:n ]Appears: Always",
"Completed mission \"Prospective Partners.\"",
"Enemy: Pyotr, the Shepherd[ST:n ]Subcategory: Sylooth[ST:n ]Appears: Always",
"Completed mission \"House Call.\"",
"Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 4",
"Completed mission \"Frontier Spirit.\"",
"Enemy: Froste, the Courteous[ST:n ]Subcategory: Vesper[ST:n ]Appears: Always",
"Enemy: Telethia, the Endbringer[ST:n ]Subcategory: Telethia[ST:n ]Appears: Always[ST:n ][ST:n ](Must be defeated in a non-mission encounter.)",
"Enemy: Joker, the Unknowable[ST:n ]Subcategory: Blatta[ST:n ]Appears: Always",
"Enemy: Frajeel, the Purgatorial[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always",
"Completed mission \"The Art of War.\"",
"Completed mission \"Rescue at the[ST:n ]Ensconced Citadel.\"",
"Completed mission \"My Dream.\"",
"Enemy: Katerina, the Cliffhanger[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always",
"Enemy: Schneider, the Cliffpercher[ST:n ]Subcategory: Forfex[ST:n ]Appears: Always",
"Completed mission \"The Voltant Visionary.\"",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"Circle of Life.\"",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"No-show Nen'celeg.\"",
"Object: Trailer Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"Dodonga Caravan.\"",
"Completed mission \"Manhunt.\"",
"Enemy: Demetrio, the Tempestuous[ST:n ]Subcategory: Simius[ST:n ]Appears: Always",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Close Comrades.\"",
"Completed mission \"A Proper Chopper.\"",
"Completed mission \"Dead Men Tell No Tales.\"",
"Completed mission \"Murder Most Foul.\"",
"Enemy: Elena, the Infernal[ST:n ]Subcategory: Scirpo[ST:n ]Appears: Fog",
"Enemy: Griffus, the Tartarean[ST:n ]Subcategory: Insidia[ST:n ]Appears: Always",
"Completed mission \"Adventure!\"",
"Enemy: Tormenta, the Scarlet-Clad[ST:n ]Subcategory: Turba[ST:n ]Appears: Always",
"Completed mission \"Lone Survivors.\"",
"Enemy: Sarcosuchus, the Iron-Eater[ST:n ]Subcategory: Dilus[ST:n ]Appears: Always",
"Object: Strange Tree[ST:n ]Required Field Skill: Biological Level 1",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"The Duel (Part II).\"",
"Enemy: Clemente, the Iron Meteor[ST:n ]Subcategory: Falsaxum[ST:n ]Appears: Always",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 1",
"Completed mission \"Missing in Action.\"",
"Enemy: Desdemona, the Subterranean[ST:n ]Subcategory: Scirpo[ST:n ]Appears: Always",
"Enemy: Buchwald, the Guardian[ST:n ]Subcategory: Virago[ST:n ]Appears: Always",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"Data Miner.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Melanya, the Sound Sleeper[ST:n ]Subcategory: Suid[ST:n ]Appears: Always",
"Completed mission \"Sun'celeg Rises.\"",
"Enemy: Gotthard, the Intimidating[ST:n ]Subcategory: Auravis[ST:n ]Appears: Always",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 4",
"Enemy: Germaine, the Treasure Keeper[ST:n ]Subcategory: Ovis[ST:n ]Appears: Always",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Enemy: Vendura, the Spellbinder[ST:n ]Subcategory: Prone (Cavern Clan)[ST:n ]Appears: Daytime",
"Enemy: Libra, the Long-Lived[ST:n ]Subcategory: Purgovent[ST:n ]Appears: Always",
"Enemy: Jindriska, the Serene[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always",
"Enemy: Barnabas, the Despot[ST:n ]Subcategory: Vigent[ST:n ]Appears: Daytime",
"Completed mission \"A Dish Served Cold.\"",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 2",
"Completed mission \"Prone Sweet Prone.\"",
"Enemy: Edgardo, the Carefree[ST:n ]Subcategory: Thallus[ST:n ]Appears: Always",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Vittorio, the Battle-Scarred[ST:n ]Subcategory: Tectinsula[ST:n ]Appears: Always",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"Foggy Dilemma.\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Ro-darm, the Demon Claw[ST:n ]Subcategory: Oc-serv[ST:n ]Appears: Always",
"Completed mission \"Slovity's Rampage.\"",
"Completed mission \"Mayday.\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Enemy: Hartmut, the Calamity[ST:n ]Subcategory: Millepod[ST:n ]Appears: Always",
"Enemy: Valeriano, the Rolling Thunder[ST:n ]Subcategory: Duoguill[ST:n ]Appears: Electromagnetic storm",
"Completed mission \"A Friend in Need.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Ernest, the Contemplative[ST:n ]Subcategory: Progen[ST:n ]Appears: Always",
"Enemy: Celedonio, the Battle-Tested[ST:n ]Subcategory: Grex[ST:n ]Appears: Always",
"Object: Indigen Dung[ST:n ]Required Field Skill: Biological Level 2",
"Enemy: Squallo, the Sand Mirer[ST:n ]Subcategory: Sabula[ST:n ]Appears: Daytime",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"Mighty Mia.\"",
"Object: Trailer Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"The Duel (Part I).\"",
"Enemy: Rolf, the Sonorous[ST:n ]Subcategory: Saltat[ST:n ]Appears: Always",
"Enemy: Ludvik, the Picky Eater[ST:n ]Subcategory: Casuari[ST:n ]Appears: Daytime",
"Completed mission \"A Grim Undertaking.\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"The Little Rich Girl.\"",
"Enemy: Elaine, the Lunar Eclipse[ST:n ]Subcategory: Ceto[ST:n ]Appears: Nighttime",
"Completed mission \"A Challenger Approaches.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"Then and Now.\"",
"Enemy: Eliane, the Unmoved[ST:n ]Subcategory: Mortifole[ST:n ]Appears: Always",
"Enemy: Sviatoslav, the Reproachful[ST:n ]Subcategory: Aprica[ST:n ]Appears: Rain",
"Completed mission \"A Great Divide.\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Ferdinand, the Fortuitous[ST:n ]Subcategory: Mephite[ST:n ]Appears: Always",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 4",
"Completed mission \"Bread and a Circus.\"",
"Enemy: Climati, the Chilling Wind[ST:n ]Subcategory: Sylooth[ST:n ]Appears: Always",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 5",
"Completed mission \"Shotgun Diplomacy.\"",
"Enemy: Silvestre, the Morning Light[ST:n ]Subcategory: Levitath[ST:n ]Appears: Always",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"Dorian Caravan.\"",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Object: Indigen Dung[ST:n ]Required Field Skill: Biological Level 3",
"Enemy: Feliciano, the All-Seeing[ST:n ]Subcategory: Sphinx[ST:n ]Appears: Daytime",
"Object: Vehicle Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Enemy: Vilem, the Gold-Scaled[ST:n ]Subcategory: Aetrygon[ST:n ]Appears: Always",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 3",
"Enemy: Bertrand, the Gorge Scourge[ST:n ]Subcategory: Adsecula[ST:n ]Appears: Always",
"Completed mission \"The Trading Floor.\"",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"Spy Games.\"",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 1",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Supplies Surprise.\"",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 1",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 5",
"Completed mission \"Gorkwa Games.\"",
"Completed mission \"Sparking a Smile.\"",
"Completed mission \"Slovity's Revenge.\"",
"Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 2",
"Enemy: Kringe, the Hunting Arrow[ST:n ]Subcategory: Caro[ST:n ]Appears: Always",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: White Whale Debris[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"The Bodyguard.\"",
"Completed mission \"My Angel, My Lana.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Definian Downfall.\"",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2",
"Enemy: Coil, the Never-Ending[ST:n ]Subcategory: Scintimure[ST:n ]Appears: Electromagnetic storm",
"Enemy: Prinsipe, the Ravenous[ST:n ]Subcategory: Blatta[ST:n ]Appears: Nighttime",
"Completed mission \"The Old Gods.\"",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Mia Is Missing!\"",
"Completed mission \"The Duel (Part IV).\"",
"Enemy: Chantai's Galdr[ST:n ]Subcategory: Galdr[ST:n ]Appears: Daytime",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Completed mission \"To Serve Nopon.\"",
"Completed mission \"Rites of Ruin.\"",
"Completed mission \"Black Lifehold.\"",
"Enemy: Eisen, the Ebon Rock[ST:n ]Subcategory: Petramand[ST:n ]Appears: Nighttime",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Lionhearted.\"",
"Enemy: Pelicollo, the Panzer[ST:n ]Subcategory: Caecus[ST:n ]Appears: Always",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 3",
"Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 3",
"Enemy: Chantai, the Insect Maiden[ST:n ]Subcategory: Milsaadi[ST:n ]Appears: Nighttime",
"Enemy: Armored Cruiser Seidr[ST:n ]Subcategory: Seidr[ST:n ]Appears: Daytime",
"Enemy: Duran, the Draconian[ST:n ]Subcategory: Marnuck[ST:n ]Appears: Always (except late night)",
"Enemy: Ilithios, the Enlightened[ST:n ]Subcategory: Gularth[ST:n ]Appears: Always (except flaming hail)",
"Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Lifepod[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"A Present for Hope.\"",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 2",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 2",
"Enemy: Terenty, the Blademaster[ST:n ]Subcategory: Ictus[ST:n ]Appears: Always",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 2",
"Completed mission \"Until the End.\"",
"Enemy: Gi-zho, the Iron Deity[ST:n ]Subcategory: Xe-dom[ST:n ]Appears: Always",
"Enemy: Jia Mian, the Beloved[ST:n ]Subcategory: Jacul[ST:n ]Appears: Always",
"Completed mission \"The Queen Is Dead.\"",
"Enemy: Sharnaak, the Technician[ST:n ]Subcategory: Milsaadi[ST:n ]Appears: Nighttime",
"Completed mission \"Alex's Last Stand.\"",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"The Unbreakable Sword.\"",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Object: Indigen Nest[ST:n ]Required Field Skill: Biological Level 3",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Enemy: Yune, the Ambusher[ST:n ]Subcategory: Visigel[ST:n ]Appears: Rarely",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 5",
"Enemy: Behemoth, the Netherdweller[ST:n ]Subcategory: Virago[ST:n ]Appears: Rarely",
"Completed mission \"Lesson from the Grave.\"",
"Completed mission \"Predator and Prey.\"",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 2",
"Completed mission \"Bottoms Up.\"",
"Enemy: Stola, the Champion[ST:n ]Subcategory: Liceor[ST:n ]Appears: Crimson aurora",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Enemy: Alexei, the Jade[ST:n ]Subcategory: Monoceros[ST:n ]Appears: Always",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"Castle in the Sky.\"",
"Enemy: Florence, the Hell Maggot[ST:n ]Subcategory: Germivore[ST:n ]Appears: Nighttime",
"Enemy: Antara, the Water Diviner[ST:n ]Subcategory: Arenatect[ST:n ]Appears: Always",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 3",
"Completed mission \"Plans of Attack.\"",
"Enemy: Radovan, the Sky Baron[ST:n ]Subcategory: Jacul[ST:n ]Appears: Daytime",
"Enemy: Laurencio, the Fog Bow[ST:n ]Subcategory: Filiavent[ST:n ]Appears: Always",
"Enemy: Asana, the Azure Star[ST:n ]Subcategory: Cervus[ST:n ]Appears: Always",
"Completed mission \"The Line of Fire.\"",
"Enemy: Damaged Zig[ST:n ]Subcategory: Zig[ST:n ]Appears: Always",
"Completed mission \"Unknown Assailant.\"",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 5",
"Enemy: Candelario, the Bronze[ST:n ]Subcategory: Petramand[ST:n ]Appears: Always",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"Soldier of the Harriers.\"",
"Completed mission \"Serial Thriller.\"",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Enemy: Luxaar's Xern[ST:n ]Subcategory: Xern[ST:n ]Appears: Always",
"Object: Patrol Chopper Wreckage[ST:n ]Required Field Skill: Mechanical Level 5",
"Completed mission \"Law and Orders.\"",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3",
"Completed mission \"Hair Apparent.\"[ST:n ]Clearing out the stray potamus was only[ST:n ]the start of one funny episode...",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 5",
"Completed mission \"It's-a Mia!\"",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 4",
"Completed mission \"Good Fortun.\"",
"Enemy: Gesserith, the Wileworm[ST:n ]Subcategory: Sabula[ST:n ]Appears: When Atreides the Distinguished[ST:n ]is present.",
"Enemy: Ramus, the Supersonic[ST:n ]Subcategory: Aetrygon[ST:n ]Appears: Always",
"Enemy: Ignit, the Ultimate Chaos[ST:n ]Subcategory: Coronid[ST:n ]Appears: Crimson auroras",
"Enemy: Lockhart, the Killer of Hope[ST:n ]Subcategory: Vivohast[ST:n ]Appears: Rarely",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 3",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4",
"Object: Skell Wreckage[ST:n ]Required Field Skill: Mechanical Level 3",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 4",
"Enemy: Man'an, the Water Whisperer[ST:n ]Subcategory: Arenatect[ST:n ]Appears: Always",
"Object: Alien Reliquary[ST:n ]Required Field Skill: Archaeological Level 4",
"Enemy: Thaddaeus, the Ultramafic[ST:n ]Subcategory: Cinicula[ST:n ]Appears: Always",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Object: Alien Wreckage[ST:n ]Required Field Skill: Archaeological Level 2",
"Completed mission \"Special Delivery.\"",
"Completed mission \"The Duel (Part III).\"",
"Completed mission \"Brotherly Love.\"",
"Enemy: Sadar's Qmoeva[ST:n ]Subcategory: Qmoeva[ST:n ]Appears: Daytime",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4",
"Completed mission \"Leaving the Nest.\"",
"Enemy: Clara, the Pure White[ST:n ]Subcategory: Ovis[ST:n ]Appears: Daytime",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"Orphe Pluck.\"",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 2",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 3",
"Object: Strange Petrified Tree[ST:n ]Required Field Skill: Biological Level 4",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 4",
"Completed mission \"The Sword of[ST:n ]Legendaryness.\"",
"Object: Alien Container[ST:n ]Required Field Skill: Archaeological Level 2",
"Enemy: Oc-serv, the Ancient[ST:n ]Subcategory: Oc-serv[ST:n ]Appears: Always",
"Completed Lin's affinity mission[ST:n ]\"The Repair Job.\"",
"Lin can often be found here.",
"Completed Vandham's affinity mission[ST:n ]\"A Day in the Life.\"",
"Completed Elma's affinity mission[ST:n ]\"Then and Now.\"",
"Completed Lin and Tatsu's affinity mission[ST:n ]\"To Serve Nopon.\"",
"Name: Elma[ST:n ]Affinity: 5[ST:n ]Appears: Night[ST:n ]Requirements: View 4th heart-to-heart",
"Completed Nagi's affinity mission[ST:n ]\"Nagi's Time.\"",
"Completed Chausson's affinity mission[ST:n ]\"A Challenger Approaches.\"",
"Name: Nagi[ST:n ]Affinity: 4[ST:n ]Appears: ---[ST:n ]Requirements: View 3rd heart-to-heart",
"Completed Elma's affinity mission[ST:n ]\"We Were Soldiers.\"",
"Elma can often be found here.",
"Completed Lin and Vandham's affinity mission[ST:n ]\"Two Peas in a Pod.\"",
"Completed Irina's affinity mission[ST:n ]\"Fathers and Sons.\"",
"Completed Tatsu's affinity mission[ST:n ]\"BFFs.\"",
"Completed Chausson's affinity mission[ST:n ]\"Prospective Partners.\"",
"Completed Lao's affinity mission[ST:n ]\"A Friend in Need.\"",
]

source = [
589,
590,
591,
592,
593,
594,
595,
596,
597,
598,
719,
600,
601,
602,
603,
604,
605,
623,
607,
608,
609,
610,
611,
612,
613,
614,
615,
616,
617,
618,
619,
620,
621,
622,
606,
624,
625,
626,
627,
628,
629,
630,
631,
632,
633,
634,
635,
636,
637,
638,
639,
640,
641,
642,
643,
644,
645,
646,
647,
648,
649,
650,
651,
652,
653,
654,
655,
656,
657,
658,
659,
660,
661,
662,
663,
664,
665,
666,
667,
673,
669,
670,
671,
672,
668,
674,
675,
676,
677,
678,
679,
680,
681,
682,
683,
684,
685,
686,
687,
688,
689,
690,
691,
692,
693,
694,
695,
696,
697,
698,
699,
700,
701,
702,
703,
704,
705,
706,
707,
708,
709,
710,
711,
712,
713,
714,
715,
716,
717,
718,
746,
720,
721,
722,
723,
724,
725,
726,
727,
728,
729,
730,
731,
732,
733,
734,
735,
736,
737,
738,
739,
740,
741,
742,
743,
744,
745,
599,
747,
748,
749,
750,
751,
752,
753,
754,
755,
756,
757,
758,
759,
760,
761,
762,
763,
764,
765,
766,
767,
768,
769,
770,
771,
772,
773,
774,
775,
776,
777,
778,
779,
780,
785,
782,
783,
784,
781,
786,
787,
788,
789,
790,
791,
792,
793,
794,
795,
796,
797,
798,
799,
800,
801,
802,
803,
804,
805,
806,
807,
808,
809,
810,
811,
812,
813,
814,
815,
816,
817,
818,
819,
820,
821,
822,
823,
824,
825,
826,
827,
828,
829,
830,
831,
832,
833,
834,
835,
836,
837,
838,
839,
840,
841,
842,
843,
844,
845,
846,
847,
848,
849,
850,
851,
852,
853,
854,
855,
856,
857,
858,
859,
860,
861,
862,
863,
864,
865,
866,
867,
868,
869,
870,
871,
872,
873,
874,
875,
876,
877,
878,
879,
880,
881,
882,
883,
884,
885,
886,
887,
888,
889,
890,
891,
892,
893,
894,
895,
896,
897,
898,
899,
900,
901,
902,
903,
904,
905,
906,
907,
908,
909,
912,
911,
910,
913,
914,
915,
916,
917,
918,
919,
920,
921,
922,
923,
924,
925,
926,
927,
928,
929,
930,
931,
932,
933,
934,
935,
936,
937,
938,
939,
940,
941,
942,
943,
944,
945,
946,
947,
948,
949,
950,
951,
952,
953,
954,
955,
956,
957,
958,
959,
960,
961,
962,
963,
964,
965,
966,
967,
968,
969,
970,
971,
972,
973,
974,
991,
976,
977,
978,
979,
980,
981,
982,
983,
984,
985,
986,
987,
988,
989,
990,
975,
992,
993,
994,
995,
996,
997,
998,
999,
1000,
1001,
1002,
1003,
1004,
1005,
1006,
1007,
1008,
1009,
1010,
1011,
1012,
1013,
1014,
1015,
1016,
1017,
1018,
1019,
1020,
1021,
1022,
1023,
1024,
1025,
1026,
1027,
1028,
1029,
1030,
1031,
1032,
1033,
1034,
1035,
1036,
1037,
1038,
1039,
1040,
1041,
1042,
1043,
1044,
1045,
1046,
1047,
1048,
1049,
1050,
1051,
1052,
1053,
1054,
1055,
1056,
1057,
1058,
1059,
1060,
1061,
1062,
1063,
1064,
1065,
1066,
1067,
1068,
1069,
1070,
1071,
1072,
1073,
1074,
1075,
1076,
1077,
1078,
1079,
1080,
1081,
1082,
1083,
1084,
1085,
1086,
1087,
1088,
1089,
1090,
1091,
1092,
1093,
1094,
1095,
1096,
1097,
1098,
1099,
1100,
1101,
1102,
1103,
1104,
1105,
1106,
1107,
1108,
1109,
1110,
1111,
1112,
1113,
1114,
1115,
1116,
1124,
1118,
1119,
1120,
1121,
1122,
1123,
1117,
1125,
1126,
1127,
1128,
1129,
1130,
1131,
1132,
1133,
1134,
1135,
1136,
1137,
1138,
1139,
1140,
1141,
1142,
1143,
1144,
1145,
1146,
1147,
1148,
1149,
1150,
1151,
1152,
1153,
1154,
1155,
1156,
1157,
1158,
1159,
1160,
1161,
1162,
1163,
1164,
1165,
1166,
1167,
1168,
1169,
1170,
1171,
1172,
1173,
1174,
1175,
1176,
]

with open('helper_segments.txt', 'w') as f:
	sys.stdout = f
	for idx in source:
		print(f"{json.dumps(replacement[idx - 589])},")