ITEM_MAPPING = {
    [0xEB0001] = {"franklinbadge", "toggle"},
    [0xEB0068] = {"pakofbubblegum", "toggle"},
    [0xEB0069] = {"flyhoney", "toggle"},
    [0xEB008B] = {"yogurtdispenser", "toggle"},
    [0xEB009E] = {"engine", "toggle"},
    [0xEB00A2] = {"pignose", "toggle"},
    [0xEB00A4] = {"shynessbook", "toggle"},
    [0xEB00A6] = {"kingbanana", "toggle"},
    [0xEB00A7] = {"letter", "toggle"},
    [0xEB00AA] = {"shackkey", "toggle"},
    [0xEB00AB] = {"cabinkey", "toggle"},
    [0xEB00AC] = {"badkeymachine", "toggle"},
    [0xEB00AE] = {"zombiepaper", "toggle"},
    [0xEB00AF] = {"hawkeye", "toggle"},
    [0xEB00B4] = {"wadofbills", "toggle"},
    [0xEB00B6] = {"diamond", "toggle"},
    [0xEB00B7] = {"signedbanana", "toggle"},
    [0xEB00B8] = {"pencileraser", "toggle"},
    [0xEB00B9] = {"hieroglyph", "toggle"},
    [0xEB00BB] = {"lens", "toggle"},
    [0xEB00C0] = {"towerkey", "toggle"},
    [0xEB00C1] = {"meteoritepiece", "toggle"},
    [0xEB00CA] = {"policebadge", "toggle"},
    [0xEB00CB] = {"permit", "toggle"},
    [0xEB00CD] = {"lockerkey", "toggle"},
    [0xEB00CE] = {"insignificantitem", "toggle"},
    [0xEB00D0] = {"tinyruby", "toggle"},
    [0xEB00D2] = {"erasereraser", "toggle"},
    [0xEB00D3] = {"tendakraut", "toggle"},
    [0xEB00FD] = {"carrotkey", "toggle"},

    [0xEB00FE] = {"onettwarp", "toggle"},
    [0xEB00FF] = {"twosonwarp", "toggle"},
    [0xEB0100] = {"happywarp", "toggle"},
    [0xEB0101] = {"threedwarp", "toggle"},
    [0xEB0102] = {"valleywarp", "toggle"},
    [0xEB0103] = {"desertwarp", "toggle"},
    [0xEB0104] = {"foursidewarp", "toggle"},
    [0xEB0105] = {"winterswarp", "toggle"},
    [0xEB0106] = {"summerswarp", "toggle"},
    [0xEB0107] = {"scarabawarp", "toggle"},
    [0xEB0108] = {"dalaamwarp", "toggle"},
    [0xEB0109] = {"darkwarp", "toggle"},
    [0xEB010A] = {"tendawarp", "toggle"},
    [0xEB010B] = {"underwarp", "toggle"},
    [0xEB010D] = {"magicwarp", "toggle"},

    [0xEB007D] = {"tinykey", "toggle"},
    [0xEB00B3] = {"lavapants", "toggle"},

    [0xEB0112] = {"ness", "toggle"},
    [0xEB010E] = {"paula", "toggle"},
    [0xEB010F] = {"jeff", "toggle"},
    [0xEB0110] = {"poo", "toggle"}
    
}