Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Town.json")
Tracker:AddLocations("locations/Sewers.json")
Tracker:AddLocations("locations/Petal_Meadows.json")
Tracker:AddLocations("locations/Shhwonk_Fortress.json")
Tracker:AddLocations("locations/Hooktail_Castle.json")
Tracker:AddLocations("locations/Boggly_Woods.json")
Tracker:AddLocations("locations/Great_Tree.json")
Tracker:AddLocations("locations/Glitz_Pit.json")
Tracker:AddLocations("locations/Glitzville.json")
Tracker:AddLocations("locations/Twilight_Trail.json")
Tracker:AddLocations("locations/Creepy_Steeple.json")
Tracker:AddLocations("locations/Keelhaul_Key.json")
Tracker:AddLocations("locations/Pirates_Grotto.json")
Tracker:AddLocations("locations/Excess_Express.json")
Tracker:AddLocations("locations/Riverside_Station.json")
Tracker:AddLocations("locations/Poshley_Heights.json")
Tracker:AddLocations("locations/Fhar_Outpost.json")
Tracker:AddLocations("locations/The_Moon.json")
Tracker:AddLocations("locations/Palace_of_Shadow.json")
Tracker:AddLocations("locations/X-Naut_Fortress.json")
Tracker:AddLocations("locations/Tattle_Log.json")

--Player Position Tracking
Tracker:AddLocations("locations/Player_Positions.json")