/// <reference types="vite/client" />

interface Window {
  sekailink?: {
    getEnv?: () => Promise<Record<string, unknown>> | Record<string, unknown>;
    authGetDesktopSession?: () => Promise<{ ok: boolean; session?: { token?: string; user?: unknown; session?: unknown } | null; error?: string }>;
    authSetDesktopSession?: (payload: { token?: string; user?: unknown; session?: unknown; updated_at?: string } | null) => Promise<{ ok: boolean; error?: string }>;
    openExternal?: (url: string) => Promise<{ ok?: boolean; error?: string; detail?: string } | void> | { ok?: boolean; error?: string; detail?: string } | void;
    windowMinimize?: () => Promise<void> | void;
    windowToggleMaximize?: () => Promise<void> | void;
    windowClose?: () => Promise<void> | void;
    setCrashReportingOptIn?: (enabled: boolean) => Promise<{ ok: boolean; enabled?: boolean; error?: string }> | { ok: boolean; enabled?: boolean; error?: string };
    collectDiagnostics?: (options?: Record<string, unknown>) => Promise<{ ok: boolean; report?: Record<string, unknown>; error?: string }> | { ok: boolean; report?: Record<string, unknown>; error?: string };
    submitDiagnostics?: (options: Record<string, unknown>) => Promise<{ ok: boolean; status?: number; error?: string }> | { ok: boolean; status?: number; error?: string };
    collectBugReportArtifacts?: (options?: Record<string, unknown>) => Promise<{ ok: boolean; artifacts?: Record<string, unknown>; error?: string }> | { ok: boolean; artifacts?: Record<string, unknown>; error?: string };
    clearSeedCache?: () => Promise<{ ok: boolean; activeRuntimeCount?: number; cleared?: string[]; failed?: Array<Record<string, unknown>>; patchedRomCache?: Record<string, unknown>; error?: string }> | { ok: boolean; activeRuntimeCount?: number; cleared?: string[]; failed?: Array<Record<string, unknown>>; patchedRomCache?: Record<string, unknown>; error?: string };
    copyText?: (text: string) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    showItemInFolder?: (targetPath: string) => Promise<unknown> | unknown;
    openDashboard?: (url: string) => Promise<{ ok?: boolean; error?: string; detail?: string } | void> | { ok?: boolean; error?: string; detail?: string } | void;
    updaterDownload?: (options: { downloadUrl?: string; url?: string; version?: string; latest?: string; sha256?: string; signature?: string; publicKey?: string; authToken?: string; artifactType?: string }) => Promise<{ ok: boolean; downloadId?: string; error?: string }> | { ok: boolean; downloadId?: string; error?: string };
    updaterDownloadAndApply?: (options: { downloadUrl?: string; url?: string; version?: string; latest?: string; sha256?: string; signature?: string; publicKey?: string; authToken?: string; timeoutMs?: number; artifactType?: string; channel?: string; build?: string; fallbackDownloadUrl?: string; fallbackSha256?: string; fallbackSignature?: string; fallbackPublicKey?: string; fallbackArtifactType?: string }) => Promise<{ ok: boolean; error?: string; downloadId?: string; path?: string; method?: string }> | { ok: boolean; error?: string; downloadId?: string; path?: string; method?: string };
    updaterOpenDownloaded?: (targetPath: string) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    updaterSyncIncremental?: (options: { manifestUrl?: string; url?: string; authToken?: string }) => Promise<{ ok: boolean; error?: string; changed?: number; deleted?: number; processed?: number; total?: number; downloadedBytes?: number }> | { ok: boolean; error?: string; changed?: number; deleted?: number; processed?: number; total?: number; downloadedBytes?: number };
    updaterLaunchBootstrapperAndQuit?: () => Promise<{ ok: boolean; path?: string; error?: string }> | { ok: boolean; path?: string; error?: string };
    bootstrapperGetReleaseChannel?: () => Promise<{ ok: boolean; channel?: string; installedChannel?: string; installedVersion?: string; error?: string }> | { ok: boolean; channel?: string; installedChannel?: string; installedVersion?: string; error?: string };
    bootstrapperSetReleaseChannel?: (channel: string) => Promise<{ ok: boolean; channel?: string; rebootRequired?: boolean; path?: string; error?: string }> | { ok: boolean; channel?: string; rebootRequired?: boolean; path?: string; error?: string };
    bootstrapperCheckUpdate?: (options?: { channel?: string; force?: boolean }) => Promise<{ ok: boolean; updated?: boolean; channel?: string; version?: string; error?: string }> | { ok: boolean; updated?: boolean; channel?: string; version?: string; error?: string };
    bootstrapperGetLatest?: (channel?: string) => Promise<{ ok: boolean; source?: string; url?: string; manifest?: Record<string, unknown>; error?: string }> | { ok: boolean; source?: string; url?: string; manifest?: Record<string, unknown>; error?: string };
    pickFile?: (options?: { title?: string; filters?: { name: string; extensions: string[] }[] }) => Promise<{ canceled: boolean; path?: string }> | { canceled: boolean; path?: string };
    pickFolder?: (options?: { title?: string }) => Promise<{ canceled: boolean; path?: string }> | { canceled: boolean; path?: string };
    configGet?: () => Promise<Record<string, any>> | Record<string, any>;
    configSetRom?: (gameId: string, romPath: string) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    configDeleteRom?: (gameId: string) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    configSetGame?: (gameId: string, patch: Record<string, any>) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    configSetWindowing?: (windowing: Record<string, any>) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    configSetLayout?: (layout: Record<string, any>) => Promise<{ ok: boolean; error?: string }> | { ok: boolean; error?: string };
    romsScan?: (folderPath: string) => Promise<{ ok: boolean; results: Array<{ gameId: string; file: string }> }> | { ok: boolean; results: Array<{ gameId: string; file: string }> };
    romsImport?: (payload: string | { filePath: string; gameId?: string }) => Promise<{ ok: boolean; gameId?: string; path?: string; error?: string; expected?: string }> | { ok: boolean; gameId?: string; path?: string; error?: string; expected?: string };
    onAuthCallback?: (handler: (url: string) => void) => () => void;
    commonClientStart?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    commonClientSend?: (command: Record<string, unknown>) => Promise<unknown> | unknown;
    commonClientStop?: () => Promise<unknown> | unknown;
    onCommonClientEvent?: (handler: (data: unknown) => void) => () => void;
    bizhawkClientStart?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    bizhawkClientSend?: (command: Record<string, unknown>) => Promise<unknown> | unknown;
    bizhawkClientStop?: () => Promise<unknown> | unknown;
    onBizHawkClientEvent?: (handler: (data: unknown) => void) => () => void;
    archipelagoClientList?: () => Promise<unknown> | unknown;
    archipelagoClientStart?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    archipelagoClientSend?: (clientId: string, command: Record<string, unknown>) => Promise<unknown> | unknown;
    archipelagoClientStop?: (clientId: string) => Promise<unknown> | unknown;
    onArchipelagoClientEvent?: (handler: (data: unknown) => void) => () => void;
    patcherApply?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    bizhawkLaunch?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    bizhawkStop?: (pid: number) => Promise<unknown> | unknown;
    sekaiEmuLabListCores?: () => Promise<unknown> | unknown;
    sekaiEmuLabLaunch?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sekaiEmuStop?: (pid: number) => Promise<unknown> | unknown;
    sekaiEmuGetSession?: (pid: number) => Promise<unknown> | unknown;
    sekaiEmuSetInputState?: (pid: number, keys: number) => Promise<unknown> | unknown;
    sekaiEmuSetPaused?: (pid: number, paused: boolean) => Promise<unknown> | unknown;
    sekaiEmuReset?: (pid: number) => Promise<unknown> | unknown;
    sekaiEmuMemoryDomains?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sekaiEmuReadMemory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sekaiEmuDumpMemory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sekaiEmuReadAudio?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    trackerLaunch?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    trackerStop?: (pid: number) => Promise<unknown> | unknown;
    trackerRuntimeStatus?: (pid: number) => Promise<unknown> | unknown;
    trackerRuntimeCommand?: (pid: number, command: string, detail?: Record<string, unknown>) => Promise<unknown> | unknown;
    trackerOpenBroadcast?: () => Promise<unknown> | unknown;
    trackerGetSession?: (pid: number) => Promise<unknown> | unknown;
    trackerListSessions?: () => Promise<unknown> | unknown;
    trackerInstallPack?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    trackerStatus?: () => Promise<unknown> | unknown;
    trackerValidatePack?: (gameId: string) => Promise<unknown> | unknown;
    trackerListPackVariants?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    trackerSetVariant?: (gameId: string, variant: string) => Promise<unknown> | unknown;
    sniStatus?: () => Promise<unknown> | unknown;
    sniListDevices?: (options?: Record<string, unknown>) => Promise<unknown> | unknown;
    sniReadMemory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniWriteMemory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniResetSystem?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniResetToMenu?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniReadDirectory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniMakeDirectory?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniRemoveFile?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniRenameFile?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniPutFile?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniGetFile?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sniBootFile?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    smz3ValidateRom?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    smz3Poll?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    smz3DeliverItem?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    resolveModuleForDownload?: (downloadUrl: string) => Promise<unknown> | unknown;
    getModuleManifest?: (moduleId: string) => Promise<unknown> | unknown;
    validateSetupForModule?: (moduleId: string) => Promise<unknown> | unknown;
    listRuntimeModules?: () => Promise<unknown> | unknown;
    linkedWorldList?: () => Promise<unknown> | unknown;
    linkedWorldValidate?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    linkedWorldInstall?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    linkedWorldLaunch?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    linkedWorldInstallWindWakerTest?: () => Promise<unknown> | unknown;
    linkedWorldLaunchSolo?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    listNativeBizHawkHandlers?: () => Promise<unknown> | unknown;
    gamescopeStatus?: () => Promise<unknown> | unknown;
    wmctrlStatus?: () => Promise<unknown> | unknown;
    getDisplays?: () => Promise<unknown> | unknown;
    sessionAutoLaunch?: (options: Record<string, unknown>) => Promise<unknown> | unknown;
    sessionTrackerVariantResponse?: (payload: Record<string, unknown>) => Promise<unknown> | unknown;
    onSessionEvent?: (handler: (data: unknown) => void) => () => void;
    onUpdaterEvent?: (handler: (data: unknown) => void) => () => void;
    logToMain?: (payload: Record<string, unknown>) => Promise<unknown> | unknown;
  };
}

declare const __APP_VERSION__: string;
