#include "input_capture_mode.hpp"

#include <SDL.h>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <string>
#include <string_view>
#include <vector>

namespace sekaiemu::spike {
namespace {

struct CaptureControl {
  std::string key;
  std::string label;
  std::string keyboard;
  std::string fallback_controller;
};

std::string Lower(std::string_view text) {
  std::string output(text);
  std::transform(output.begin(), output.end(), output.begin(), [](unsigned char value) {
    return static_cast<char>(std::tolower(value));
  });
  return output;
}

std::vector<CaptureControl> ControlsForProfile(const std::string& profile) {
  const std::string clean = Lower(profile);
  std::vector<CaptureControl> controls = {
      {"dpad_up", "D-Pad Up", "key:Up", "button:dpup"},
      {"dpad_down", "D-Pad Down", "key:Down", "button:dpdown"},
      {"dpad_left", "D-Pad Left", "key:Left", "button:dpleft"},
      {"dpad_right", "D-Pad Right", "key:Right", "button:dpright"},
      {"a", "A", "key:X", "button:a"},
      {"b", "B", "key:Z", "button:b"},
  };
  if (clean != "nes" && clean != "gb" && clean != "gbc") {
    controls.push_back({"x", "X", "key:S", "button:x"});
    controls.push_back({"y", "Y", "key:A", "button:y"});
  }
  if (clean != "nes" && clean != "gb" && clean != "gbc") {
    controls.push_back({"l", "L", "key:Q", "button:leftshoulder"});
    controls.push_back({"r", "R", "key:W", "button:rightshoulder"});
  }
  controls.push_back({"start", "Start", "key:Return", "button:start"});
  controls.push_back({"select", "Select", "key:Right Shift", "button:back"});
  if (clean == "n64") {
    controls.push_back({"analog_up", "Stick Up", "key:Up", "axis-:lefty"});
    controls.push_back({"analog_down", "Stick Down", "key:Down", "axis+:lefty"});
    controls.push_back({"analog_left", "Stick Left", "key:Left", "axis-:leftx"});
    controls.push_back({"analog_right", "Stick Right", "key:Right", "axis+:leftx"});
  }
  return controls;
}

std::string ControllerButtonToken(Uint8 button) {
  const char* name = SDL_GameControllerGetStringForButton(static_cast<SDL_GameControllerButton>(button));
  if (!name || !*name) return "";
  return std::string("button:") + name;
}

std::string ControllerAxisToken(Uint8 axis, Sint16 value) {
  if (std::abs(static_cast<int>(value)) < 16000) return "";
  const char* name = SDL_GameControllerGetStringForAxis(static_cast<SDL_GameControllerAxis>(axis));
  if (!name || !*name) return "";
  return std::string(value > 0 ? "axis+:" : "axis-:") + name;
}

bool WriteCaptureConfig(const std::filesystem::path& path,
                        const std::vector<CaptureControl>& controls,
                        const std::vector<std::string>& tokens,
                        std::string& error) {
  std::error_code ec;
  std::filesystem::create_directories(path.parent_path(), ec);
  std::ofstream stream(path, std::ios::trunc);
  if (!stream) {
    error = "Could not write input capture output: " + path.string();
    return false;
  }
  stream << "# Sekaiemu core input configuration\n";
  stream << "# Generated by Sekaiemu SDL input capture.\n";
  stream << "selected_controller_guid=\n";
  for (std::size_t index = 0; index < controls.size(); ++index) {
    const auto& control = controls[index];
    const std::string controller = index < tokens.size() && !tokens[index].empty()
        ? tokens[index]
        : control.fallback_controller;
    stream << control.key << ".keyboard=" << control.keyboard << "\n";
    stream << control.key << ".controller=" << controller << "\n";
  }
  return true;
}

void SetInstruction(SDL_Window* window, const std::vector<CaptureControl>& controls, std::size_t index) {
  const std::string title = index < controls.size()
      ? "Sekaiemu Controller Capture - press " + controls[index].label + " (Esc to cancel)"
      : "Sekaiemu Controller Capture - complete";
  SDL_SetWindowTitle(window, title.c_str());
}

}  // namespace

int RunInputCaptureMode(const LaunchRequest& request, std::string& error) {
  if (request.input_capture_path.empty()) {
    error = "Input capture path is empty.";
    return 1;
  }
  if (SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK) == 0) {
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER | SDL_INIT_JOYSTICK) != 0) {
      error = SDL_GetError();
      return 1;
    }
  }

  SDL_Window* window = SDL_CreateWindow(
      "Sekaiemu Controller Capture",
      SDL_WINDOWPOS_CENTERED,
      SDL_WINDOWPOS_CENTERED,
      680,
      160,
      SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI);
  if (!window) {
    error = SDL_GetError();
    return 1;
  }

  SDL_GameController* controller = nullptr;
  for (int index = 0; index < SDL_NumJoysticks(); ++index) {
    if (SDL_IsGameController(index)) {
      controller = SDL_GameControllerOpen(index);
      if (controller) break;
    }
  }

  const auto controls = ControlsForProfile(request.input_capture_profile);
  std::vector<std::string> tokens(controls.size());
  std::size_t current = 0;
  SetInstruction(window, controls, current);

  bool running = true;
  bool completed = false;
  while (running) {
    SDL_Event event;
    while (SDL_WaitEvent(&event)) {
      if (event.type == SDL_QUIT) {
        running = false;
        break;
      }
      if (event.type == SDL_KEYDOWN && event.key.keysym.sym == SDLK_ESCAPE) {
        error = "Input capture cancelled.";
        running = false;
        break;
      }
      std::string token;
      if (event.type == SDL_CONTROLLERBUTTONDOWN) {
        token = ControllerButtonToken(event.cbutton.button);
      } else if (event.type == SDL_CONTROLLERAXISMOTION) {
        token = ControllerAxisToken(event.caxis.axis, event.caxis.value);
      }
      if (token.empty()) continue;
      tokens[current] = token;
      current += 1;
      if (current >= controls.size()) {
        completed = true;
        running = false;
        break;
      }
      SetInstruction(window, controls, current);
    }
  }

  if (controller) SDL_GameControllerClose(controller);
  SDL_DestroyWindow(window);
  if (!completed) return 2;
  if (!WriteCaptureConfig(request.input_capture_path, controls, tokens, error)) return 1;
  SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_INFORMATION, "Sekaiemu", "Controller capture complete.", nullptr);
  return 0;
}

}  // namespace sekaiemu::spike
