ItemData = {
    item_name_groups = {}
}

ItemType = {
    NONE = 0,
    SONG = 1,
    MAGIC = 2
}

local SoHItemData = {}
SoHItemData.__index = SoHItemData

setmetatable(
    SoHItemData,
    {
        __call = function(cls, ...)
            return cls.new(...)
        end
    }
)

function SoHItemData.new(item_type, child_only, adult_only, item_groups)
    local self = {}
    setmetatable(self, SoHItemData)

    self.item_type = item_type or ItemType.NONE
    self.child_only = child_only or false
    self.adult_only = adult_only or false
    self.item_groups = item_groups or {}

    return self
end

ItemData.item_data_table = {
    [Items.KOKIRI_SWORD] = SoHItemData(0, true, false, {"Swords", "Sword"}),
    [Items.MASTER_SWORD] = SoHItemData(0, false, true, {"Swords", "Sword"}),
    [Items.GIANTS_KNIFE] = SoHItemData(0, false, true, {"Swords", "Sword"}),
    [Items.BIGGORONS_SWORD] = SoHItemData(0, false, {"Swords", "Sword"}),
    [Items.DEKU_SHIELD] = SoHItemData(0, true, false, {"Shields", "Shield"}),
    [Items.HYLIAN_SHIELD] = SoHItemData(0, false, false, {"Shields", "Shield"}),
    [Items.MIRROR_SHIELD] = SoHItemData(0, false, true, {"Shields", "Shield"}),
    [Items.GORON_TUNIC] = SoHItemData(0, false, true, {"Tunics", "Tunic"}),
    [Items.ZORA_TUNIC] = SoHItemData(0, false, true, {"Tunics", "Tunic"}),
    [Items.IRON_BOOTS] = SoHItemData(0, false, true),
    [Items.HOVER_BOOTS] = SoHItemData(0, false, true),
    [Items.BOOMERANG] = SoHItemData(0, true, false),
    [Items.LENS_OF_TRUTH] = SoHItemData(ItemType.MAGIC, false, false, {"Lens"}),
    [Items.MEGATON_HAMMER] = SoHItemData(0, false, true, {"Hammer"}),
    [Items.STONE_OF_AGONY] = SoHItemData(),
    [Items.DINS_FIRE] = SoHItemData(ItemType.MAGIC),
    [Items.FARORES_WIND] = SoHItemData(ItemType.MAGIC),
    [Items.NAYRUS_LOVE] = SoHItemData(ItemType.MAGIC),
    [Items.FIRE_ARROW] = SoHItemData(ItemType.MAGIC, false, true, {"Magic Arrows"}),
    [Items.ICE_ARROW] = SoHItemData(ItemType.MAGIC, false, true, {"Magic Arrows"}),
    [Items.LIGHT_ARROW] = SoHItemData(ItemType.MAGIC, false, true, {"Magic Arrows"}),
    [Items.GERUDO_MEMBERSHIP_CARD] = SoHItemData(),
    [Items.MAGIC_BEAN] = SoHItemData(0, true, false, {"Beans", "Bean"}),
    [Items.MAGIC_BEAN_PACK] = SoHItemData(0, true, false, {"Beans", "Bean"}),
    [Items.DOUBLE_DEFENSE] = SoHItemData(),
    [Items.WEIRD_EGG] = SoHItemData(0, true, false),
    [Items.ZELDAS_LETTER] = SoHItemData(0, true, false),
    [Items.POCKET_EGG] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.COJIRO] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.ODD_MUSHROOM] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.ODD_POTION] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.POACHERS_SAW] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.BROKEN_GORONS_SWORD] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.PRESCRIPTION] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.EYEBALL_FROG] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.WORLDS_FINEST_EYEDROPS] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.CLAIM_CHECK] = SoHItemData(0, false, true, {"Adult Trade Items"}),
    [Items.GOLD_SKULLTULA_TOKEN] = SoHItemData(0, false, false, {"Tokens", "Token"}),
    [Items.PROGRESSIVE_HOOKSHOT] = SoHItemData(0, false, false, {"Hookshot", "Longshot"}),
    [Items.STRENGTH_UPGRADE] = SoHItemData(0, false, false, {"Strength Upgrades"}),
    [Items.PROGRESSIVE_BOMB_BAG] = SoHItemData(0, false, false, {"Bomb Bag", "Bombs"}),
    [Items.PROGRESSIVE_BOW] = SoHItemData(0, false, false, {"Bow"}),
    [Items.PROGRESSIVE_SLINGSHOT] = SoHItemData(0, false, false, {"Slingshot"}),
    [Items.PROGRESSIVE_WALLET] = SoHItemData(0, false, false, {"Wallet", "Giant Wallet", "Adult Wallet", "Tycoon Wallet"}),
    [Items.PROGRESSIVE_SCALE] = SoHItemData(0, false, false, {"Bronze Scale", "Silver Scale", "Golden Scale", "Scale"}),
    [Items.PROGRESSIVE_NUT_CAPACITY] = SoHItemData(0, false, false, {"Deku Nut Bag"}),
    [Items.PROGRESSIVE_STICK_CAPACITY] = SoHItemData(0, false, false, {"Stick Bag"}),
    [Items.BOMBCHU_BAG] = SoHItemData(0, false, false, {"Progressive Bombchu Bag", "Bombs"}),
    [Items.PROGRESSIVE_MAGIC_METER] = SoHItemData(0, false, false, {"Magic Meter"}),
    [Items.MAGIC_SINGLE] = SoHItemData(),
    [Items.MAGIC_DOUBLE] = SoHItemData(),
    [Items.PROGRESSIVE_OCARINA] = SoHItemData(0, false, false, {"Ocarinas", "Ocarina"}),
    --Items.PROGRESSIVE_GORON_SWORD = SoHItemData(),
    [Items.EMPTY_BOTTLE] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_MILK] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_RED_POTION] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_GREEN_POTION] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_BLUE_POTION] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_FAIRY] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_FISH] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_BLUE_FIRE] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_BUGS] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_POE] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_RUTOS_LETTER] = SoHItemData(0, true, false, {"Bottles", "Bottle"}),
    [Items.BOTTLE_WITH_BIG_POE] = SoHItemData(0, false, false, {"Bottles", "Bottle"}),
    [Items.ZELDAS_LULLABY] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.EPONAS_SONG] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.SARIAS_SONG] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.SUNS_SONG] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.SONG_OF_TIME] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.SONG_OF_STORMS] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.MINUET_OF_FOREST] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.BOLERO_OF_FIRE] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.SERENADE_OF_WATER] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.REQUIEM_OF_SPIRIT] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.NOCTURNE_OF_SHADOW] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.PRELUDE_OF_LIGHT] = SoHItemData(ItemType.SONG, false, false, {"Songs", "Song"}),
    [Items.GREAT_DEKU_TREE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.DODONGOS_CAVERN_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.JABU_JABUS_BELLY_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.FOREST_TEMPLE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.FIRE_TEMPLE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.WATER_TEMPLE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.SPIRIT_TEMPLE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.SHADOW_TEMPLE_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.BOTTOM_OF_THE_WELL_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.ICE_CAVERN_MAP] = SoHItemData(0, false, false, {"Maps", "Map"}),
    [Items.GREAT_DEKU_TREE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.DODONGOS_CAVERN_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.JABU_JABUS_BELLY_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.FOREST_TEMPLE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.FIRE_TEMPLE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.WATER_TEMPLE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.SPIRIT_TEMPLE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.SHADOW_TEMPLE_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.BOTTOM_OF_THE_WELL_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.ICE_CAVERN_COMPASS] = SoHItemData(0, false, false, {"Compasses", "Compass"}),
    [Items.FOREST_TEMPLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.FIRE_TEMPLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.WATER_TEMPLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.SPIRIT_TEMPLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.SHADOW_TEMPLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.GANONS_CASTLE_BOSS_KEY] = SoHItemData(0, false, false, {"Boss Keys", "Boss Key"}),
    [Items.FOREST_TEMPLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Forest Temple Key"}),
    [Items.FIRE_TEMPLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Fire Temple Key"}),
    [Items.WATER_TEMPLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Water Temple Key"}),
    [Items.SPIRIT_TEMPLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Spirit Temple Key"}),
    [Items.SHADOW_TEMPLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Shadow Temple Key"}),
    [Items.BOTTOM_OF_THE_WELL_SMALL_KEY] = SoHItemData(
        0,
        false,
        false,
        {"Small Keys", "Small Key", "Bottom of the Well Key", "BotW key"}
    ),
    [Items.TRAINING_GROUND_SMALL_KEY] = SoHItemData(
        0,
        false,
        false,
        {"Small Keys", "Small Key", "Gerudo Training Ground Key", "GTG key"}
    ),
    [Items.GERUDO_FORTRESS_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Gerudo Fortress Key"}),
    [Items.GANONS_CASTLE_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Ganons Castle Key"}),
    [Items.TREASURE_GAME_SMALL_KEY] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Treasure Game Key"}),
    [Items.FOREST_TEMPLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Forest Temple Key"}),
    [Items.FIRE_TEMPLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Fire Temple Key"}),
    [Items.WATER_TEMPLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Water Temple Key"}),
    [Items.SPIRIT_TEMPLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Spirit Temple Key"}),
    [Items.SHADOW_TEMPLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Shadow Temple Key"}),
    [Items.BOTTOM_OF_THE_WELL_KEY_RING] = SoHItemData(
        0,
        false,
        false,
        {"Small Keys", "Small Key", "Bottom of the Well Key", "BotW key"}
    ),
    [Items.TRAINING_GROUND_KEY_RING] = SoHItemData(
        0,
        false,
        false,
        {"Small Keys", "Small Key", "Gerudo Training Ground Key", "GTG key"}
    ),
    [Items.GERUDO_FORTRESS_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Gerudo Fortress Key"}),
    [Items.GANONS_CASTLE_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Ganons Castle Key"}),
    [Items.TREASURE_GAME_KEY_RING] = SoHItemData(0, false, false, {"Small Keys", "Small Key", "Treasure Game Key"}),
    [Items.KOKIRIS_EMERALD] = SoHItemData(0, false, false, {"Stones", "Stone"}),
    [Items.GORONS_RUBY] = SoHItemData(0, false, false, {"Stones", "Stone"}),
    [Items.ZORAS_SAPPHIRE] = SoHItemData(0, false, false, {"Stones", "Stone"}),
    [Items.FOREST_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.FIRE_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.WATER_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.SPIRIT_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.SHADOW_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.LIGHT_MEDALLION] = SoHItemData(0, false, false, {"Medallions", "Medallion"}),
    [Items.RECOVERY_HEART] = SoHItemData(),
    [Items.GREEN_RUPEE] = SoHItemData(),
    [Items.GREG_THE_GREEN_RUPEE] = SoHItemData(),
    [Items.BLUE_RUPEE] = SoHItemData(),
    [Items.RED_RUPEE] = SoHItemData(),
    [Items.PURPLE_RUPEE] = SoHItemData(),
    [Items.HUGE_RUPEE] = SoHItemData(),
    --35
    [Items.PIECE_OF_HEART] = SoHItemData(0, false, false, { "Hearts", "Heart"}),
    --8
    [Items.HEART_CONTAINER] = SoHItemData(0, false, false, { "Hearts", "Heart"}),
    [Items.ICE_TRAP] = SoHItemData(0, false, false, {"Traps", "Trap"}),
    --Items.MILK = SoHItemData(0, ),
    --Items.FISH = SoHItemData(0, ),
    [Items.BOMBS_5] = SoHItemData(),
    [Items.BOMBS_10] = SoHItemData(),
    [Items.BOMBS_20] = SoHItemData(),
    [Items.BOMBCHUS_5] = SoHItemData(),
    [Items.BOMBCHUS_10] = SoHItemData(),
    [Items.BOMBCHUS_20] = SoHItemData(),
    [Items.ARROWS_5] = SoHItemData(),
    [Items.ARROWS_10] = SoHItemData(),
    [Items.ARROWS_30] = SoHItemData(),
    [Items.DEKU_NUTS_5] = SoHItemData(),
    [Items.DEKU_NUTS_10] = SoHItemData(),
    [Items.DEKU_SEEDS_30] = SoHItemData(),
    [Items.DEKU_STICK_1] = SoHItemData(),
    --Items.RED_POTION_REFILL = SoHItemData(0,  0 ),
    --Items.GREEN_POTION_REFILL = SoHItemData(0,  0 ),
    --Items.BLUE_POTION_REFILL = SoHItemData(00,  0 ),
    --1
    [Items.PIECE_OF_HEART_WINNER] = SoHItemData(0, false, false, { "Hearts", "Heart"}),
    --Items.TREASURE_GAME_GREEN_RUPEE = SoHItemData(0,  0 ),
    [Items.BUY_DEKU_NUTS5] = SoHItemData(),
    [Items.BUY_ARROWS30] = SoHItemData(),
    [Items.BUY_ARROWS50] = SoHItemData(),
    [Items.BUY_BOMBS525] = SoHItemData(),
    [Items.BUY_DEKU_NUTS10] = SoHItemData(),
    [Items.BUY_DEKU_STICK1] = SoHItemData(),
    [Items.BUY_BOMBS10] = SoHItemData(),
    [Items.BUY_FISH] = SoHItemData(),
    [Items.BUY_RED_POTION30] = SoHItemData(),
    [Items.BUY_GREEN_POTION] = SoHItemData(),
    [Items.BUY_BLUE_POTION] = SoHItemData(),
    [Items.BUY_HYLIAN_SHIELD] = SoHItemData(),
    [Items.BUY_DEKU_SHIELD] = SoHItemData(),
    [Items.BUY_GORON_TUNIC] = SoHItemData(),
    [Items.BUY_ZORA_TUNIC] = SoHItemData(),
    [Items.BUY_HEART] = SoHItemData(),
    [Items.BUY_BOMBCHUS10] = SoHItemData(),
    [Items.BUY_BOMBCHUS20] = SoHItemData(),
    [Items.BUY_DEKU_SEEDS30] = SoHItemData(),
    --Items.SOLD_OUT = SoHItemData(0,  0 ),
    [Items.BUY_BLUE_FIRE] = SoHItemData(),
    [Items.BUY_BOTTLE_BUG] = SoHItemData(),
    [Items.BUY_POE] = SoHItemData(),
    [Items.BUY_FAIRYS_SPIRIT] = SoHItemData(),
    [Items.BUY_ARROWS10] = SoHItemData(),
    [Items.BUY_BOMBS20] = SoHItemData(),
    [Items.BUY_BOMBS30] = SoHItemData(),
    [Items.BUY_BOMBS535] = SoHItemData(),
    [Items.BUY_RED_POTION40] = SoHItemData(),
    [Items.BUY_RED_POTION50] = SoHItemData(),
    --Items.TRIFORCE = SoHItemData(0,  0 ),
    [Items.TRIFORCE_PIECE] = SoHItemData(),
    [Items.GOHMAS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.KING_DODONGOS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.BARINADES_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.PHANTOM_GANONS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.VOLVAGIAS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.MORPHAS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.BONGO_BONGOS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.TWINROVAS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.GANONS_SOUL] = SoHItemData(0, false, false, {"Boss Souls"}),
    [Items.OCARINA_A_BUTTON] = SoHItemData(0, false, false, {"Ocarina Buttons"}),
    [Items.OCARINA_CUP_BUTTON] = SoHItemData(0, false, false, {"Ocarina Buttons"}),
    [Items.OCARINA_CDOWN_BUTTON] = SoHItemData(0, false, false, {"Ocarina Buttons"}),
    [Items.OCARINA_CLEFT_BUTTON] = SoHItemData(0, false, false, {"Ocarina Buttons"}),
    [Items.OCARINA_CRIGHT_BUTTON] = SoHItemData(0, false, false, {"Ocarina Buttons"}),
    [Items.SKELETON_KEY] = SoHItemData(0, false, false, {"Keys", "Key"}),
    [Items.FISHING_POLE] = SoHItemData(),
    [Items.DEKU_STICK_BAG] = SoHItemData(),
    [Items.DEKU_NUT_BAG] = SoHItemData(),
    --Items.HINT = SoHItemData(0,  0 ),
    [Items.TYCOON_WALLET] = SoHItemData(),
    [Items.BRONZE_SCALE] = SoHItemData(),
    [Items.CHILD_WALLET] = SoHItemData(),
    --Items.BOMBCHU_BAG = SoHItemData(),
    --Items.QUIVER_INF = SoHItemData(0,  0 ),
    --Items.BOMB_BAG_INF = SoHItemData(0,  0 ),
    --Items.BULLET_BAG_INF = SoHItemData(00,  0 ),
    --Items.STICK_UPGRADE_INF = SoHItemData(0,  0 ),
    --Items.NUT_UPGRADE_INF = SoHItemData(0,  0 ),
    --Items.MAGIC_INF = SoHItemData(0,  0 ),
    --Items.BOMBCHU_INF = SoHItemData(0,  0 ),
    --Items.WALLET_INF = SoHItemData(0,  0 ),
    [Items.FAIRY_OCARINA] = SoHItemData(),
    [Items.OCARINA_OF_TIME] = SoHItemData(),
    [Items.BOMB_BAG] = SoHItemData(),
    --Items.BIG_BOMB_BAG = SoHItemData(0,  0 ),
    --Items.BIGGEST_BOMB_BAG = SoHItemData(00,  0 ),
    [Items.FAIRY_BOW] = SoHItemData(0, false, true),
    --Items.BIG_QUIVER = SoHItemData(0,  0 ),
    --Items.BIGGEST_QUIVER = SoHItemData(0,  0 ),
    [Items.FAIRY_SLINGSHOT] = SoHItemData(0, true, false),
    --Items.BIG_BULLET_BAG = SoHItemData(0,  0 ),
    --Items.BIGGEST_BULLET_BAG = SoHItemData(0,  0 ),
    [Items.GORONS_BRACELET] = SoHItemData(),
    [Items.SILVER_GAUNTLETS] = SoHItemData(0, false, true),
    [Items.GOLDEN_GAUNTLETS] = SoHItemData(0, false, true),
    [Items.SILVER_SCALE] = SoHItemData(),
    [Items.GOLDEN_SCALE] = SoHItemData(),
    [Items.ADULT_WALLET] = SoHItemData(),
    [Items.GIANT_WALLET] = SoHItemData(),
    --Items.DEKU_NUT_CAPACITY30 = SoHItemData(0,  0 ),
    --Items.DEKU_NUT_CAPACITY40 = SoHItemData(0,  0 ),
    --Items.DEKU_STICK_CAPACITY20 = SoHItemData(0,  0 ),
    --Items.DEKU_STICK_CAPACITY30 = SoHItemData(0,  0 ),
    [Items.HOOKSHOT] = SoHItemData(0, false, true),
    [Items.LONGSHOT] = SoHItemData(0, false, true),
    [Items.SCARECROW] = SoHItemData(0, false, true),
    [Items.GUARD_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.MARKET_BAZAAR_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.MARKET_POTION_SHOP_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.MASK_SHOP_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.MARKET_SHOOTING_GALLERY_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.BOMBCHU_BOWLING_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.TREASURE_CHEST_GAME_BUILDING_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.BOMBCHU_SHOP_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.RICHARDS_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.ALLEY_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.KAK_BAZAAR_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.KAK_POTION_SHOP_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.BOSS_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.GRANNYS_POTION_SHOP_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.SKULLTULA_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.IMPAS_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.WINDMILL_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.KAK_SHOOTING_GALLERY_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.DAMPES_HUT_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.TALONS_HOUSE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.STABLES_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.BACK_TOWER_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.HYLIA_LAB_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.FISHING_HOLE_KEY] = SoHItemData(0, false, false, {"Overworld Keys"}),
    [Items.DISTANT_SCARECROW] = SoHItemData(0, false, true),
    [Items.ROCS_FEATHER] = SoHItemData(),
    [Items.STICKS] = SoHItemData(0, true, false),
    [Items.NUTS] = SoHItemData(),
    [Items.EPONA] = SoHItemData(),
    [Items.RESERVATION] = SoHItemData(),
    --Items.MAX = SoHItemData(0,  0 ),
    --Intentionally place the glitched item without a value. Everything else should be above this.
    [Items.GLITCHED] = SoHItemData()
}

local function initialize_item_name_groups()
    local name_groups = {}
    for item, data in pairs(ItemData.item_data_table) do
        if data.item_groups then
            for _, group in pairs(data.item_groups) do
                if name_groups[group] == nil then
                    name_groups[group] = {}
                end
                table.insert(name_groups[group],item)
            end
        end
    end
    ItemData.item_name_groups = name_groups
end

initialize_item_name_groups()
