"use strict";

const createSekaiemuRuntime = (deps = {}) => {
  const {
    app,
    fs,
    os,
    path,
    crypto,
    processRef = process,
    readConfig,
    ensureDir,
    writeLogLine,
    nowIso,
    isPlainObject,
    getRuntimePlatformPath,
    getBundledRuntimeDir,
    getRuntimeFilePath,
    getOverlayRuntimeDir,
    getInstalledTrackerPack,
    getTrackerVariant,
    moduleUsesBizHawkProtocolClient,
    findFreeLocalPort,
    findFreeLocalPortInRange,
    spawnMaybeGamescope,
    startSekaiemuChatBridge,
    stopArchipelagoClientsForSession,
    nativeGameProcs,
    sekaiemuChatBridges,
    rememberSekaiemuSession = () => {},
    forgetSekaiemuSession = () => {},
  } = deps;
  const process = processRef;

  const getSekaiemuSettings = () => {
    const config = readConfig();
    const games = config.games && typeof config.games === "object" ? config.games : {};
    const sekaiemu = games.sekaiemu && typeof games.sekaiemu === "object" ? games.sekaiemu : {};
    const frontend = sekaiemu.frontend && typeof sekaiemu.frontend === "object" ? sekaiemu.frontend : {};
    const cores = sekaiemu.cores && typeof sekaiemu.cores === "object" ? sekaiemu.cores : {};
    return {
      exe_path: String(sekaiemu.exe_path || process.env.SEKAILINK_SEKAIEMU_PATH || "").trim(),
      root_dir: String(sekaiemu.root_dir || process.env.SEKAILINK_SEKAIEMU_ROOT || "").trim(),
      core_dirs: Array.isArray(sekaiemu.core_dirs) ? sekaiemu.core_dirs.map((entry) => String(entry || "").trim()).filter(Boolean) : [],
      system_dir: String(sekaiemu.system_dir || "").trim(),
      save_dir: String(sekaiemu.save_dir || "").trim(),
      log_dir: String(sekaiemu.log_dir || "").trim(),
      args: Array.isArray(sekaiemu.args) ? sekaiemu.args.map((entry) => String(entry || "").trim()).filter(Boolean) : [],
      frontend,
      cores,
    };
  };
  
  const boolConfigValue = (value, fallback) => {
    if (typeof value === "boolean") return value ? "true" : "false";
    if (typeof value === "string") {
      const lower = value.trim().toLowerCase();
      if (["1", "true", "yes", "on"].includes(lower)) return "true";
      if (["0", "false", "no", "off"].includes(lower)) return "false";
    }
    return fallback ? "true" : "false";
  };
  
  const enumConfigValue = (value, allowed, fallback) => {
    const clean = String(value || "").trim().toLowerCase();
    return allowed.includes(clean) ? clean : fallback;
  };
  
  const writeSekaiemuRuntimeConfig = (saveDir, settings) => {
    const configDir = path.join(saveDir, "frontend-config");
    try {
      ensureDir(configDir);
      const frontend = settings.frontend && typeof settings.frontend === "object" ? settings.frontend : {};
      const settingsMode = enumConfigValue(frontend.settings_mode, ["easy", "advanced"], "easy");
      const trackerDisplayMode = "separate-window";
      const volume = Math.max(0, Math.min(150, Number(frontend.master_volume_percent ?? 15) || 0));
      const sekaiemuCfg = [
        "# Sekaiemu frontend settings generated by SekaiLink Client Core.",
        `settings_mode=${settingsMode}`,
        `chat_overlay_enabled=${boolConfigValue(frontend.chat_overlay_enabled, true)}`,
        `notifications_enabled=${boolConfigValue(frontend.notifications_enabled, true)}`,
        `bridge_terminal_enabled=${boolConfigValue(frontend.bridge_terminal_enabled, false)}`,
        `master_volume_percent=${volume}`,
        `tracker_display_mode=${trackerDisplayMode}`,
        "tracker_screen_visible=false",
        "tracker_auto_follow=false",
        "",
      ].join("\n");
      fs.writeFileSync(path.join(configDir, "sekaiemu.cfg"), sekaiemuCfg, "utf8");
  
      const cores = settings.cores && typeof settings.cores === "object" ? settings.cores : {};
      const coreLines = ["# Sekaiemu core preferences generated by SekaiLink Client Core."];
      for (const [rawKey, rawValue] of Object.entries(cores).sort(([a], [b]) => a.localeCompare(b))) {
        const key = String(rawKey || "").trim();
        if (!/^[A-Za-z0-9._-]+$/.test(key)) continue;
        const value = String(rawValue ?? "").replace(/[\r\n]/g, " ").trim();
        if (!value) continue;
        coreLines.push(`${key}=${value}`);
      }
      coreLines.push("");
      fs.writeFileSync(path.join(configDir, "cores.cfg"), coreLines.join("\n"), "utf8");
      writeLogLine("info", "sekaiemu", `runtime frontend config written: ${configDir}`);
      return { ok: true, dir: configDir };
    } catch (err) {
      const detail = String(err || "");
      writeLogLine("warn", "sekaiemu", `runtime frontend config write failed: ${detail}`);
      return { ok: false, error: "sekaiemu_runtime_config_write_failed", detail };
    }
  };
  
  const fileExists = (filePath) => {
    const safe = String(filePath || "").trim();
    if (!safe) return false;
    try {
      return fs.existsSync(safe) && fs.statSync(safe).isFile();
    } catch (_err) {
      return false;
    }
  };
  
  const dirExists = (dirPath) => {
    const safe = String(dirPath || "").trim();
    if (!safe) return false;
    try {
      return fs.existsSync(safe) && fs.statSync(safe).isDirectory();
    } catch (_err) {
      return false;
    }
  };
  
  const pathExists = (targetPath) => {
    const safe = String(targetPath || "").trim();
    if (!safe) return false;
    try {
      return fs.existsSync(safe);
    } catch (_err) {
      return false;
    }
  };
  
  const findExecutableByNamesInDir = (rootDir, names = [], maxDepth = 6) => {
    const root = String(rootDir || "").trim();
    if (!root) return "";
    try {
      if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) return "";
    } catch (_err) {
      return "";
    }
    const wanted = new Set(names.map((name) => String(name || "").toLowerCase()).filter(Boolean));
    const queue = [{ dir: root, depth: 0 }];
    while (queue.length) {
      const cur = queue.shift();
      if (!cur || cur.depth > maxDepth) continue;
      let entries = [];
      try {
        entries = fs.readdirSync(cur.dir, { withFileTypes: true });
      } catch (_err) {
        continue;
      }
      for (const entry of entries) {
        const full = path.join(cur.dir, entry.name);
        if (entry.isDirectory()) {
          queue.push({ dir: full, depth: cur.depth + 1 });
        } else if (entry.isFile() && wanted.has(entry.name.toLowerCase())) {
          return full;
        }
      }
    }
    return "";
  };
  
  const resolveSekaiemuExecutable = () => {
    const settings = getSekaiemuSettings();
    const exeNames = process.platform === "win32"
      ? ["sekaiemu_libretro_spike.exe", "sekaiemu.exe"]
      : ["sekaiemu_libretro_spike", "sekaiemu"];
    const home = app.getPath("home");
    const runtimeBinCandidates = exeNames.flatMap((exeName) => [
      getRuntimePlatformPath("bin", exeName),
      path.join(getBundledRuntimeDir(), "bin", exeName),
      path.join(getBundledRuntimeDir(), "sekaiemu", exeName),
    ]);
    const devCandidates = app.isPackaged ? [] : [
      path.join("/tmp", "sekaiemu-libretro-spike-beta3-build", exeNames[0]),
      path.join(home, "Projects", "Sekaiemu-Libretro-Spike-Codex", "workspace", "sekaiemu-libretro-spike", "build", exeNames[0]),
      path.join(home, "Sekaiemu-Libretro-Spike-Codex", "workspace", "sekaiemu-libretro-spike", "build", exeNames[0]),
    ];
    const candidates = [
      settings.exe_path,
      ...runtimeBinCandidates,
      ...devCandidates,
    ];
    for (const candidate of candidates) {
      if (fileExists(candidate)) return candidate;
    }
    const roots = [
      settings.root_dir,
      getRuntimePlatformPath("sekaiemu"),
      path.join(getBundledRuntimeDir(), "sekaiemu"),
      ...(app.isPackaged ? [] : [
        path.join(home, "Projects", "Sekaiemu-Libretro-Spike-Codex", "workspace", "sekaiemu-libretro-spike"),
      ]),
    ].filter(Boolean);
    for (const root of roots) {
      const found = findExecutableByNamesInDir(root, exeNames, 5);
      if (found) return found;
    }
    return "";
  };
  
  const resolvePathFromRoots = (candidate, roots = [], existsPredicate = fileExists) => {
    const safe = String(candidate || "").trim();
    if (!safe) return "";
    if (path.isAbsolute(safe) && existsPredicate(safe)) return safe;
    for (const root of roots) {
      const base = String(root || "").trim();
      if (!base) continue;
      const resolved = path.join(base, safe);
      if (existsPredicate(resolved)) return resolved;
    }
    return "";
  };

  const sha256File = (filePath) => {
    const hash = crypto.createHash("sha256");
    const data = fs.readFileSync(filePath);
    hash.update(data);
    return hash.digest("hex");
  };

  const normalizeSystemFileEntries = (manifest = {}) => {
    const entries = Array.isArray(manifest.system_files) ? manifest.system_files : [];
    return entries
      .map((entry) => {
        if (typeof entry === "string") return { name: entry, target: entry };
        if (!entry || typeof entry !== "object") return null;
        const name = String(entry.name || entry.file || entry.path || "").trim();
        const target = String(entry.target || entry.name || "").trim();
        if (!name || !target) return null;
        return {
          name,
          target,
          size: Number(entry.size || 0) || 0,
          sha256: String(entry.sha256 || "").trim().toLowerCase(),
          description: String(entry.description || "").trim(),
        };
      })
      .filter(Boolean);
  };

  const stageSekaiemuSystemFiles = (manifest = {}, systemDir = "") => {
    const required = normalizeSystemFileEntries(manifest);
    if (!required.length || !systemDir) return { ok: true, staged: [] };
    const searchRoots = [
      path.join(app.getPath("userData"), "firmware"),
      path.join(getBundledRuntimeDir(), "firmware"),
      path.join(getBundledRuntimeDir(), "system"),
      getRuntimePlatformPath("firmware"),
      getRuntimePlatformPath("system"),
    ].filter(Boolean);
    const staged = [];
    for (const entry of required) {
      const targetPath = path.join(systemDir, entry.target);
      const validTarget = (() => {
        if (!fileExists(targetPath)) return false;
        try {
          if (entry.size && fs.statSync(targetPath).size !== entry.size) return false;
          if (entry.sha256 && sha256File(targetPath) !== entry.sha256) return false;
          return true;
        } catch (_err) {
          return false;
        }
      })();
      if (validTarget) {
        staged.push({ name: entry.name, target: targetPath, reused: true });
        continue;
      }

      const candidates = [entry.name, entry.target].filter(Boolean);
      let sourcePath = "";
      for (const root of searchRoots) {
        for (const candidate of candidates) {
          const resolved = path.join(root, candidate);
          if (!fileExists(resolved)) continue;
          try {
            if (entry.size && fs.statSync(resolved).size !== entry.size) continue;
            if (entry.sha256 && sha256File(resolved) !== entry.sha256) continue;
            sourcePath = resolved;
            break;
          } catch (_err) {
            // Keep scanning.
          }
        }
        if (sourcePath) break;
      }
      if (!sourcePath) {
        return {
          ok: false,
          error: "sekaiemu_system_file_missing",
          file: entry.name,
          target: entry.target,
          detail: entry.description || "Required firmware/system file was not found.",
        };
      }
      ensureDir(path.dirname(targetPath));
      fs.copyFileSync(sourcePath, targetPath);
      staged.push({ name: entry.name, source: sourcePath, target: targetPath, reused: false });
      writeLogLine("info", "sekaiemu", `staged system file ${entry.name} -> ${targetPath}`);
    }
    return { ok: true, staged };
  };
  
  const resolveSekaiemuCorePath = (manifest = {}) => {
    const settings = getSekaiemuSettings();
    const sekaiemu = manifest.sekaiemu && typeof manifest.sekaiemu === "object" ? manifest.sekaiemu : {};
    const corePath = String(sekaiemu.core_path || manifest.libretro_core_path || "").trim();
    const coreId = String(sekaiemu.core_id || manifest.libretro_core_id || manifest?.driver?.core_id || "").trim();
    const home = app.getPath("home");
    const roots = [
      ...settings.core_dirs,
      getRuntimePlatformPath("cores"),
      path.join(getBundledRuntimeDir(), "cores"),
      path.join(getBundledRuntimeDir(), "libretro"),
      ...(app.isPackaged ? [] : [
        path.join(home, "Projects", "Sekaiemu-Libretro-Spike-Codex", "workspace", "src"),
      ]),
    ];
    const direct = resolvePathFromRoots(corePath, roots);
    if (direct) return direct;
  
    const ext = process.platform === "win32" ? ".dll" : ".so";
    const names = (...baseNames) => baseNames.map((name) => `${name}${ext}`);
    const aliases = {
      bsnes: names("bsnes_mercury_performance_libretro", "bsnes_mercury_balanced_libretro", "bsnes_libretro", "snes9x_libretro"),
      snes: names("bsnes_mercury_performance_libretro", "bsnes_mercury_balanced_libretro", "snes9x_libretro"),
      snes9x: names("snes9x_libretro"),
      gba: names("mgba_libretro"),
      mgba: names("mgba_libretro"),
      gb: names("gambatte_libretro"),
      gbc: names("gambatte_libretro"),
      gambatte: names("gambatte_libretro"),
      nes: names("nestopia_libretro", "fceumm_libretro"),
      nestopia: names("nestopia_libretro"),
      fceumm: names("fceumm_libretro"),
      n64: names("mupen64plus_next_libretro", "parallel_n64_libretro"),
      mupen64plus: names("mupen64plus_next_libretro"),
      parallel_n64: names("parallel_n64_libretro"),
    };
    const wanted = aliases[coreId.toLowerCase()] || (coreId ? [coreId] : []);
    if (!wanted.length) return "";
    for (const root of roots) {
      const found = findExecutableByNamesInDir(root, wanted, 5);
      if (found) return found;
    }
    return "";
  };
  
  const parseArchipelagoAddress = (address) => {
    const raw = String(address || "").trim();
    if (!raw) return null;
    try {
      const url = new URL(raw.includes("://") ? raw : `ws://${raw}`);
      const port = Number(url.port || (url.protocol === "wss:" ? 443 : 0));
      return {
        host: url.hostname,
        port: Number.isFinite(port) ? port : 0,
        path: url.pathname && url.pathname !== "" ? url.pathname : "/",
      };
    } catch (_err) {
      const [host, portText] = raw.split(":");
      const port = Number(portText || 0);
      if (!host || !Number.isFinite(port)) return null;
      return { host, port, path: "/" };
    }
  };
  
  const resolveSklmiRuntimeForSekaiemu = () => {
    const runtimeDir = getBundledRuntimeDir();
    const exeName = process.platform === "win32" ? "sekailink_sklmi_runtime.exe" : "sekailink_sklmi_runtime";
    const sourceRepoRoot = path.resolve(__dirname, "../../../..");
    const devCandidates = app.isPackaged ? [] : [
      path.join(sourceRepoRoot, "services", "sklmi", "build", exeName),
      path.join(sourceRepoRoot, "runtime", "bin", exeName),
    ];
    const candidates = [
      process.env.SEKAILINK_SKLMI_RUNTIME,
      getRuntimePlatformPath("bin", exeName),
      path.join(runtimeDir, "bin", exeName),
      path.join(runtimeDir, "sklmi", exeName),
      path.join(runtimeDir, exeName),
      ...devCandidates,
    ];
    for (const candidate of candidates) {
      if (fileExists(candidate)) return candidate;
    }
    return "";
  };
  
  const resolveSklmiManifestDirForSekaiemu = () => {
    const runtimeDir = getBundledRuntimeDir();
    const sourceRepoRoot = path.resolve(__dirname, "../../../..");
    const devCandidates = app.isPackaged ? [] : [
      path.join(sourceRepoRoot, "services", "sklmi", "manifests"),
      path.join(sourceRepoRoot, "runtime", "sklmi", "manifests"),
    ];
    const candidates = [
      process.env.SEKAILINK_SKLMI_MANIFEST_DIR,
      getRuntimePlatformPath("sklmi", "manifests"),
      path.join(runtimeDir, "sklmi", "manifests"),
      path.join(runtimeDir, "manifests", "sklmi"),
      path.join(runtimeDir, "manifests"),
      ...devCandidates,
    ];
    for (const candidate of candidates) {
      try {
        if (candidate && fs.existsSync(candidate) && fs.statSync(candidate).isDirectory()) return candidate;
      } catch (_err) {
        // keep scanning
      }
    }
    return "";
  };
  
  const resolveSekaiemuTrackerPackPath = (manifest = {}, roots = [], options = {}) => {
    const gameId = String(manifest.game_id || manifest.gameId || "").trim();
    const sekaiemu = manifest.sekaiemu && typeof manifest.sekaiemu === "object" ? manifest.sekaiemu : {};
    const allowInstalledFallback = options.allowInstalledFallback !== false;
    const adaptedCandidates = [
      sekaiemu.sklmi_tracker_pack,
      sekaiemu.sklmi_tracker_pack_path,
      manifest.sklmi_tracker_pack_path,
      manifest.sklmi_tracker_pack,
      gameId ? path.join("tracker-bundles", `${gameId}-linkedworld-default.zip`) : "",
      gameId ? path.join("tracker-bundles", `${gameId}-linkedworld-default`) : "",
    ].filter(Boolean);
    for (const candidate of adaptedCandidates) {
      const resolved = resolvePathFromRoots(String(candidate || "").trim(), roots, pathExists) || getRuntimeFilePath(String(candidate || "").trim());
      if (resolved && pathExists(resolved)) return resolved;
    }
    if (allowInstalledFallback && gameId) {
      const installed = getInstalledTrackerPack(gameId);
      if (installed?.path && pathExists(installed.path)) return String(installed.path);
    }
    const declared = String(
      sekaiemu.tracker_pack ||
        sekaiemu.tracker_pack_path ||
        manifest.tracker_pack_path ||
        ""
    ).trim();
    if (declared && !path.isAbsolute(declared)) {
      const runtimePath = getRuntimeFilePath(declared);
      if (pathExists(runtimePath)) return runtimePath;
      if (declared.toLowerCase().endsWith(".zip")) {
        const unpackedRuntimePath = getRuntimeFilePath(declared.slice(0, -4));
        if (pathExists(unpackedRuntimePath)) return unpackedRuntimePath;
      }
    }
    const resolved = resolvePathFromRoots(declared, roots, pathExists);
    if (resolved) return resolved;
    if (declared.toLowerCase().endsWith(".zip")) {
      return resolvePathFromRoots(declared.slice(0, -4), roots, pathExists);
    }
    return "";
  };
  
  
  const tryLaunchSekaiemu = async (options = {}) => {
    const moduleId = String(options.moduleId || "").trim();
    const manifest = options.manifest || getModuleManifest(moduleId) || {};
    const romPath = String(options.romPath || "").trim();
    const layoutPreview = Boolean(options.layoutPreview);
    const settings = getSekaiemuSettings();
    const sekaiemu = manifest.sekaiemu && typeof manifest.sekaiemu === "object" ? manifest.sekaiemu : {};
    const exePath = resolveSekaiemuExecutable();
    if (!exePath) return { ok: false, error: "sekaiemu_not_found" };
    const requestedCorePath = String(options.corePath || "").trim();
    const corePath = layoutPreview
      ? ""
      : (requestedCorePath && fileExists(requestedCorePath)
        ? requestedCorePath
        : resolveSekaiemuCorePath(manifest));
    if (!layoutPreview && !corePath) return { ok: false, error: "sekaiemu_core_missing" };
    if (!layoutPreview && (!romPath || !fileExists(romPath))) return { ok: false, error: "rom_missing", detail: "patched_rom_not_found" };
  
    const safeModuleId = moduleId || String(manifest.game_id || "game").trim() || "game";
    const runtimeRoot = path.join(app.getPath("userData"), "sekaiemu", safeModuleId);
    const systemDir = settings.system_dir || path.join(runtimeRoot, "system");
    const romSaveKey = !layoutPreview && romPath
      ? `${path.basename(romPath, path.extname(romPath)).replace(/[^a-z0-9_.-]+/gi, "_").slice(0, 72)}-${crypto
          .createHash("sha1")
          .update(path.resolve(romPath))
          .digest("hex")
          .slice(0, 10)}`
      : "";
    const saveDir = settings.save_dir || path.join(runtimeRoot, "saves", romSaveKey || "default");
    const logDir = settings.log_dir || path.join(app.getPath("userData"), "logs", "sekaiemu");
    ensureDir(systemDir);
    ensureDir(saveDir);
    ensureDir(logDir);
    const systemFilesRes = stageSekaiemuSystemFiles(manifest, systemDir);
    if (!systemFilesRes.ok) {
      return {
        ok: false,
        error: systemFilesRes.error || "sekaiemu_system_file_missing",
        detail: systemFilesRes.detail || systemFilesRes.file || "",
        file: systemFilesRes.file || "",
      };
    }
    writeSekaiemuRuntimeConfig(saveDir, settings);
  
    const requestedMemorySocket = String(options.memorySocketPath || "").trim();
    const needsBizHawkProtocolPort = !layoutPreview && !requestedMemorySocket && moduleUsesBizHawkProtocolClient(manifest);
    const bizHawkProtocolPort = needsBizHawkProtocolPort
      ? await findFreeLocalPortInRange(43055, 43059)
      : 0;
    if (needsBizHawkProtocolPort && !bizHawkProtocolPort) {
      return { ok: false, error: "bizhawk_protocol_port_unavailable", detail: "Ports 43055-43059 are already in use." };
    }
    const memorySocketPath = layoutPreview
      ? ""
      : (requestedMemorySocket || (
        bizHawkProtocolPort
          ? `tcp://127.0.0.1:${bizHawkProtocolPort}`
          : process.platform === "win32"
          ? `tcp://127.0.0.1:${await findFreeLocalPort(43080)}`
          : path.join(os.tmpdir(), `sekailink-sekaiemu-${Date.now()}-${crypto.randomBytes(4).toString("hex")}.sock`)
      ));
    const args = layoutPreview
      ? ["--layout-preview", "--save-dir", saveDir, "--log-dir", logDir, options.startFullscreen ? "--fullscreen" : "--windowed"]
      : ["--core", corePath, "--game", romPath, "--system-dir", systemDir, "--save-dir", saveDir, "--log-dir", logDir, "--memory-socket", memorySocketPath];
    const runtimeDir = getBundledRuntimeDir();
    const overlayRuntimeDir = getOverlayRuntimeDir();
    const roots = [
      overlayRuntimeDir,
      runtimeDir,
      path.dirname(exePath),
      path.join(path.dirname(exePath), ".."),
      path.join(app.getPath("home"), "Projects", "Sekaiemu-Libretro-Spike-Codex", "workspace", "sekaiemu-libretro-spike"),
    ];
    const profilePath = resolvePathFromRoots(String(sekaiemu.profile_path || sekaiemu.profile || "").trim(), roots);
    if (!layoutPreview && profilePath) args.push("--profile", profilePath);
    const sklmiRuntime = layoutPreview ? "" : resolveSklmiRuntimeForSekaiemu();
    const sklmiManifestDir = layoutPreview ? "" : resolveSklmiManifestDirForSekaiemu();
    if (!layoutPreview && sklmiRuntime) args.push("--sklmi-runtime", sklmiRuntime);
    if (!layoutPreview && sklmiManifestDir) args.push("--sklmi-manifest-dir", sklmiManifestDir);
  
    const apAddress = parseArchipelagoAddress(options.serverAddress);
    const apGame = String(sekaiemu.ap_game || manifest.ap_game || manifest.display_name || "").trim();
    const apSlot = String(options.slot || "").trim();
    const playerAlias = String(options.playerAlias || "").trim();
    const cleanupModuleId = safeModuleId;
    const cleanupSlot = apSlot;
    if (!layoutPreview && apAddress?.host && apAddress.port && apGame && apSlot) {
      args.push(
        "--ap-host", apAddress.host,
        "--ap-port", String(apAddress.port),
        "--ap-path", apAddress.path || "/",
        "--ap-game", apGame,
        "--ap-slot-name", apSlot,
        "--ap-uuid", `sekailink-${safeModuleId}`
      );
      if (options.password) args.push("--ap-password", String(options.password));
      if (playerAlias) args.push("--player-alias", playerAlias);
      args.push("--ap-tags", "AP,SekaiLink,SKLMI");
    }
    writeLogLine("info", "sekaiemu", `internal tracker disabled for BETA-3 runtime: module=${safeModuleId}`);
    if (!layoutPreview) {
      const trackerPack = resolveSekaiemuTrackerPackPath(manifest, [
        overlayRuntimeDir,
        runtimeDir,
        path.join(runtimeDir, "tracker-bundles"),
        path.dirname(exePath),
        path.join(path.dirname(exePath), ".."),
      ], { allowInstalledFallback: false });
      if (trackerPack) {
        args.push("--tracker-pack", trackerPack);
        const trackerVariant = String(options.trackerVariant || options.packVariant || getTrackerVariant(String(manifest.game_id || safeModuleId))).trim();
        if (trackerVariant && trackerVariant !== "default") args.push("--tracker-variant", trackerVariant);
        writeLogLine("info", "sekaiemu", `tracker pack provided to SKLMI companion: module=${safeModuleId} pack=${trackerPack} variant=${trackerVariant || "default"}`);
      }
    }
    if (!layoutPreview && Array.isArray(sekaiemu.args)) {
      for (const entry of sekaiemu.args) {
        const value = String(entry || "").trim();
        if (value) args.push(value);
      }
    }
    const chatBridge = layoutPreview ? null : startSekaiemuChatBridge({
      moduleId: safeModuleId,
      ...(isPlainObject(options.chatBridge) ? options.chatBridge : {}),
      apiBaseUrl: options.apiBaseUrl,
      authToken: options.authToken,
      deviceId: options.deviceId,
    });
    if (chatBridge) {
      args.push("--chat-inbox", chatBridge.inboxPath, "--chat-outbox", chatBridge.outboxPath);
    }
    if (!layoutPreview) args.push(...settings.args);
  
    try {
      fs.chmodSync(exePath, 0o755);
    } catch (_err) {
      // ignore chmod failures
    }
  
    try {
      const spawnEnv = { ...process.env };
      if (process.platform === "win32") {
        const runtimeBinDir = path.dirname(exePath);
        const priorPath = spawnEnv.PATH || spawnEnv.Path || "";
        spawnEnv.PATH = priorPath ? `${runtimeBinDir}${path.delimiter}${priorPath}` : runtimeBinDir;
        spawnEnv.Path = spawnEnv.PATH;
      }
      const wrapped = spawnMaybeGamescope(exePath, args, { stdio: "ignore", env: spawnEnv });
      if (!wrapped.ok) {
        chatBridge?.stop?.();
        return { ok: false, error: wrapped.error || "sekaiemu_launch_failed", detail: wrapped.detail || "" };
      }
      nativeGameProcs.set(wrapped.proc.pid, wrapped.proc);
      rememberSekaiemuSession(wrapped.proc.pid, {
        exePath,
        corePath,
        romPath,
        memorySocketPath,
        moduleId: safeModuleId,
        layoutPreview,
        launchedAt: nowIso(),
      });
      if (chatBridge) sekaiemuChatBridges.set(wrapped.proc.pid, chatBridge);
      wrapped.proc.on("exit", () => {
        nativeGameProcs.delete(wrapped.proc.pid);
        forgetSekaiemuSession(wrapped.proc.pid);
        if (!layoutPreview && cleanupSlot) {
          stopArchipelagoClientsForSession(cleanupModuleId, cleanupSlot, `sekaiemu_exit:${wrapped.proc.pid}`).catch((err) => {
            writeLogLine("warn", "archipelagoclient", `session cleanup after sekaiemu exit failed: ${String(err?.message || err || "")}`);
          });
        }
        const activeBridge = sekaiemuChatBridges.get(wrapped.proc.pid);
        activeBridge?.stop?.();
        sekaiemuChatBridges.delete(wrapped.proc.pid);
      });
      return { ok: true, pid: wrapped.proc.pid, method: "libretro-spike", exePath, corePath, romPath, memorySocketPath, layoutPreview, chatBridge };
    } catch (err) {
      chatBridge?.stop?.();
      return { ok: false, error: "sekaiemu_launch_failed", detail: String(err || "") };
    }
  };

  return {
    getSekaiemuSettings,
    writeSekaiemuRuntimeConfig,
    fileExists,
    dirExists,
    pathExists,
    findExecutableByNamesInDir,
    resolveSekaiemuExecutable,
    resolveSekaiemuCorePath,
    parseArchipelagoAddress,
    resolveSklmiRuntimeForSekaiemu,
    resolveSklmiManifestDirForSekaiemu,
    resolveSekaiemuTrackerPackPath,
    tryLaunchSekaiemu,
  };
};

module.exports = { createSekaiemuRuntime };
