chatroom = [
    "The Hidden Flame Tavern",
    "Fading Ember Forge",
    "Underground Gallery 56",
    "The Broken Star Pub",
    "The Cloak Room",
    "Shake Your Tailfeathers Hall",
    "Cloudchaser Inn",
    "Sunspire Aviary",
    "Whispering Winds Market",
    "Beast Beat Club",
    "Critter Carnival",
    "Pride Paws Park",
    "Fursona Studios",
    "Flufftail Forest",
    "Howl & Roar Arcade",
    "Whiskers & Claws Spa",
    "The Bear's Den",
    "Tail Wagger's Lounge",
    "The Furred Haven Caf\u00E9",
    "Radiant Cinema",
    "Aurora Dance Studio",
    "Unity Gym",
    "Sapphire Shores Beach Club",
    "The Ally Alley",
    "The Velvet Underground",
    "Equality Park",
    "Celestial Glow Spa",
    "Colors Caf\u00E9 & Bakery",
    "The Quirk Collective",
    "Spectrum Arcade",
    "Pride Plaza",
    "Queertopia",
    "Phoenix Fire Tattoo Parlor",
    "Crimson Dawn Bridge",
    "Emberwood Refuge",
    "Veiled Vein Tunnel",
    "Windswept Hilltop",
    "The Golden Paw Lodge",
    "Feathers & Fins Falls",
    "Wild Whiskers Motel",
    "Moonlit Meadows",
]
prog = [
    "\u2605SGDQ Main Stage\u2605",
    "\u2605Tier 3 Subscriber Lounge\u2605",
    "\u2605The Elite 4\u2605",
    "\u2605Kitten's Chair\u2605",
    "\u2605Local Bird Sanctuary\u2605",
    "\u2605Bowser's Hot Tub\u2605",
    "\u2605Moon Kingdom\u2605",
    "\u2605The Odyssey\u2605",
    "\u2605Adam's Couch\u2605",
    "\u2605Delilah's Basement\u2605"
]